// @generated by web/scripts/sync-examples.mjs — DO NOT EDIT.
// Source of truth: examples/cell-spec/A123__ANR26650M1-B.json
// Regenerate: npm run sync:examples   (see docs/CONTENT-MODEL.md §4)

// The full canonical record, verbatim from examples/**.
export const cellSpecCanonical = {
  "schema_version": "0.1.0",
  "cell_spec": {
    "id": "https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5",
    "short_id": "7d9k2m",
    "identifier": "cell-spec:7d9k-2m4p-8t3x-6nq5",
    "name": "A123 ANR26650M1-B",
    "model": "ANR26650M1-B",
    "manufacturer": {
      "type": "Organization",
      "name": "A123",
      "id": "https://w3id.org/battinfo/organization/9k3e-absq-8131-vyjd"
    },
    "brand": {
      "type": "Brand",
      "name": "A123"
    },
    "category": "battery cell",
    "cell_format": "cylindrical",
    "chemistry": "Li-ion",
    "positive_electrode_basis": "LFP",
    "negative_electrode_basis": "unknown",
    "size_code": "R26650",
    "iec_code": "IFpR26650",
    "country_of_origin": "United States",
    "year": 2012
  },
  "properties": {
    "nominal_capacity": {
      "value": 2.5,
      "unit": "Ah",
      "raw": {
        "text": "Cell Capacity (nominal/minimum) (0.5C Rate) 2.5/2.4 Ah",
        "page": 1,
        "confidence": 0.8
      }
    },
    "minimum_capacity": {
      "value": 2.4,
      "unit": "Ah",
      "raw": {
        "text": "Cell Capacity (nominal/minimum) (0.5C Rate) 2.5/2.4 Ah",
        "page": 1,
        "confidence": 0.8
      }
    },
    "nominal_voltage": {
      "value": 3.3,
      "unit": "V",
      "raw": {
        "text": "Voltage (nominal) 3.3V",
        "page": 1,
        "confidence": 0.8
      }
    },
    "internal_resistance": {
      "value": 6,
      "unit": "mΩ",
      "raw": {
        "text": "Internal Impedance (1kHz AC typical) 6mΩ",
        "page": 1,
        "confidence": 0.8
      }
    },
    "mass": {
      "value": 76,
      "unit": "g",
      "raw": {
        "text": "Cell Weight 76g",
        "page": 1,
        "confidence": 0.8
      }
    },
    "diameter": {
      "value": 26,
      "unit": "mm",
      "raw": {
        "text": "Cell Dimensions 26 x 65 mm",
        "page": 1,
        "confidence": 0.8
      }
    },
    "height": {
      "value": 65,
      "unit": "mm",
      "raw": {
        "text": "Cell Dimensions 26 x 65 mm",
        "page": 1,
        "confidence": 0.8
      }
    },
    "pulse_charging_current": {
      "value": 10,
      "unit": "A",
      "raw": {
        "text": "Recommended Fast Charge Method to 80% SOC 10A to 3.6V CC, 12 min",
        "page": 1,
        "confidence": 0.8
      }
    },
    "nominal_continuous_charging_current": {
      "value": 2.5,
      "unit": "A",
      "raw": {
        "text": "Recommended Standard Charge Method 2.5A to 3.6V CCCV, 60 min",
        "page": 1,
        "confidence": 0.8
      }
    },
    "maximum_continuous_charging_current": {
      "value": 2.5,
      "unit": "A",
      "raw": {
        "text": "Recommended Standard Charge Method 2.5A to 3.6V CCCV, 60 min",
        "page": 1,
        "confidence": 0.8
      }
    },
    "maximum_continuous_discharging_current": {
      "value": 50,
      "unit": "A",
      "raw": {
        "text": "Maximum Continuous Discharge 50A",
        "page": 1,
        "confidence": 0.8
      }
    },
    "minimum_discharging_temperature": {
      "value": -30,
      "unit": "°C",
      "raw": {
        "text": "Operating Temperature -30°C to 55°C",
        "page": 1,
        "confidence": 0.8
      }
    },
    "maximum_discharging_temperature": {
      "value": 55,
      "unit": "°C",
      "raw": {
        "text": "Operating Temperature -30°C to 55°C",
        "page": 1,
        "confidence": 0.8
      }
    },
    "minimum_storage_temperature": {
      "value": -40,
      "unit": "°C",
      "raw": {
        "text": "Storage Temperature -40°C to 60°C",
        "page": 1,
        "confidence": 0.8
      }
    },
    "maximum_storage_temperature": {
      "value": 60,
      "unit": "°C",
      "raw": {
        "text": "Storage Temperature -40°C to 60°C",
        "page": 1,
        "confidence": 0.8
      }
    },
    "cycle_life": {
      "value_text": ">1000",
      "unit": "count",
      "raw": {
        "text": "Cycle Life at 20A Discharge, 100% DOD >1,000 cycles",
        "page": 1,
        "confidence": 0.7
      }
    }
  },
  "provenance": {
    "source_type": "datasheet",
    "source_file": "A123__ANR26650M1-B.pdf",
    "source_url": null,
    "file_hash": "b5069f48e121de3a1308af66215e7a97a1c8c6a87227da089c83e352f1ddf35e",
    "retrieved_at": 1769585584
  }
} as const;

// A friendly authored-input teaser derived from the canonical record, so its
// values can never drift from the source record.
export const cellSpecInput = {
  "schema_version": "0.1.0",
  "cell_spec": {
    "name": "A123 ANR26650M1-B",
    "model": "ANR26650M1-B",
    "manufacturer": {
      "type": "Organization",
      "name": "A123",
      "id": "https://w3id.org/battinfo/organization/9k3e-absq-8131-vyjd"
    },
    "category": "battery cell",
    "cell_format": "cylindrical",
    "chemistry": "Li-ion",
    "positive_electrode_basis": "LFP"
  },
  "properties": {
    "nominal_capacity": {
      "value": 2.5,
      "unit": "Ah",
      "raw": {
        "text": "Cell Capacity (nominal/minimum) (0.5C Rate) 2.5/2.4 Ah",
        "page": 1,
        "confidence": 0.8
      }
    },
    "nominal_voltage": {
      "value": 3.3,
      "unit": "V",
      "raw": {
        "text": "Voltage (nominal) 3.3V",
        "page": 1,
        "confidence": 0.8
      }
    },
    "mass": {
      "value": 76,
      "unit": "g",
      "raw": {
        "text": "Cell Weight 76g",
        "page": 1,
        "confidence": 0.8
      }
    },
    "diameter": {
      "value": 26,
      "unit": "mm",
      "raw": {
        "text": "Cell Dimensions 26 x 65 mm",
        "page": 1,
        "confidence": 0.8
      }
    },
    "height": {
      "value": 65,
      "unit": "mm",
      "raw": {
        "text": "Cell Dimensions 26 x 65 mm",
        "page": 1,
        "confidence": 0.8
      }
    }
  }
} as const;
