// GENERATED by scripts/gen_web_jsonld.py — do not edit.
// Each pair is the canonical example record and the JSON-LD the REAL
// Python transform emits for it (battinfo.record_to_jsonld).
// tests/test_web_generated.py fails when this file drifts from the library.

export const jsonldGallery: {
  slug: string;
  label: string;
  recordType: string;
  sourceFile: string;
  highlight: string;
  record: Record<string, unknown>;
  jsonld: Record<string, unknown>;
}[] = [
  {
    "slug": "cell-spec",
    "label": "Cell spec — A123 ANR26650M1-B",
    "recordType": "cell-spec",
    "sourceFile": "examples/cell-spec/A123__ANR26650M1-B.json",
    "highlight": "EMMO @type stacking: one cylindrical LFP cell is simultaneously a BatteryCell, a CylindricalBattery, and a LithiumIronPhosphateBattery — no manual annotation.",
    "record": {
      "schema_version": "0.2.0",
      "cell_spec": {
        "id": "https://w3id.org/battinfo/spec/pge5-wer6-2q82-v9k0",
        "short_id": "pge5we",
        "identifier": "cell-spec:pge5-wer6-2q82-v9k0",
        "name": "A123 ANR26650M1-B",
        "model": "ANR26650M1-B",
        "manufacturer": {
          "type": "Organization",
          "name": "A123",
          "id": "https://w3id.org/battinfo/organization/8z6j-n7vw-e73w-smh7"
        },
        "brand": {
          "type": "Brand",
          "name": "A123"
        },
        "category": "battery cell",
        "cell_format": "cylindrical",
        "chemistry": "Li-ion",
        "positive_electrode_basis": "LFP",
        "negative_electrode_basis": "unknown",
        "size_code": "R26650",
        "iec_code": "IFpR26650",
        "country_of_origin": "United States",
        "year": 2012
      },
      "properties": {
        "nominal_capacity": {
          "value": 2.5,
          "unit": "Ah",
          "raw": {
            "text": "Cell Capacity (nominal/minimum) (0.5C Rate) 2.5/2.4 Ah",
            "page": 1,
            "confidence": 0.8
          }
        },
        "minimum_capacity": {
          "value": 2.4,
          "unit": "Ah",
          "raw": {
            "text": "Cell Capacity (nominal/minimum) (0.5C Rate) 2.5/2.4 Ah",
            "page": 1,
            "confidence": 0.8
          }
        },
        "nominal_voltage": {
          "value": 3.3,
          "unit": "V",
          "raw": {
            "text": "Voltage (nominal) 3.3V",
            "page": 1,
            "confidence": 0.8
          }
        },
        "internal_resistance": {
          "value": 6.0,
          "unit": "mΩ",
          "raw": {
            "text": "Internal Impedance (1kHz AC typical) 6mΩ",
            "page": 1,
            "confidence": 0.8
          }
        },
        "mass": {
          "value": 76.0,
          "unit": "g",
          "raw": {
            "text": "Cell Weight 76g",
            "page": 1,
            "confidence": 0.8
          }
        },
        "diameter": {
          "value": 26.0,
          "unit": "mm",
          "raw": {
            "text": "Cell Dimensions 26 x 65 mm",
            "page": 1,
            "confidence": 0.8
          }
        },
        "height": {
          "value": 65.0,
          "unit": "mm",
          "raw": {
            "text": "Cell Dimensions 26 x 65 mm",
            "page": 1,
            "confidence": 0.8
          }
        },
        "pulse_charging_current": {
          "value": 10.0,
          "unit": "A",
          "raw": {
            "text": "Recommended Fast Charge Method to 80% SOC 10A to 3.6V CC, 12 min",
            "page": 1,
            "confidence": 0.8
          }
        },
        "maximum_continuous_charging_current": {
          "value": 2.5,
          "unit": "A",
          "raw": {
            "text": "Recommended Standard Charge Method 2.5A to 3.6V CCCV, 60 min",
            "page": 1,
            "confidence": 0.8
          }
        },
        "maximum_continuous_discharging_current": {
          "value": 50.0,
          "unit": "A",
          "raw": {
            "text": "Maximum Continuous Discharge 50A",
            "page": 1,
            "confidence": 0.8
          }
        },
        "minimum_discharging_temperature": {
          "value": -30,
          "unit": "°C",
          "raw": {
            "text": "Operating Temperature -30°C to 55°C",
            "page": 1,
            "confidence": 0.8
          }
        },
        "maximum_discharging_temperature": {
          "value": 55,
          "unit": "°C",
          "raw": {
            "text": "Operating Temperature -30°C to 55°C",
            "page": 1,
            "confidence": 0.8
          }
        },
        "minimum_storage_temperature": {
          "value": -40,
          "unit": "°C",
          "raw": {
            "text": "Storage Temperature -40°C to 60°C",
            "page": 1,
            "confidence": 0.8
          }
        },
        "maximum_storage_temperature": {
          "value": 60,
          "unit": "°C",
          "raw": {
            "text": "Storage Temperature -40°C to 60°C",
            "page": 1,
            "confidence": 0.8
          }
        },
        "cycle_life": {
          "value_text": ">1000",
          "unit": "count",
          "raw": {
            "text": "Cycle Life at 20A Discharge, 100% DOD >1,000 cycles",
            "page": 1,
            "confidence": 0.7
          }
        }
      },
      "provenance": {
        "source_type": "datasheet",
        "source_file": "A123__ANR26650M1-B.pdf",
        "source_url": null,
        "file_hash": "b5069f48e121de3a1308af66215e7a97a1c8c6a87227da089c83e352f1ddf35e",
        "retrieved_at": 1769585584
      }
    },
    "jsonld": {
      "@context": "https://w3id.org/battinfo/context/records/v1.json",
      "@type": [
        "BatteryCellSpecification",
        "schema:CreativeWork"
      ],
      "@id": "https://w3id.org/battinfo/spec/pge5-wer6-2q82-v9k0",
      "schema:identifier": "pge5-wer6-2q82-v9k0",
      "schema:name": "A123 ANR26650M1-B",
      "schema:model": "ANR26650M1-B",
      "schema:manufacturer": {
        "@type": "schema:Organization",
        "schema:name": "A123"
      },
      "schema:url": "https://www.battery-genome.org/registry/spec/pge5-wer6-2q82-v9k0",
      "isDescriptionFor": {
        "@type": [
          "BatteryCell",
          "CylindricalBattery",
          "LithiumIonBattery",
          "LithiumIonIronPhosphateBattery"
        ],
        "skos:prefLabel": "A123 ANR26650M1-B"
      },
      "schema:size": "R26650",
      "schema:productID": "IFpR26650",
      "schema:brand": {
        "@type": "schema:Brand",
        "schema:name": "A123"
      },
      "schema:category": "battery cell",
      "schema:countryOfOrigin": {
        "@type": "schema:Country",
        "schema:name": "United States"
      },
      "schema:releaseDate": "2012-01-01",
      "schema:schemaVersion": "0.2.0",
      "hasProperty": [
        {
          "@type": [
            "NominalCapacity",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "NominalCapacity",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 2.5
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#AmpereHour"
        },
        {
          "@type": [
            "MinimumCapacity",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MinimumCapacity",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 2.4
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#AmpereHour"
        },
        {
          "@type": [
            "NominalVoltage",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "NominalVoltage",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 3.3
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Volt"
        },
        {
          "@type": [
            "InternalResistance",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "InternalResistance",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 6.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#MilliOhm"
        },
        {
          "@type": [
            "Mass",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "Mass",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 76.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Gram"
        },
        {
          "@type": [
            "Diameter",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "Diameter",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 26.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#MilliMetre"
        },
        {
          "@type": [
            "Height",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "Height",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 65.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#MilliMetre"
        },
        {
          "@type": [
            "MaximumPulseChargingCurrent",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MaximumPulseChargingCurrent",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 10.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Ampere"
        },
        {
          "@type": [
            "MaximumContinuousChargingCurrent",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MaximumContinuousChargingCurrent",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 2.5
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Ampere"
        },
        {
          "@type": [
            "MaximumContinuousDischargingCurrent",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MaximumContinuousDischargingCurrent",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 50.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Ampere"
        },
        {
          "@type": [
            "MinimumDischargingTemperature",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MinimumDischargingTemperature",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": -30
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc"
        },
        {
          "@type": [
            "MaximumDischargingTemperature",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MaximumDischargingTemperature",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 55
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc"
        },
        {
          "@type": [
            "MinimumStorageTemperature",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MinimumStorageTemperature",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": -40
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc"
        },
        {
          "@type": [
            "MaximumStorageTemperature",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MaximumStorageTemperature",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 60
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc"
        },
        {
          "@type": [
            "CycleLife",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "CycleLife",
          "schema:value": ">1000",
          "hasMeasurementUnit": "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"
        }
      ],
      "hasPositiveElectrode": {
        "@type": "LithiumIronPhosphateElectrode"
      },
      "dcterms:source": {
        "@type": "prov:Entity",
        "dcterms:type": "datasheet",
        "prov:generatedAtTime": "2026-01-28T07:33:04+00:00"
      }
    }
  },
  {
    "slug": "test",
    "label": "Test — baseline cycling on a tracked cell",
    "recordType": "test",
    "sourceFile": "examples/test/test-5p7v-2n8k-4m3t-6q9r.json",
    "highlight": "The test points at the physical cell it ran on (prov:used), so every number stays attached to its subject.",
    "record": {
      "schema_version": "0.2.0",
      "test": {
        "id": "https://w3id.org/battinfo/test/5p7v-2n8k-4m3t-6q9r",
        "short_id": "5p7v2n",
        "identifier": "test:5p7v-2n8k-4m3t-6q9r",
        "cell_id": "https://w3id.org/battinfo/cell/3m6k-9t2p-7x4h-9nq8",
        "name": "A123 ANR26650M1-B baseline cycling",
        "description": "Galvanostatic cycling test for one physical cell instance.",
        "kind": "cycling",
        "status": "completed",
        "protocol_name": "0.5C charge/discharge baseline cycling",
        "started_at": 1771718400,
        "ended_at": 1771804800,
        "dataset_ids": [
          "https://w3id.org/battinfo/dataset/1f8r-6v2k-9p4m-3t7x"
        ]
      },
      "provenance": {
        "source_type": "measurement",
        "source_url": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x",
        "source_file": "test-5p7v-2n8k-4m3t-6q9r.json",
        "retrieved_at": 1771804800,
        "workflow_version": "0.2.0",
        "citation": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      },
      "notes": [
        "Explicit test record linking the physical cell instance to its cycling dataset."
      ]
    },
    "jsonld": {
      "@context": "https://w3id.org/battinfo/context/records/v1.json",
      "@type": [
        "BatteryTest",
        "schema:Action",
        "prov:Activity"
      ],
      "@id": "https://w3id.org/battinfo/test/5p7v-2n8k-4m3t-6q9r",
      "schema:name": "A123 ANR26650M1-B baseline cycling",
      "schema:additionalType": "cycling",
      "schema:measurementTechnique": "0.5C charge/discharge baseline cycling",
      "schema:actionStatus": "completed",
      "hasTestObject": {
        "@id": "https://w3id.org/battinfo/cell/3m6k-9t2p-7x4h-9nq8"
      },
      "schema:result": [
        {
          "@id": "https://w3id.org/battinfo/dataset/1f8r-6v2k-9p4m-3t7x"
        }
      ],
      "dcterms:source": {
        "@type": "prov:Entity",
        "dcterms:type": "measurement",
        "prov:hadPrimarySource": {
          "@id": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
        },
        "prov:generatedAtTime": "2026-02-23T00:00:00+00:00",
        "dcterms:bibliographicCitation": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      }
    }
  },
  {
    "slug": "dataset",
    "label": "Dataset — the files a test produced",
    "recordType": "dataset",
    "sourceFile": "examples/dataset/dataset-1f8r-6v2k-9p4m-3t7x.json",
    "highlight": "Datasets are DCAT: catalogable, with distributions and checksums — the shape data portals already understand.",
    "record": {
      "schema_version": "0.2.0",
      "dataset": {
        "id": "https://w3id.org/battinfo/dataset/1f8r-6v2k-9p4m-3t7x",
        "short_id": "1f8r6v",
        "identifier": "doi:10.5281/zenodo.1234567",
        "name": "Cell cycling run for BattINFO cell 3m6k9t",
        "description": "Raw cycling and metadata export for one physical cell.",
        "access_url": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x",
        "same_as": [
          "https://doi.org/10.5281/zenodo.1234567"
        ],
        "license": "https://creativecommons.org/licenses/by/4.0/",
        "version": "1.0.0",
        "keywords": [
          "battery cycling",
          "time series",
          "lithium-ion"
        ],
        "creators": [
          {
            "type": "Organization",
            "name": "BattINFO Maintainers"
          }
        ],
        "publisher": {
          "type": "Organization",
          "name": "BattINFO"
        },
        "citations": [
          {
            "kind": "dataset",
            "url": "https://doi.org/10.5281/zenodo.1234567",
            "doi": "10.5281/zenodo.1234567",
            "citation_key": "example_dataset_2026"
          }
        ],
        "about": [
          "https://w3id.org/battinfo/cell/3m6k-9t2p-7x4h-9nq8",
          "https://w3id.org/battinfo/test/5p7v-2n8k-4m3t-6q9r"
        ],
        "measurement_techniques": [
          "cycling"
        ],
        "measurement_methods": [
          "galvanostatic cycling"
        ],
        "variable_measured": [
          {
            "name": "voltage",
            "unit_text": "V"
          },
          {
            "name": "current",
            "unit_text": "A"
          },
          {
            "name": "capacity",
            "unit_text": "Ah"
          }
        ],
        "is_accessible_for_free": true,
        "in_language": "en",
        "created_at": 1771718400,
        "modified_at": 1771718400,
        "published_at": 1771718400,
        "distributions": [
          {
            "type": "DataDownload",
            "name": "Raw cycling HDF5 archive",
            "content_url": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x/raw.h5",
            "encoding_format": "application/x-hdf5",
            "checksum": {
              "algorithm": "sha256",
              "value": "8fbf34bd0f8a0caef6f5ce6cc1f8e6a2d8f0123982fc624d6f7f3f7e27b95a89"
            },
            "access_level": "open"
          }
        ]
      },
      "provenance": {
        "source_type": "measurement",
        "source_name": "Example Lab Data Portal",
        "source_url": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x",
        "source_file": "dataset-1f8r-6v2k-9p4m-3t7x.json",
        "source_dataset_key": "example-0001",
        "ingest_status": "ready",
        "quality_flags": [],
        "retrieved_at": 1771718400,
        "curated_by": "BattINFO Maintainers",
        "workflow_version": "0.2.0",
        "citation": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      },
      "notes": [
        "Schema.org-first dataset record with BattINFO battery extensions.",
        "Used as a canonical example for dataset ingestion and linking workflows."
      ]
    },
    "jsonld": {
      "@context": "https://w3id.org/battinfo/context/records/v1.json",
      "@type": "http://www.w3.org/ns/dcat#Dataset",
      "@id": "https://w3id.org/battinfo/dataset/1f8r-6v2k-9p4m-3t7x",
      "dcterms:title": "Cell cycling run for BattINFO cell 3m6k9t",
      "dcterms:description": "Raw cycling and metadata export for one physical cell.",
      "schema:description": "Raw cycling and metadata export for one physical cell.",
      "dcterms:license": {
        "@id": "https://creativecommons.org/licenses/by/4.0/"
      },
      "dcat:accessURL": {
        "@id": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      },
      "dcat:keyword": [
        "battery cycling",
        "time series",
        "lithium-ion"
      ],
      "schema:keywords": [
        "battery cycling",
        "time series",
        "lithium-ion"
      ],
      "dcterms:created": "2026-02-22T00:00:00Z",
      "dcterms:modified": "2026-02-22T00:00:00Z",
      "dcterms:issued": "2026-02-22T00:00:00Z",
      "schema:datePublished": "2026-02-22T00:00:00Z",
      "schema:measurementTechnique": [
        "cycling"
      ],
      "schema:measurementMethod": [
        "galvanostatic cycling"
      ],
      "schema:variableMeasured": [
        {
          "@type": "schema:PropertyValue",
          "schema:name": "voltage",
          "schema:unitText": "V"
        },
        {
          "@type": "schema:PropertyValue",
          "schema:name": "current",
          "schema:unitText": "A"
        },
        {
          "@type": "schema:PropertyValue",
          "schema:name": "capacity",
          "schema:unitText": "Ah"
        }
      ],
      "schema:citation": [
        {
          "@type": "schema:CreativeWork",
          "@id": "https://doi.org/10.5281/zenodo.1234567",
          "schema:url": "https://doi.org/10.5281/zenodo.1234567",
          "schema:additionalType": "dataset",
          "bibo:doi": "10.5281/zenodo.1234567",
          "schema:identifier": "example_dataset_2026"
        }
      ],
      "dcterms:subject": [
        {
          "@id": "https://w3id.org/battinfo/cell/3m6k-9t2p-7x4h-9nq8"
        },
        {
          "@id": "https://w3id.org/battinfo/test/5p7v-2n8k-4m3t-6q9r"
        }
      ],
      "dcat:distribution": [
        {
          "@type": "dcat:Distribution",
          "schema:name": "Raw cycling HDF5 archive",
          "dcat:downloadURL": {
            "@id": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x/raw.h5"
          },
          "dcat:mediaType": "application/x-hdf5",
          "spdx:checksum": {
            "@type": "spdx:Checksum",
            "spdx:checksumAlgorithm": {
              "@id": "spdx:checksumAlgorithm_sha256"
            },
            "spdx:checksumValue": "8fbf34bd0f8a0caef6f5ce6cc1f8e6a2d8f0123982fc624d6f7f3f7e27b95a89"
          }
        }
      ],
      "dcterms:source": {
        "@type": "prov:Entity",
        "dcterms:type": "measurement",
        "prov:hadPrimarySource": {
          "@id": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
        },
        "prov:generatedAtTime": "2026-02-22T00:00:00+00:00",
        "dcterms:bibliographicCitation": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      }
    }
  }
];
