// GENERATED by scripts/gen_web_jsonld.py — do not edit.
// Each pair is the canonical example record and the JSON-LD the REAL
// Python transform emits for it (battinfo.record_to_jsonld).
// tests/test_web_generated.py fails when this file drifts from the library.

export const jsonldGallery: {
  slug: string;
  label: string;
  recordType: string;
  sourceFile: string;
  highlight: string;
  record: Record<string, unknown>;
  jsonld: Record<string, unknown>;
}[] = [
  {
    "slug": "cell-spec",
    "label": "Cell spec — A123 ANR26650M1-B",
    "recordType": "cell-spec",
    "sourceFile": "examples/cell-spec/A123__ANR26650M1-B.json",
    "highlight": "EMMO @type stacking: one cylindrical LFP cell is simultaneously a BatteryCell, a CylindricalBattery, and a LithiumIronPhosphateBattery — no manual annotation.",
    "record": {
      "schema_version": "0.1.0",
      "cell_spec": {
        "id": "https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5",
        "short_id": "7d9k2m",
        "identifier": "cell-spec:7d9k-2m4p-8t3x-6nq5",
        "name": "A123 ANR26650M1-B",
        "model": "ANR26650M1-B",
        "manufacturer": {
          "type": "Organization",
          "name": "A123",
          "id": "https://w3id.org/battinfo/organization/9k3e-absq-8131-vyjd"
        },
        "brand": {
          "type": "Brand",
          "name": "A123"
        },
        "category": "battery cell",
        "cell_format": "cylindrical",
        "chemistry": "Li-ion",
        "positive_electrode_basis": "LFP",
        "negative_electrode_basis": "unknown",
        "size_code": "R26650",
        "iec_code": "IFpR26650",
        "country_of_origin": "United States",
        "year": 2012
      },
      "properties": {
        "nominal_capacity": {
          "value": 2.5,
          "unit": "Ah",
          "raw": {
            "text": "Cell Capacity (nominal/minimum) (0.5C Rate) 2.5/2.4 Ah",
            "page": 1,
            "confidence": 0.8
          }
        },
        "minimum_capacity": {
          "value": 2.4,
          "unit": "Ah",
          "raw": {
            "text": "Cell Capacity (nominal/minimum) (0.5C Rate) 2.5/2.4 Ah",
            "page": 1,
            "confidence": 0.8
          }
        },
        "nominal_voltage": {
          "value": 3.3,
          "unit": "V",
          "raw": {
            "text": "Voltage (nominal) 3.3V",
            "page": 1,
            "confidence": 0.8
          }
        },
        "internal_resistance": {
          "value": 6.0,
          "unit": "mΩ",
          "raw": {
            "text": "Internal Impedance (1kHz AC typical) 6mΩ",
            "page": 1,
            "confidence": 0.8
          }
        },
        "mass": {
          "value": 76.0,
          "unit": "g",
          "raw": {
            "text": "Cell Weight 76g",
            "page": 1,
            "confidence": 0.8
          }
        },
        "diameter": {
          "value": 26.0,
          "unit": "mm",
          "raw": {
            "text": "Cell Dimensions 26 x 65 mm",
            "page": 1,
            "confidence": 0.8
          }
        },
        "height": {
          "value": 65.0,
          "unit": "mm",
          "raw": {
            "text": "Cell Dimensions 26 x 65 mm",
            "page": 1,
            "confidence": 0.8
          }
        },
        "pulse_charging_current": {
          "value": 10.0,
          "unit": "A",
          "raw": {
            "text": "Recommended Fast Charge Method to 80% SOC 10A to 3.6V CC, 12 min",
            "page": 1,
            "confidence": 0.8
          }
        },
        "nominal_continuous_charging_current": {
          "value": 2.5,
          "unit": "A",
          "raw": {
            "text": "Recommended Standard Charge Method 2.5A to 3.6V CCCV, 60 min",
            "page": 1,
            "confidence": 0.8
          }
        },
        "maximum_continuous_charging_current": {
          "value": 2.5,
          "unit": "A",
          "raw": {
            "text": "Recommended Standard Charge Method 2.5A to 3.6V CCCV, 60 min",
            "page": 1,
            "confidence": 0.8
          }
        },
        "maximum_continuous_discharging_current": {
          "value": 50.0,
          "unit": "A",
          "raw": {
            "text": "Maximum Continuous Discharge 50A",
            "page": 1,
            "confidence": 0.8
          }
        },
        "minimum_discharging_temperature": {
          "value": -30,
          "unit": "°C",
          "raw": {
            "text": "Operating Temperature -30°C to 55°C",
            "page": 1,
            "confidence": 0.8
          }
        },
        "maximum_discharging_temperature": {
          "value": 55,
          "unit": "°C",
          "raw": {
            "text": "Operating Temperature -30°C to 55°C",
            "page": 1,
            "confidence": 0.8
          }
        },
        "minimum_storage_temperature": {
          "value": -40,
          "unit": "°C",
          "raw": {
            "text": "Storage Temperature -40°C to 60°C",
            "page": 1,
            "confidence": 0.8
          }
        },
        "maximum_storage_temperature": {
          "value": 60,
          "unit": "°C",
          "raw": {
            "text": "Storage Temperature -40°C to 60°C",
            "page": 1,
            "confidence": 0.8
          }
        },
        "cycle_life": {
          "value_text": ">1000",
          "unit": "count",
          "raw": {
            "text": "Cycle Life at 20A Discharge, 100% DOD >1,000 cycles",
            "page": 1,
            "confidence": 0.7
          }
        }
      },
      "provenance": {
        "source_type": "datasheet",
        "source_file": "A123__ANR26650M1-B.pdf",
        "source_url": null,
        "file_hash": "b5069f48e121de3a1308af66215e7a97a1c8c6a87227da089c83e352f1ddf35e",
        "retrieved_at": 1769585584
      }
    },
    "jsonld": {
      "@context": {
        "@version": 1.1,
        "battery": "https://w3id.org/emmo/domain/battery#",
        "electrochemistry": "https://w3id.org/emmo/domain/electrochemistry#",
        "emmo": "https://w3id.org/emmo#",
        "battinfo": "https://w3id.org/battinfo/",
        "schema": "https://schema.org/",
        "dcterms": "http://purl.org/dc/terms/",
        "prov": "http://www.w3.org/ns/prov#",
        "dcat": "http://www.w3.org/ns/dcat#",
        "dqv": "http://www.w3.org/ns/dqv#",
        "oa": "http://www.w3.org/ns/oa#",
        "earl": "http://www.w3.org/ns/earl#",
        "spdx": "http://spdx.org/rdf/terms#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "BatteryCell": "battery:battery_68ed592a_7924_45d0_a108_94d6275d57f0",
        "BatteryCellSpecification": "battery:battery_1cfbba6c_8824_4932_a23e_2141483acef7",
        "CylindricalBattery": "battery:battery_ac604ecd_cc60_4b98_b57c_74cd5d3ccd40",
        "PrismaticBattery": "battery:battery_86c9ca80_de6f_417f_afdc_a7e52fa6322d",
        "PouchCell": "battery:battery_392b3f47_d62a_4bd4_a819_b58b09b8843a",
        "CoinCell": "battery:battery_b7fdab58_6e91_4c84_b097_b06eff86a124",
        "LithiumIonBattery": "battery:battery_96addc62_ea04_449a_8237_4cd541dd8e5f",
        "LithiumMetalBattery": "battery:battery_ada13509_4eed_4e40_a7b1_4cc488144154",
        "SodiumIonBattery": "battery:battery_42329a95_03fe_4ec1_83cb_b7e8ed52f68a",
        "AlkalineZincManganeseDioxideBattery": "battery:battery_b572826a_b4e4_4986_b57d_f7b945061f8b",
        "AlkalineCell": "battery:battery_50b911f7_c903_4700_9764_c308d8a95470",
        "PrimaryBattery": "battery:battery_3b0b0d6e_8b0e_4491_885e_8421d3eb3b69",
        "SecondaryBattery": "battery:battery_efc38420_ecbb_42e4_bb3f_208e7c417098",
        "BatteryTest": "battery:battery_dca7729a_421a_4921_90cf_9692bb9eb081",
        "name": "schema:name",
        "model": "schema:model",
        "manufacturer": "schema:manufacturer",
        "hasProperty": {
          "@id": "emmo:EMMO_e1097637_70d2_4895_973f_2396f04fa204",
          "@type": "@id"
        },
        "hasNumericalPart": {
          "@id": "emmo:EMMO_8ef3cd6d_ae58_4a8d_9fc0_ad8f49015cd0",
          "@type": "@id"
        },
        "hasNumberValue": "emmo:EMMO_faf79f53_749d_40b2_807c_d34244c192f4",
        "hasNumericalValue": "emmo:EMMO_faf79f53_749d_40b2_807c_d34244c192f4",
        "hasMeasurementUnit": {
          "@id": "emmo:EMMO_bed1d005_b04e_4a90_94cf_02bc678a8569",
          "@type": "@id"
        },
        "isDescriptionFor": {
          "@id": "emmo:EMMO_f702bad4_fc77_41f0_a26d_79f6444fd4f3",
          "@type": "@id"
        },
        "hasDescription": {
          "@id": "emmo:EMMO_c58c799e_cc6c_4310_a3f1_78da70705b2a",
          "@type": "@id"
        },
        "hasTestObject": {
          "@id": "battery:battery_da3b3f28_aaad_4d67_b674_df47e109fb8b",
          "@type": "@id"
        },
        "hasTestEquipment": {
          "@id": "battery:battery_df4ff8f1_2cf2_444a_9498_23f533bd295c",
          "@type": "@id"
        },
        "hasOutput": {
          "@id": "emmo:EMMO_c4bace1d_4db0_4cd3_87e9_18122bae2840",
          "@type": "@id"
        },
        "id": "schema:productID",
        "nominal_capacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "minimum_capacity": "electrochemistry:electrochemistry_d3c0078e_c1d3_461e_873d_e5c3adf441c5",
        "rated_capacity": "electrochemistry:electrochemistry_9b3b4668_0795_4a35_9965_2af383497a26",
        "typical_capacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "nominal_voltage": "electrochemistry:electrochemistry_639b844a_e801_436b_985d_28926129ead6",
        "charging_voltage": "electrochemistry:electrochemistry_79a9e1be_35b0_4c3c_8087_b5f967ca0e87",
        "discharging_cutoff_voltage": "electrochemistry:electrochemistry_534dd59c_904c_45d9_8550_ae9d2eb6bbc9",
        "charging_cutoff_voltage": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "upper_voltage_limit": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "maximum_continuous_charging_current": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "nominal_continuous_charging_current": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "maximum_pulse_charging_current": "electrochemistry:electrochemistry_1b2a7137_64d4_483a_8437_dcb3bedcb6da",
        "maximum_continuous_discharging_current": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "nominal_continuous_discharging_current": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "maximum_pulse_discharging_current": "electrochemistry:electrochemistry_3e54f9e3_a31d_4821_9bfb_ef953a42c35b",
        "nominal_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "typical_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "rated_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "certified_usable_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "power_capability": "battinfo:powerCapability",
        "maximum_power": "battinfo:maximumPower",
        "specific_energy": "emmo:EMMO_e218c625_6a39_47a9_8d08_a2ef41c152a9",
        "energy_density": "electrochemistry:electrochemistry_4aa1b96e_44a0_4b1a_a0ac_723d0223d80b",
        "specific_power": "battinfo:specificPower",
        "power_density": "battinfo:powerDensity",
        "power_energy_ratio": "battinfo:powerEnergyRatio",
        "internal_resistance": "electrochemistry:electrochemistry_9bf40017_3f58_4030_ada7_cb37a3dfda2d",
        "dc_internal_resistance": "electrochemistry:electrochemistry_7b3eb826_b968_493a_8396_cc3a5f09ecb3",
        "ac_internal_resistance": "electrochemistry:electrochemistry_964cd426_f3cf_4a52_8c5d_0490cf48edb5",
        "impedance": "emmo:EMMO_79a02de5_b884_4eab_bc18_f67997d597a2",
        "round_trip_energy_efficiency": "battinfo:roundTripEnergyEfficiency",
        "round_trip_energy_efficiency_50pct": "battinfo:roundTripEnergyEfficiency50Pct",
        "initial_coulombic_efficiency": "electrochemistry:electrochemistry_469b9516_a96d_4aa2_b8e5_05ae982e2084",
        "mass": "emmo:EMMO_ed4af7ae_63a2_497e_bb88_2309619ea405",
        "diameter": "emmo:EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6",
        "height": "emmo:EMMO_08bcf1d6_e719_46c8_bb21_24bc9bf34dba",
        "width": "emmo:EMMO_e4de48b1_dabb_4490_ac2b_040f926c64f0",
        "length": "emmo:EMMO_cd2cd0de_e0cc_4ef1_b27e_2e88db027bac",
        "thickness": "emmo:EMMO_43003c86_9d15_433b_9789_ee2940920656",
        "volume": "emmo:EMMO_f1a51559_aa3d_43a0_9327_918039f0dfed",
        "maximum_charging_temperature": "electrochemistry:electrochemistry_4a354510_4dc2_4803_8845_f4024a1a7260",
        "minimum_charging_temperature": "electrochemistry:electrochemistry_b90b1ad7_b9a8_44df_ad45_bfd25aac2e49",
        "maximum_discharging_temperature": "electrochemistry:electrochemistry_de612af2_a029_4a02_8090_4a75ab13271d",
        "minimum_discharging_temperature": "electrochemistry:electrochemistry_2a1de79f_e927_45a2_9619_3799a0d61e9b",
        "maximum_storage_temperature": "electrochemistry:electrochemistry_0ea4d188_9701_4699_a5ca_812a98a9afa7",
        "minimum_storage_temperature": "electrochemistry:electrochemistry_0ddfd57a_d338_4690_be45_b26884ed6302",
        "operating_temperature_min": "battinfo:operatingTemperatureMin",
        "operating_temperature_max": "battinfo:operatingTemperatureMax",
        "cycle_life": "electrochemistry:electrochemistry_ae782b14_88ce_4cdd_9418_12aca00be937",
        "cycle_life_c_rate": "battinfo:cycleLifeCRate",
        "calendar_life": "electrochemistry:electrochemistry_743c71a3_b80c_42e3_92fa_13a67b8167df",
        "capacity_fade": "battinfo:capacityFade",
        "capacity_threshold_exhaustion": "battinfo:capacityThresholdExhaustion",
        "charging_time": "battinfo:chargingTime",
        "self_discharge_rate": "electrochemistry:electrochemistry_c3e97d58_1854_4c23_bb42_d2972172865e",
        "state_of_health": "electrochemistry:electrochemistry_a7a4614f_2426_46f3_8475_cda4a9fabfce",
        "source_type": "battinfo:sourceType",
        "source_url": "battinfo:sourceURL",
        "source_file": "battinfo:sourceFile",
        "citation": "dcterms:bibliographicCitation",
        "citation_doi": "battinfo:citationDOI",
        "retrieved_at": "battinfo:retrievedAt",
        "workflow_version": "battinfo:workflowVersion",
        "curated_by": "dcterms:contributor",
        "protocol_name": "schema:name",
        "protocol_url": "schema:url",
        "V": "emmo:Volt",
        "mV": "emmo:MilliVolt",
        "kV": "emmo:KiloVolt",
        "Ah": "emmo:AmpereHour",
        "mAh": "emmo:MilliAmpereHour",
        "A": "emmo:Ampere",
        "mA": "emmo:MilliAmpere",
        "W": "emmo:Watt",
        "kW": "emmo:KiloWatt",
        "Wh": "emmo:WattHour",
        "kWh": "emmo:KiloWattHour",
        "MWh": "emmo:MegaWattHour",
        "Ohm": "emmo:Ohm",
        "mOhm": "emmo:MilliOhm",
        "mohm": "emmo:MilliOhm",
        "degC": "emmo:EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc",
        "K": "emmo:Kelvin",
        "g": "emmo:Gram",
        "kg": "emmo:Kilogram",
        "mg": "emmo:MilliGram",
        "mm": "emmo:MilliMetre",
        "cm": "emmo:CentiMetre",
        "m": "emmo:Metre",
        "L": "emmo:Litre",
        "mL": "emmo:MilliLitre",
        "cm3": "emmo:CubicCentiMetre",
        "h": "emmo:Hour",
        "min": "emmo:Minute",
        "s": "emmo:Second",
        "1": "emmo:EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
        "%": "emmo:Percent",
        "license": {
          "@id": "dcterms:license",
          "@type": "@id"
        },
        "created_at": {
          "@id": "dcterms:created",
          "@type": "xsd:dateTime"
        },
        "modified_at": {
          "@id": "dcterms:modified",
          "@type": "xsd:dateTime"
        }
      },
      "@id": "https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5",
      "@type": [
        "https://w3id.org/emmo/domain/battery#battery_68ed592a_7924_45d0_a108_94d6275d57f0",
        "https://w3id.org/emmo/domain/battery#battery_ac604ecd_cc60_4b98_b57c_74cd5d3ccd40",
        "https://w3id.org/emmo/domain/battery#battery_96addc62_ea04_449a_8237_4cd541dd8e5f"
      ],
      "schema:name": "A123 ANR26650M1-B",
      "schema:model": "ANR26650M1-B",
      "schema:manufacturer": {
        "@type": "schema:Organization",
        "schema:name": "A123"
      },
      "battinfo:cell_format": "cylindrical",
      "battinfo:chemistry": "Li-ion",
      "battinfo:positive_electrode_basis": "LFP",
      "battinfo:negative_electrode_basis": "unknown",
      "battinfo:size_code": "R26650",
      "battinfo:iec_code": "IFpR26650",
      "battinfo:country_of_origin": "United States",
      "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100": {
        "hasNumericalPart": {
          "hasNumberValue": 2.5
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#AmpereHour"
        }
      },
      "electrochemistry:electrochemistry_d3c0078e_c1d3_461e_873d_e5c3adf441c5": {
        "hasNumericalPart": {
          "hasNumberValue": 2.4
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#AmpereHour"
        }
      },
      "electrochemistry:electrochemistry_639b844a_e801_436b_985d_28926129ead6": {
        "hasNumericalPart": {
          "hasNumberValue": 3.3
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#Volt"
        }
      },
      "electrochemistry:electrochemistry_9bf40017_3f58_4030_ada7_cb37a3dfda2d": {
        "hasNumericalPart": {
          "hasNumberValue": 6.0
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#MilliOhm"
        }
      },
      "emmo:EMMO_ed4af7ae_63a2_497e_bb88_2309619ea405": {
        "hasNumericalPart": {
          "hasNumberValue": 76.0
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#Gram"
        }
      },
      "emmo:EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6": {
        "hasNumericalPart": {
          "hasNumberValue": 26.0
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#MilliMetre"
        }
      },
      "emmo:EMMO_08bcf1d6_e719_46c8_bb21_24bc9bf34dba": {
        "hasNumericalPart": {
          "hasNumberValue": 65.0
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#MilliMetre"
        }
      },
      "electrochemistry:electrochemistry_1b2a7137_64d4_483a_8437_dcb3bedcb6da": {
        "hasNumericalPart": {
          "hasNumberValue": 10.0
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#Ampere"
        }
      },
      "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78": {
        "hasNumericalPart": {
          "hasNumberValue": 2.5
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#Ampere"
        }
      },
      "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5": {
        "hasNumericalPart": {
          "hasNumberValue": 50.0
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#Ampere"
        }
      },
      "electrochemistry:electrochemistry_2a1de79f_e927_45a2_9619_3799a0d61e9b": {
        "hasNumericalPart": {
          "hasNumberValue": -30
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#DegreeCelsius"
        }
      },
      "electrochemistry:electrochemistry_de612af2_a029_4a02_8090_4a75ab13271d": {
        "hasNumericalPart": {
          "hasNumberValue": 55
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#DegreeCelsius"
        }
      },
      "electrochemistry:electrochemistry_0ddfd57a_d338_4690_be45_b26884ed6302": {
        "hasNumericalPart": {
          "hasNumberValue": -40
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#DegreeCelsius"
        }
      },
      "electrochemistry:electrochemistry_0ea4d188_9701_4699_a5ca_812a98a9afa7": {
        "hasNumericalPart": {
          "hasNumberValue": 60
        },
        "hasMeasurementUnit": {
          "@id": "https://w3id.org/emmo#DegreeCelsius"
        }
      },
      "battinfo:provenance": {
        "battinfo:sourceType": "datasheet",
        "battinfo:sourceFile": "A123__ANR26650M1-B.pdf"
      }
    }
  },
  {
    "slug": "test",
    "label": "Test — baseline cycling on a tracked cell",
    "recordType": "test",
    "sourceFile": "examples/test/test-5p7v-2n8k-4m3t-6q9r.json",
    "highlight": "The test points at the physical cell it ran on (prov:used), so every number stays attached to its subject.",
    "record": {
      "schema_version": "0.1.0",
      "test": {
        "id": "https://w3id.org/battinfo/test/5p7v-2n8k-4m3t-6q9r",
        "short_id": "5p7v2n",
        "identifier": "test:5p7v-2n8k-4m3t-6q9r",
        "cell_id": "https://w3id.org/battinfo/cell/3m6k-9t2p-7x4h-9nq8",
        "name": "A123 ANR26650M1-B baseline cycling",
        "description": "Galvanostatic cycling test for one physical cell instance.",
        "kind": "cycling",
        "status": "completed",
        "protocol_name": "0.5C charge/discharge baseline cycling",
        "started_at": 1771718400,
        "ended_at": 1771804800,
        "dataset_ids": [
          "https://w3id.org/battinfo/dataset/1f8r-6v2k-9p4m-3t7x"
        ]
      },
      "provenance": {
        "source_type": "measurement",
        "source_url": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x",
        "source_file": "test-5p7v-2n8k-4m3t-6q9r.json",
        "retrieved_at": 1771804800,
        "workflow_version": "0.2.0",
        "citation": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      },
      "notes": [
        "Explicit test record linking the physical cell instance to its cycling dataset."
      ]
    },
    "jsonld": {
      "@context": {
        "@version": 1.1,
        "battery": "https://w3id.org/emmo/domain/battery#",
        "electrochemistry": "https://w3id.org/emmo/domain/electrochemistry#",
        "emmo": "https://w3id.org/emmo#",
        "battinfo": "https://w3id.org/battinfo/",
        "schema": "https://schema.org/",
        "dcterms": "http://purl.org/dc/terms/",
        "prov": "http://www.w3.org/ns/prov#",
        "dcat": "http://www.w3.org/ns/dcat#",
        "dqv": "http://www.w3.org/ns/dqv#",
        "oa": "http://www.w3.org/ns/oa#",
        "earl": "http://www.w3.org/ns/earl#",
        "spdx": "http://spdx.org/rdf/terms#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "BatteryCell": "battery:battery_68ed592a_7924_45d0_a108_94d6275d57f0",
        "BatteryCellSpecification": "battery:battery_1cfbba6c_8824_4932_a23e_2141483acef7",
        "CylindricalBattery": "battery:battery_ac604ecd_cc60_4b98_b57c_74cd5d3ccd40",
        "PrismaticBattery": "battery:battery_86c9ca80_de6f_417f_afdc_a7e52fa6322d",
        "PouchCell": "battery:battery_392b3f47_d62a_4bd4_a819_b58b09b8843a",
        "CoinCell": "battery:battery_b7fdab58_6e91_4c84_b097_b06eff86a124",
        "LithiumIonBattery": "battery:battery_96addc62_ea04_449a_8237_4cd541dd8e5f",
        "LithiumMetalBattery": "battery:battery_ada13509_4eed_4e40_a7b1_4cc488144154",
        "SodiumIonBattery": "battery:battery_42329a95_03fe_4ec1_83cb_b7e8ed52f68a",
        "AlkalineZincManganeseDioxideBattery": "battery:battery_b572826a_b4e4_4986_b57d_f7b945061f8b",
        "AlkalineCell": "battery:battery_50b911f7_c903_4700_9764_c308d8a95470",
        "PrimaryBattery": "battery:battery_3b0b0d6e_8b0e_4491_885e_8421d3eb3b69",
        "SecondaryBattery": "battery:battery_efc38420_ecbb_42e4_bb3f_208e7c417098",
        "BatteryTest": "battery:battery_dca7729a_421a_4921_90cf_9692bb9eb081",
        "name": "schema:name",
        "model": "schema:model",
        "manufacturer": "schema:manufacturer",
        "hasProperty": {
          "@id": "emmo:EMMO_e1097637_70d2_4895_973f_2396f04fa204",
          "@type": "@id"
        },
        "hasNumericalPart": {
          "@id": "emmo:EMMO_8ef3cd6d_ae58_4a8d_9fc0_ad8f49015cd0",
          "@type": "@id"
        },
        "hasNumberValue": "emmo:EMMO_faf79f53_749d_40b2_807c_d34244c192f4",
        "hasNumericalValue": "emmo:EMMO_faf79f53_749d_40b2_807c_d34244c192f4",
        "hasMeasurementUnit": {
          "@id": "emmo:EMMO_bed1d005_b04e_4a90_94cf_02bc678a8569",
          "@type": "@id"
        },
        "isDescriptionFor": {
          "@id": "emmo:EMMO_f702bad4_fc77_41f0_a26d_79f6444fd4f3",
          "@type": "@id"
        },
        "hasDescription": {
          "@id": "emmo:EMMO_c58c799e_cc6c_4310_a3f1_78da70705b2a",
          "@type": "@id"
        },
        "hasTestObject": {
          "@id": "battery:battery_da3b3f28_aaad_4d67_b674_df47e109fb8b",
          "@type": "@id"
        },
        "hasTestEquipment": {
          "@id": "battery:battery_df4ff8f1_2cf2_444a_9498_23f533bd295c",
          "@type": "@id"
        },
        "hasOutput": {
          "@id": "emmo:EMMO_c4bace1d_4db0_4cd3_87e9_18122bae2840",
          "@type": "@id"
        },
        "id": "schema:productID",
        "nominal_capacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "minimum_capacity": "electrochemistry:electrochemistry_d3c0078e_c1d3_461e_873d_e5c3adf441c5",
        "rated_capacity": "electrochemistry:electrochemistry_9b3b4668_0795_4a35_9965_2af383497a26",
        "typical_capacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "nominal_voltage": "electrochemistry:electrochemistry_639b844a_e801_436b_985d_28926129ead6",
        "charging_voltage": "electrochemistry:electrochemistry_79a9e1be_35b0_4c3c_8087_b5f967ca0e87",
        "discharging_cutoff_voltage": "electrochemistry:electrochemistry_534dd59c_904c_45d9_8550_ae9d2eb6bbc9",
        "charging_cutoff_voltage": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "upper_voltage_limit": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "maximum_continuous_charging_current": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "nominal_continuous_charging_current": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "maximum_pulse_charging_current": "electrochemistry:electrochemistry_1b2a7137_64d4_483a_8437_dcb3bedcb6da",
        "maximum_continuous_discharging_current": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "nominal_continuous_discharging_current": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "maximum_pulse_discharging_current": "electrochemistry:electrochemistry_3e54f9e3_a31d_4821_9bfb_ef953a42c35b",
        "nominal_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "typical_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "rated_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "certified_usable_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "power_capability": "battinfo:powerCapability",
        "maximum_power": "battinfo:maximumPower",
        "specific_energy": "emmo:EMMO_e218c625_6a39_47a9_8d08_a2ef41c152a9",
        "energy_density": "electrochemistry:electrochemistry_4aa1b96e_44a0_4b1a_a0ac_723d0223d80b",
        "specific_power": "battinfo:specificPower",
        "power_density": "battinfo:powerDensity",
        "power_energy_ratio": "battinfo:powerEnergyRatio",
        "internal_resistance": "electrochemistry:electrochemistry_9bf40017_3f58_4030_ada7_cb37a3dfda2d",
        "dc_internal_resistance": "electrochemistry:electrochemistry_7b3eb826_b968_493a_8396_cc3a5f09ecb3",
        "ac_internal_resistance": "electrochemistry:electrochemistry_964cd426_f3cf_4a52_8c5d_0490cf48edb5",
        "impedance": "emmo:EMMO_79a02de5_b884_4eab_bc18_f67997d597a2",
        "round_trip_energy_efficiency": "battinfo:roundTripEnergyEfficiency",
        "round_trip_energy_efficiency_50pct": "battinfo:roundTripEnergyEfficiency50Pct",
        "initial_coulombic_efficiency": "electrochemistry:electrochemistry_469b9516_a96d_4aa2_b8e5_05ae982e2084",
        "mass": "emmo:EMMO_ed4af7ae_63a2_497e_bb88_2309619ea405",
        "diameter": "emmo:EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6",
        "height": "emmo:EMMO_08bcf1d6_e719_46c8_bb21_24bc9bf34dba",
        "width": "emmo:EMMO_e4de48b1_dabb_4490_ac2b_040f926c64f0",
        "length": "emmo:EMMO_cd2cd0de_e0cc_4ef1_b27e_2e88db027bac",
        "thickness": "emmo:EMMO_43003c86_9d15_433b_9789_ee2940920656",
        "volume": "emmo:EMMO_f1a51559_aa3d_43a0_9327_918039f0dfed",
        "maximum_charging_temperature": "electrochemistry:electrochemistry_4a354510_4dc2_4803_8845_f4024a1a7260",
        "minimum_charging_temperature": "electrochemistry:electrochemistry_b90b1ad7_b9a8_44df_ad45_bfd25aac2e49",
        "maximum_discharging_temperature": "electrochemistry:electrochemistry_de612af2_a029_4a02_8090_4a75ab13271d",
        "minimum_discharging_temperature": "electrochemistry:electrochemistry_2a1de79f_e927_45a2_9619_3799a0d61e9b",
        "maximum_storage_temperature": "electrochemistry:electrochemistry_0ea4d188_9701_4699_a5ca_812a98a9afa7",
        "minimum_storage_temperature": "electrochemistry:electrochemistry_0ddfd57a_d338_4690_be45_b26884ed6302",
        "operating_temperature_min": "battinfo:operatingTemperatureMin",
        "operating_temperature_max": "battinfo:operatingTemperatureMax",
        "cycle_life": "electrochemistry:electrochemistry_ae782b14_88ce_4cdd_9418_12aca00be937",
        "cycle_life_c_rate": "battinfo:cycleLifeCRate",
        "calendar_life": "electrochemistry:electrochemistry_743c71a3_b80c_42e3_92fa_13a67b8167df",
        "capacity_fade": "battinfo:capacityFade",
        "capacity_threshold_exhaustion": "battinfo:capacityThresholdExhaustion",
        "charging_time": "battinfo:chargingTime",
        "self_discharge_rate": "electrochemistry:electrochemistry_c3e97d58_1854_4c23_bb42_d2972172865e",
        "state_of_health": "electrochemistry:electrochemistry_a7a4614f_2426_46f3_8475_cda4a9fabfce",
        "source_type": "battinfo:sourceType",
        "source_url": "battinfo:sourceURL",
        "source_file": "battinfo:sourceFile",
        "citation": "dcterms:bibliographicCitation",
        "citation_doi": "battinfo:citationDOI",
        "retrieved_at": "battinfo:retrievedAt",
        "workflow_version": "battinfo:workflowVersion",
        "curated_by": "dcterms:contributor",
        "protocol_name": "schema:name",
        "protocol_url": "schema:url",
        "V": "emmo:Volt",
        "mV": "emmo:MilliVolt",
        "kV": "emmo:KiloVolt",
        "Ah": "emmo:AmpereHour",
        "mAh": "emmo:MilliAmpereHour",
        "A": "emmo:Ampere",
        "mA": "emmo:MilliAmpere",
        "W": "emmo:Watt",
        "kW": "emmo:KiloWatt",
        "Wh": "emmo:WattHour",
        "kWh": "emmo:KiloWattHour",
        "MWh": "emmo:MegaWattHour",
        "Ohm": "emmo:Ohm",
        "mOhm": "emmo:MilliOhm",
        "mohm": "emmo:MilliOhm",
        "degC": "emmo:EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc",
        "K": "emmo:Kelvin",
        "g": "emmo:Gram",
        "kg": "emmo:Kilogram",
        "mg": "emmo:MilliGram",
        "mm": "emmo:MilliMetre",
        "cm": "emmo:CentiMetre",
        "m": "emmo:Metre",
        "L": "emmo:Litre",
        "mL": "emmo:MilliLitre",
        "cm3": "emmo:CubicCentiMetre",
        "h": "emmo:Hour",
        "min": "emmo:Minute",
        "s": "emmo:Second",
        "1": "emmo:EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
        "%": "emmo:Percent",
        "license": {
          "@id": "dcterms:license",
          "@type": "@id"
        },
        "created_at": {
          "@id": "dcterms:created",
          "@type": "xsd:dateTime"
        },
        "modified_at": {
          "@id": "dcterms:modified",
          "@type": "xsd:dateTime"
        }
      },
      "@type": "https://w3id.org/emmo/domain/battery#battery_dca7729a_421a_4921_90cf_9692bb9eb081",
      "@id": "https://w3id.org/battinfo/test/5p7v-2n8k-4m3t-6q9r",
      "schema:name": "A123 ANR26650M1-B baseline cycling",
      "battinfo:testKind": "cycling",
      "battinfo:protocolName": "0.5C charge/discharge baseline cycling",
      "battinfo:status": "completed",
      "battinfo:testedCell": {
        "@id": "https://w3id.org/battinfo/cell/3m6k-9t2p-7x4h-9nq8"
      },
      "battinfo:hasDataset": [
        {
          "@id": "https://w3id.org/battinfo/dataset/1f8r-6v2k-9p4m-3t7x"
        }
      ],
      "battinfo:provenance": {
        "battinfo:sourceType": "measurement",
        "battinfo:sourceFile": "test-5p7v-2n8k-4m3t-6q9r.json",
        "battinfo:sourceURL": {
          "@id": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
        },
        "dcterms:bibliographicCitation": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      }
    }
  },
  {
    "slug": "dataset",
    "label": "Dataset — the files a test produced",
    "recordType": "dataset",
    "sourceFile": "examples/dataset/dataset-1f8r-6v2k-9p4m-3t7x.json",
    "highlight": "Datasets are DCAT: catalogable, with distributions and checksums — the shape data portals already understand.",
    "record": {
      "schema_version": "0.2.0",
      "dataset": {
        "id": "https://w3id.org/battinfo/dataset/1f8r-6v2k-9p4m-3t7x",
        "short_id": "1f8r6v",
        "identifier": "doi:10.5281/zenodo.1234567",
        "name": "Cell cycling run for BattINFO cell 3m6k9t",
        "description": "Raw cycling and metadata export for one physical cell.",
        "access_url": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x",
        "same_as": [
          "https://doi.org/10.5281/zenodo.1234567"
        ],
        "license": "https://creativecommons.org/licenses/by/4.0/",
        "version": "1.0.0",
        "keywords": [
          "battery cycling",
          "time series",
          "lithium-ion"
        ],
        "creators": [
          {
            "type": "Organization",
            "name": "BattINFO Maintainers"
          }
        ],
        "publisher": {
          "type": "Organization",
          "name": "BattINFO"
        },
        "citations": [
          {
            "kind": "dataset",
            "url": "https://doi.org/10.5281/zenodo.1234567",
            "doi": "10.5281/zenodo.1234567",
            "citation_key": "example_dataset_2026"
          }
        ],
        "about": [
          "https://w3id.org/battinfo/cell/3m6k-9t2p-7x4h-9nq8",
          "https://w3id.org/battinfo/test/5p7v-2n8k-4m3t-6q9r"
        ],
        "measurement_techniques": [
          "cycling"
        ],
        "measurement_methods": [
          "galvanostatic cycling"
        ],
        "variable_measured": [
          {
            "name": "voltage",
            "unit_text": "V"
          },
          {
            "name": "current",
            "unit_text": "A"
          },
          {
            "name": "capacity",
            "unit_text": "Ah"
          }
        ],
        "is_accessible_for_free": true,
        "in_language": "en",
        "created_at": 1771718400,
        "modified_at": 1771718400,
        "published_at": 1771718400,
        "distributions": [
          {
            "type": "DataDownload",
            "name": "Raw cycling HDF5 archive",
            "content_url": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x/raw.h5",
            "encoding_format": "application/x-hdf5",
            "checksum": {
              "algorithm": "sha256",
              "value": "8fbf34bd0f8a0caef6f5ce6cc1f8e6a2d8f0123982fc624d6f7f3f7e27b95a89"
            },
            "access_level": "open"
          }
        ]
      },
      "provenance": {
        "source_type": "measurement",
        "source_name": "Example Lab Data Portal",
        "source_url": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x",
        "source_file": "dataset-1f8r-6v2k-9p4m-3t7x.json",
        "source_dataset_key": "example-0001",
        "ingest_status": "ready",
        "quality_flags": [],
        "retrieved_at": 1771718400,
        "curated_by": "BattINFO Maintainers",
        "workflow_version": "0.2.0",
        "citation": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      },
      "notes": [
        "Schema.org-first dataset record with BattINFO battery extensions.",
        "Used as a canonical example for dataset ingestion and linking workflows."
      ]
    },
    "jsonld": {
      "@context": {
        "@version": 1.1,
        "battery": "https://w3id.org/emmo/domain/battery#",
        "electrochemistry": "https://w3id.org/emmo/domain/electrochemistry#",
        "emmo": "https://w3id.org/emmo#",
        "battinfo": "https://w3id.org/battinfo/",
        "schema": "https://schema.org/",
        "dcterms": "http://purl.org/dc/terms/",
        "prov": "http://www.w3.org/ns/prov#",
        "dcat": "http://www.w3.org/ns/dcat#",
        "dqv": "http://www.w3.org/ns/dqv#",
        "oa": "http://www.w3.org/ns/oa#",
        "earl": "http://www.w3.org/ns/earl#",
        "spdx": "http://spdx.org/rdf/terms#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "BatteryCell": "battery:battery_68ed592a_7924_45d0_a108_94d6275d57f0",
        "BatteryCellSpecification": "battery:battery_1cfbba6c_8824_4932_a23e_2141483acef7",
        "CylindricalBattery": "battery:battery_ac604ecd_cc60_4b98_b57c_74cd5d3ccd40",
        "PrismaticBattery": "battery:battery_86c9ca80_de6f_417f_afdc_a7e52fa6322d",
        "PouchCell": "battery:battery_392b3f47_d62a_4bd4_a819_b58b09b8843a",
        "CoinCell": "battery:battery_b7fdab58_6e91_4c84_b097_b06eff86a124",
        "LithiumIonBattery": "battery:battery_96addc62_ea04_449a_8237_4cd541dd8e5f",
        "LithiumMetalBattery": "battery:battery_ada13509_4eed_4e40_a7b1_4cc488144154",
        "SodiumIonBattery": "battery:battery_42329a95_03fe_4ec1_83cb_b7e8ed52f68a",
        "AlkalineZincManganeseDioxideBattery": "battery:battery_b572826a_b4e4_4986_b57d_f7b945061f8b",
        "AlkalineCell": "battery:battery_50b911f7_c903_4700_9764_c308d8a95470",
        "PrimaryBattery": "battery:battery_3b0b0d6e_8b0e_4491_885e_8421d3eb3b69",
        "SecondaryBattery": "battery:battery_efc38420_ecbb_42e4_bb3f_208e7c417098",
        "BatteryTest": "battery:battery_dca7729a_421a_4921_90cf_9692bb9eb081",
        "name": "schema:name",
        "model": "schema:model",
        "manufacturer": "schema:manufacturer",
        "hasProperty": {
          "@id": "emmo:EMMO_e1097637_70d2_4895_973f_2396f04fa204",
          "@type": "@id"
        },
        "hasNumericalPart": {
          "@id": "emmo:EMMO_8ef3cd6d_ae58_4a8d_9fc0_ad8f49015cd0",
          "@type": "@id"
        },
        "hasNumberValue": "emmo:EMMO_faf79f53_749d_40b2_807c_d34244c192f4",
        "hasNumericalValue": "emmo:EMMO_faf79f53_749d_40b2_807c_d34244c192f4",
        "hasMeasurementUnit": {
          "@id": "emmo:EMMO_bed1d005_b04e_4a90_94cf_02bc678a8569",
          "@type": "@id"
        },
        "isDescriptionFor": {
          "@id": "emmo:EMMO_f702bad4_fc77_41f0_a26d_79f6444fd4f3",
          "@type": "@id"
        },
        "hasDescription": {
          "@id": "emmo:EMMO_c58c799e_cc6c_4310_a3f1_78da70705b2a",
          "@type": "@id"
        },
        "hasTestObject": {
          "@id": "battery:battery_da3b3f28_aaad_4d67_b674_df47e109fb8b",
          "@type": "@id"
        },
        "hasTestEquipment": {
          "@id": "battery:battery_df4ff8f1_2cf2_444a_9498_23f533bd295c",
          "@type": "@id"
        },
        "hasOutput": {
          "@id": "emmo:EMMO_c4bace1d_4db0_4cd3_87e9_18122bae2840",
          "@type": "@id"
        },
        "id": "schema:productID",
        "nominal_capacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "minimum_capacity": "electrochemistry:electrochemistry_d3c0078e_c1d3_461e_873d_e5c3adf441c5",
        "rated_capacity": "electrochemistry:electrochemistry_9b3b4668_0795_4a35_9965_2af383497a26",
        "typical_capacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "nominal_voltage": "electrochemistry:electrochemistry_639b844a_e801_436b_985d_28926129ead6",
        "charging_voltage": "electrochemistry:electrochemistry_79a9e1be_35b0_4c3c_8087_b5f967ca0e87",
        "discharging_cutoff_voltage": "electrochemistry:electrochemistry_534dd59c_904c_45d9_8550_ae9d2eb6bbc9",
        "charging_cutoff_voltage": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "upper_voltage_limit": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "maximum_continuous_charging_current": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "nominal_continuous_charging_current": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "maximum_pulse_charging_current": "electrochemistry:electrochemistry_1b2a7137_64d4_483a_8437_dcb3bedcb6da",
        "maximum_continuous_discharging_current": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "nominal_continuous_discharging_current": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "maximum_pulse_discharging_current": "electrochemistry:electrochemistry_3e54f9e3_a31d_4821_9bfb_ef953a42c35b",
        "nominal_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "typical_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "rated_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "certified_usable_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "power_capability": "battinfo:powerCapability",
        "maximum_power": "battinfo:maximumPower",
        "specific_energy": "emmo:EMMO_e218c625_6a39_47a9_8d08_a2ef41c152a9",
        "energy_density": "electrochemistry:electrochemistry_4aa1b96e_44a0_4b1a_a0ac_723d0223d80b",
        "specific_power": "battinfo:specificPower",
        "power_density": "battinfo:powerDensity",
        "power_energy_ratio": "battinfo:powerEnergyRatio",
        "internal_resistance": "electrochemistry:electrochemistry_9bf40017_3f58_4030_ada7_cb37a3dfda2d",
        "dc_internal_resistance": "electrochemistry:electrochemistry_7b3eb826_b968_493a_8396_cc3a5f09ecb3",
        "ac_internal_resistance": "electrochemistry:electrochemistry_964cd426_f3cf_4a52_8c5d_0490cf48edb5",
        "impedance": "emmo:EMMO_79a02de5_b884_4eab_bc18_f67997d597a2",
        "round_trip_energy_efficiency": "battinfo:roundTripEnergyEfficiency",
        "round_trip_energy_efficiency_50pct": "battinfo:roundTripEnergyEfficiency50Pct",
        "initial_coulombic_efficiency": "electrochemistry:electrochemistry_469b9516_a96d_4aa2_b8e5_05ae982e2084",
        "mass": "emmo:EMMO_ed4af7ae_63a2_497e_bb88_2309619ea405",
        "diameter": "emmo:EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6",
        "height": "emmo:EMMO_08bcf1d6_e719_46c8_bb21_24bc9bf34dba",
        "width": "emmo:EMMO_e4de48b1_dabb_4490_ac2b_040f926c64f0",
        "length": "emmo:EMMO_cd2cd0de_e0cc_4ef1_b27e_2e88db027bac",
        "thickness": "emmo:EMMO_43003c86_9d15_433b_9789_ee2940920656",
        "volume": "emmo:EMMO_f1a51559_aa3d_43a0_9327_918039f0dfed",
        "maximum_charging_temperature": "electrochemistry:electrochemistry_4a354510_4dc2_4803_8845_f4024a1a7260",
        "minimum_charging_temperature": "electrochemistry:electrochemistry_b90b1ad7_b9a8_44df_ad45_bfd25aac2e49",
        "maximum_discharging_temperature": "electrochemistry:electrochemistry_de612af2_a029_4a02_8090_4a75ab13271d",
        "minimum_discharging_temperature": "electrochemistry:electrochemistry_2a1de79f_e927_45a2_9619_3799a0d61e9b",
        "maximum_storage_temperature": "electrochemistry:electrochemistry_0ea4d188_9701_4699_a5ca_812a98a9afa7",
        "minimum_storage_temperature": "electrochemistry:electrochemistry_0ddfd57a_d338_4690_be45_b26884ed6302",
        "operating_temperature_min": "battinfo:operatingTemperatureMin",
        "operating_temperature_max": "battinfo:operatingTemperatureMax",
        "cycle_life": "electrochemistry:electrochemistry_ae782b14_88ce_4cdd_9418_12aca00be937",
        "cycle_life_c_rate": "battinfo:cycleLifeCRate",
        "calendar_life": "electrochemistry:electrochemistry_743c71a3_b80c_42e3_92fa_13a67b8167df",
        "capacity_fade": "battinfo:capacityFade",
        "capacity_threshold_exhaustion": "battinfo:capacityThresholdExhaustion",
        "charging_time": "battinfo:chargingTime",
        "self_discharge_rate": "electrochemistry:electrochemistry_c3e97d58_1854_4c23_bb42_d2972172865e",
        "state_of_health": "electrochemistry:electrochemistry_a7a4614f_2426_46f3_8475_cda4a9fabfce",
        "source_type": "battinfo:sourceType",
        "source_url": "battinfo:sourceURL",
        "source_file": "battinfo:sourceFile",
        "citation": "dcterms:bibliographicCitation",
        "citation_doi": "battinfo:citationDOI",
        "retrieved_at": "battinfo:retrievedAt",
        "workflow_version": "battinfo:workflowVersion",
        "curated_by": "dcterms:contributor",
        "protocol_name": "schema:name",
        "protocol_url": "schema:url",
        "V": "emmo:Volt",
        "mV": "emmo:MilliVolt",
        "kV": "emmo:KiloVolt",
        "Ah": "emmo:AmpereHour",
        "mAh": "emmo:MilliAmpereHour",
        "A": "emmo:Ampere",
        "mA": "emmo:MilliAmpere",
        "W": "emmo:Watt",
        "kW": "emmo:KiloWatt",
        "Wh": "emmo:WattHour",
        "kWh": "emmo:KiloWattHour",
        "MWh": "emmo:MegaWattHour",
        "Ohm": "emmo:Ohm",
        "mOhm": "emmo:MilliOhm",
        "mohm": "emmo:MilliOhm",
        "degC": "emmo:EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc",
        "K": "emmo:Kelvin",
        "g": "emmo:Gram",
        "kg": "emmo:Kilogram",
        "mg": "emmo:MilliGram",
        "mm": "emmo:MilliMetre",
        "cm": "emmo:CentiMetre",
        "m": "emmo:Metre",
        "L": "emmo:Litre",
        "mL": "emmo:MilliLitre",
        "cm3": "emmo:CubicCentiMetre",
        "h": "emmo:Hour",
        "min": "emmo:Minute",
        "s": "emmo:Second",
        "1": "emmo:EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
        "%": "emmo:Percent",
        "license": {
          "@id": "dcterms:license",
          "@type": "@id"
        },
        "created_at": {
          "@id": "dcterms:created",
          "@type": "xsd:dateTime"
        },
        "modified_at": {
          "@id": "dcterms:modified",
          "@type": "xsd:dateTime"
        }
      },
      "@type": "http://www.w3.org/ns/dcat#Dataset",
      "@id": "https://w3id.org/battinfo/dataset/1f8r-6v2k-9p4m-3t7x",
      "dcterms:title": "Cell cycling run for BattINFO cell 3m6k9t",
      "dcterms:license": {
        "@id": "https://creativecommons.org/licenses/by/4.0/"
      },
      "dcat:accessURL": {
        "@id": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      },
      "dcterms:created": "2026-02-22T00:00:00Z",
      "dcterms:modified": "2026-02-22T00:00:00Z",
      "dcterms:subject": [
        {
          "@id": "https://w3id.org/battinfo/cell/3m6k-9t2p-7x4h-9nq8"
        },
        {
          "@id": "https://w3id.org/battinfo/test/5p7v-2n8k-4m3t-6q9r"
        }
      ],
      "dcat:distribution": [
        {
          "@type": "dcat:Distribution",
          "dcat:downloadURL": {
            "@id": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x/raw.h5"
          },
          "dcat:mediaType": "application/x-hdf5",
          "spdx:checksum": {
            "@type": "spdx:Checksum",
            "spdx:checksumAlgorithm": "spdx:checksumAlgorithm_sha256",
            "spdx:checksumValue": "8fbf34bd0f8a0caef6f5ce6cc1f8e6a2d8f0123982fc624d6f7f3f7e27b95a89"
          }
        }
      ],
      "battinfo:provenance": {
        "battinfo:sourceType": "measurement",
        "battinfo:sourceFile": "dataset-1f8r-6v2k-9p4m-3t7x.json",
        "battinfo:sourceURL": {
          "@id": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
        },
        "dcterms:bibliographicCitation": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      }
    }
  }
];
