// GENERATED by scripts/gen_web_jsonld.py — do not edit.
// Each pair is the canonical example record and the JSON-LD the REAL
// Python transform emits for it (battinfo.record_to_jsonld).
// tests/test_web_generated.py fails when this file drifts from the library.

export const jsonldGallery: {
  slug: string;
  label: string;
  recordType: string;
  sourceFile: string;
  highlight: string;
  record: Record<string, unknown>;
  jsonld: Record<string, unknown>;
}[] = [
  {
    "slug": "cell-spec",
    "label": "Cell spec — A123 ANR26650M1-B",
    "recordType": "cell-spec",
    "sourceFile": "examples/cell-spec/A123__ANR26650M1-B.json",
    "highlight": "EMMO @type stacking: one cylindrical LFP cell is simultaneously a BatteryCell, a CylindricalBattery, and a LithiumIronPhosphateBattery — no manual annotation.",
    "record": {
      "schema_version": "0.1.0",
      "cell_spec": {
        "id": "https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5",
        "short_id": "7d9k2m",
        "identifier": "cell-spec:7d9k-2m4p-8t3x-6nq5",
        "name": "A123 ANR26650M1-B",
        "model": "ANR26650M1-B",
        "manufacturer": {
          "type": "Organization",
          "name": "A123",
          "id": "https://w3id.org/battinfo/organization/9k3e-absq-8131-vyjd"
        },
        "brand": {
          "type": "Brand",
          "name": "A123"
        },
        "category": "battery cell",
        "cell_format": "cylindrical",
        "chemistry": "Li-ion",
        "positive_electrode_basis": "LFP",
        "negative_electrode_basis": "unknown",
        "size_code": "R26650",
        "iec_code": "IFpR26650",
        "country_of_origin": "United States",
        "year": 2012
      },
      "properties": {
        "nominal_capacity": {
          "value": 2.5,
          "unit": "Ah",
          "raw": {
            "text": "Cell Capacity (nominal/minimum) (0.5C Rate) 2.5/2.4 Ah",
            "page": 1,
            "confidence": 0.8
          }
        },
        "minimum_capacity": {
          "value": 2.4,
          "unit": "Ah",
          "raw": {
            "text": "Cell Capacity (nominal/minimum) (0.5C Rate) 2.5/2.4 Ah",
            "page": 1,
            "confidence": 0.8
          }
        },
        "nominal_voltage": {
          "value": 3.3,
          "unit": "V",
          "raw": {
            "text": "Voltage (nominal) 3.3V",
            "page": 1,
            "confidence": 0.8
          }
        },
        "internal_resistance": {
          "value": 6.0,
          "unit": "mΩ",
          "raw": {
            "text": "Internal Impedance (1kHz AC typical) 6mΩ",
            "page": 1,
            "confidence": 0.8
          }
        },
        "mass": {
          "value": 76.0,
          "unit": "g",
          "raw": {
            "text": "Cell Weight 76g",
            "page": 1,
            "confidence": 0.8
          }
        },
        "diameter": {
          "value": 26.0,
          "unit": "mm",
          "raw": {
            "text": "Cell Dimensions 26 x 65 mm",
            "page": 1,
            "confidence": 0.8
          }
        },
        "height": {
          "value": 65.0,
          "unit": "mm",
          "raw": {
            "text": "Cell Dimensions 26 x 65 mm",
            "page": 1,
            "confidence": 0.8
          }
        },
        "pulse_charging_current": {
          "value": 10.0,
          "unit": "A",
          "raw": {
            "text": "Recommended Fast Charge Method to 80% SOC 10A to 3.6V CC, 12 min",
            "page": 1,
            "confidence": 0.8
          }
        },
        "nominal_continuous_charging_current": {
          "value": 2.5,
          "unit": "A",
          "raw": {
            "text": "Recommended Standard Charge Method 2.5A to 3.6V CCCV, 60 min",
            "page": 1,
            "confidence": 0.8
          }
        },
        "maximum_continuous_charging_current": {
          "value": 2.5,
          "unit": "A",
          "raw": {
            "text": "Recommended Standard Charge Method 2.5A to 3.6V CCCV, 60 min",
            "page": 1,
            "confidence": 0.8
          }
        },
        "maximum_continuous_discharging_current": {
          "value": 50.0,
          "unit": "A",
          "raw": {
            "text": "Maximum Continuous Discharge 50A",
            "page": 1,
            "confidence": 0.8
          }
        },
        "minimum_discharging_temperature": {
          "value": -30,
          "unit": "°C",
          "raw": {
            "text": "Operating Temperature -30°C to 55°C",
            "page": 1,
            "confidence": 0.8
          }
        },
        "maximum_discharging_temperature": {
          "value": 55,
          "unit": "°C",
          "raw": {
            "text": "Operating Temperature -30°C to 55°C",
            "page": 1,
            "confidence": 0.8
          }
        },
        "minimum_storage_temperature": {
          "value": -40,
          "unit": "°C",
          "raw": {
            "text": "Storage Temperature -40°C to 60°C",
            "page": 1,
            "confidence": 0.8
          }
        },
        "maximum_storage_temperature": {
          "value": 60,
          "unit": "°C",
          "raw": {
            "text": "Storage Temperature -40°C to 60°C",
            "page": 1,
            "confidence": 0.8
          }
        },
        "cycle_life": {
          "value_text": ">1000",
          "unit": "count",
          "raw": {
            "text": "Cycle Life at 20A Discharge, 100% DOD >1,000 cycles",
            "page": 1,
            "confidence": 0.7
          }
        }
      },
      "provenance": {
        "source_type": "datasheet",
        "source_file": "A123__ANR26650M1-B.pdf",
        "source_url": null,
        "file_hash": "b5069f48e121de3a1308af66215e7a97a1c8c6a87227da089c83e352f1ddf35e",
        "retrieved_at": 1769585584
      }
    },
    "jsonld": {
      "@context": {
        "@version": 1.1,
        "battery": "https://w3id.org/emmo/domain/battery#",
        "electrochemistry": "https://w3id.org/emmo/domain/electrochemistry#",
        "emmo": "https://w3id.org/emmo#",
        "battinfo": "https://w3id.org/battinfo/",
        "schema": "https://schema.org/",
        "dcterms": "http://purl.org/dc/terms/",
        "prov": "http://www.w3.org/ns/prov#",
        "dcat": "http://www.w3.org/ns/dcat#",
        "bibo": "http://purl.org/ontology/bibo/",
        "pav": "http://purl.org/pav/",
        "dqv": "http://www.w3.org/ns/dqv#",
        "oa": "http://www.w3.org/ns/oa#",
        "earl": "http://www.w3.org/ns/earl#",
        "spdx": "http://spdx.org/rdf/terms#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "skos": "http://www.w3.org/2004/02/skos/core#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "BatteryCell": "battery:battery_68ed592a_7924_45d0_a108_94d6275d57f0",
        "BatteryCellSpecification": "battery:battery_1cfbba6c_8824_4932_a23e_2141483acef7",
        "CylindricalBattery": "battery:battery_ac604ecd_cc60_4b98_b57c_74cd5d3ccd40",
        "PrismaticBattery": "battery:battery_86c9ca80_de6f_417f_afdc_a7e52fa6322d",
        "PouchCell": "battery:battery_392b3f47_d62a_4bd4_a819_b58b09b8843a",
        "CoinCell": "battery:battery_b7fdab58_6e91_4c84_b097_b06eff86a124",
        "LithiumIonBattery": "battery:battery_96addc62_ea04_449a_8237_4cd541dd8e5f",
        "LithiumMetalBattery": "battery:battery_ada13509_4eed_4e40_a7b1_4cc488144154",
        "SodiumIonBattery": "battery:battery_42329a95_03fe_4ec1_83cb_b7e8ed52f68a",
        "AlkalineZincManganeseDioxideBattery": "battery:battery_b572826a_b4e4_4986_b57d_f7b945061f8b",
        "AlkalineCell": "battery:battery_50b911f7_c903_4700_9764_c308d8a95470",
        "PrimaryBattery": "battery:battery_3b0b0d6e_8b0e_4491_885e_8421d3eb3b69",
        "SecondaryBattery": "battery:battery_efc38420_ecbb_42e4_bb3f_208e7c417098",
        "BatteryTest": "battery:battery_dca7729a_421a_4921_90cf_9692bb9eb081",
        "name": "schema:name",
        "model": "schema:model",
        "manufacturer": "schema:manufacturer",
        "hasProperty": {
          "@id": "emmo:EMMO_e1097637_70d2_4895_973f_2396f04fa204",
          "@type": "@id"
        },
        "hasNumericalPart": {
          "@id": "emmo:EMMO_8ef3cd6d_ae58_4a8d_9fc0_ad8f49015cd0",
          "@type": "@id"
        },
        "hasNumberValue": "emmo:EMMO_faf79f53_749d_40b2_807c_d34244c192f4",
        "hasNumericalValue": "emmo:EMMO_faf79f53_749d_40b2_807c_d34244c192f4",
        "hasMeasurementUnit": {
          "@id": "emmo:EMMO_bed1d005_b04e_4a90_94cf_02bc678a8569",
          "@type": "@id"
        },
        "isDescriptionFor": {
          "@id": "emmo:EMMO_f702bad4_fc77_41f0_a26d_79f6444fd4f3",
          "@type": "@id"
        },
        "hasDescription": {
          "@id": "emmo:EMMO_c58c799e_cc6c_4310_a3f1_78da70705b2a",
          "@type": "@id"
        },
        "hasTestObject": {
          "@id": "battery:battery_da3b3f28_aaad_4d67_b674_df47e109fb8b",
          "@type": "@id"
        },
        "hasTestEquipment": {
          "@id": "battery:battery_df4ff8f1_2cf2_444a_9498_23f533bd295c",
          "@type": "@id"
        },
        "hasOutput": {
          "@id": "emmo:EMMO_c4bace1d_4db0_4cd3_87e9_18122bae2840",
          "@type": "@id"
        },
        "id": "schema:productID",
        "nominal_capacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "minimum_capacity": "electrochemistry:electrochemistry_d3c0078e_c1d3_461e_873d_e5c3adf441c5",
        "rated_capacity": "electrochemistry:electrochemistry_9b3b4668_0795_4a35_9965_2af383497a26",
        "typical_capacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "nominal_voltage": "electrochemistry:electrochemistry_639b844a_e801_436b_985d_28926129ead6",
        "charging_voltage": "electrochemistry:electrochemistry_79a9e1be_35b0_4c3c_8087_b5f967ca0e87",
        "discharging_cutoff_voltage": "electrochemistry:electrochemistry_534dd59c_904c_45d9_8550_ae9d2eb6bbc9",
        "charging_cutoff_voltage": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "upper_voltage_limit": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "maximum_continuous_charging_current": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "nominal_continuous_charging_current": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "maximum_pulse_charging_current": "electrochemistry:electrochemistry_1b2a7137_64d4_483a_8437_dcb3bedcb6da",
        "maximum_continuous_discharging_current": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "nominal_continuous_discharging_current": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "maximum_pulse_discharging_current": "electrochemistry:electrochemistry_3e54f9e3_a31d_4821_9bfb_ef953a42c35b",
        "nominal_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "typical_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "rated_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "certified_usable_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "power_capability": "battinfo:powerCapability",
        "maximum_power": "battinfo:maximumPower",
        "specific_energy": "emmo:EMMO_e218c625_6a39_47a9_8d08_a2ef41c152a9",
        "energy_density": "electrochemistry:electrochemistry_4aa1b96e_44a0_4b1a_a0ac_723d0223d80b",
        "specific_power": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_c762a928_5a74_46fd_9929_4ac2d7a3a8d7",
        "power_density": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_a7eb870c_4ef7_4ccd_85e8_4b7b726d7a2a",
        "power_energy_ratio": "battinfo:powerEnergyRatio",
        "internal_resistance": "electrochemistry:electrochemistry_9bf40017_3f58_4030_ada7_cb37a3dfda2d",
        "dc_internal_resistance": "electrochemistry:electrochemistry_7b3eb826_b968_493a_8396_cc3a5f09ecb3",
        "ac_internal_resistance": "electrochemistry:electrochemistry_964cd426_f3cf_4a52_8c5d_0490cf48edb5",
        "impedance": "emmo:EMMO_79a02de5_b884_4eab_bc18_f67997d597a2",
        "round_trip_energy_efficiency": "battinfo:roundTripEnergyEfficiency",
        "round_trip_energy_efficiency_50pct": "battinfo:roundTripEnergyEfficiency50Pct",
        "initial_coulombic_efficiency": "electrochemistry:electrochemistry_469b9516_a96d_4aa2_b8e5_05ae982e2084",
        "mass": "emmo:EMMO_ed4af7ae_63a2_497e_bb88_2309619ea405",
        "diameter": "emmo:EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6",
        "height": "emmo:EMMO_08bcf1d6_e719_46c8_bb21_24bc9bf34dba",
        "width": "emmo:EMMO_e4de48b1_dabb_4490_ac2b_040f926c64f0",
        "length": "emmo:EMMO_cd2cd0de_e0cc_4ef1_b27e_2e88db027bac",
        "thickness": "emmo:EMMO_43003c86_9d15_433b_9789_ee2940920656",
        "volume": "emmo:EMMO_f1a51559_aa3d_43a0_9327_918039f0dfed",
        "maximum_charging_temperature": "electrochemistry:electrochemistry_4a354510_4dc2_4803_8845_f4024a1a7260",
        "minimum_charging_temperature": "electrochemistry:electrochemistry_b90b1ad7_b9a8_44df_ad45_bfd25aac2e49",
        "maximum_discharging_temperature": "electrochemistry:electrochemistry_de612af2_a029_4a02_8090_4a75ab13271d",
        "minimum_discharging_temperature": "electrochemistry:electrochemistry_2a1de79f_e927_45a2_9619_3799a0d61e9b",
        "maximum_storage_temperature": "electrochemistry:electrochemistry_0ea4d188_9701_4699_a5ca_812a98a9afa7",
        "minimum_storage_temperature": "electrochemistry:electrochemistry_0ddfd57a_d338_4690_be45_b26884ed6302",
        "operating_temperature_min": "battinfo:operatingTemperatureMin",
        "operating_temperature_max": "battinfo:operatingTemperatureMax",
        "cycle_life": "electrochemistry:electrochemistry_ae782b14_88ce_4cdd_9418_12aca00be937",
        "cycle_life_c_rate": "battinfo:cycleLifeCRate",
        "calendar_life": "electrochemistry:electrochemistry_743c71a3_b80c_42e3_92fa_13a67b8167df",
        "capacity_fade": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_e3d3d21c_cb9a_498c_bdb0_63c964f0d3c6",
        "capacity_threshold_exhaustion": "battinfo:capacityThresholdExhaustion",
        "charging_time": "battinfo:chargingTime",
        "self_discharge_rate": "electrochemistry:electrochemistry_c3e97d58_1854_4c23_bb42_d2972172865e",
        "state_of_health": "electrochemistry:electrochemistry_a7a4614f_2426_46f3_8475_cda4a9fabfce",
        "source_type": "dcterms:type",
        "source_url": {
          "@id": "prov:hadPrimarySource",
          "@type": "@id"
        },
        "citation": "dcterms:bibliographicCitation",
        "citation_doi": "bibo:doi",
        "retrieved_at": "prov:generatedAtTime",
        "workflow_version": "pav:version",
        "curated_by": "dcterms:contributor",
        "protocol_name": "schema:name",
        "protocol_url": "schema:url",
        "V": "emmo:Volt",
        "mV": "emmo:MilliVolt",
        "kV": "emmo:KiloVolt",
        "Ah": "emmo:AmpereHour",
        "mAh": "emmo:MilliAmpereHour",
        "A": "emmo:Ampere",
        "mA": "emmo:MilliAmpere",
        "W": "emmo:Watt",
        "kW": "emmo:KiloWatt",
        "Wh": "emmo:WattHour",
        "kWh": "emmo:KiloWattHour",
        "MWh": "emmo:MegaWattHour",
        "Ohm": "emmo:Ohm",
        "mOhm": "emmo:MilliOhm",
        "mohm": "emmo:MilliOhm",
        "degC": "emmo:EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc",
        "K": "emmo:Kelvin",
        "g": "emmo:Gram",
        "kg": "emmo:Kilogram",
        "mg": "emmo:MilliGram",
        "mm": "emmo:MilliMetre",
        "cm": "emmo:CentiMetre",
        "m": "emmo:Metre",
        "L": "emmo:Litre",
        "mL": "emmo:MilliLitre",
        "cm3": "emmo:CubicCentiMetre",
        "h": "emmo:Hour",
        "min": "emmo:Minute",
        "s": "emmo:Second",
        "1": "emmo:EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
        "%": "emmo:Percent",
        "license": {
          "@id": "dcterms:license",
          "@type": "@id"
        },
        "created_at": {
          "@id": "dcterms:created",
          "@type": "xsd:dateTime"
        },
        "modified_at": {
          "@id": "dcterms:modified",
          "@type": "xsd:dateTime"
        },
        "LR03": "battery:battery_a5299801_2a8d_4d03_a476_ca2c5e9ca702",
        "LR6": "battery:battery_6b2540b9_5af6_478a_81ae_583db9636db8",
        "LR14": "battery:battery_d00e842e_ee0b_4e25_bd17_d64d76d69730",
        "LR20": "battery:battery_0c9979c2_c981_48ea_a8e1_72bdcb58fd58",
        "LR1": "battery:battery_1c0306f5_5698_4874_b6ce_e5cc45a46b91",
        "CR2032": "battery:battery_b61b96ac_f2f4_4b74_82d5_565fe3a2d88b",
        "CR2025": "battery:battery_9984642f_c9dc_4b98_94f6_6ffe20cfc014",
        "LR44": "battery:battery_d10ff656_f9fd_4b0e_9de9_4812a44ea359",
        "HR6": "battery:battery_a71a4bf2_dee6_4aa4_8ad4_9f38c261fb84",
        "KR6": "battery:battery_ad7c1d81_9a9f_4174_88ea_3ba3e8f4dbe2",
        "ACInternalResistance": "electrochemistry:electrochemistry_964cd426_f3cf_4a52_8c5d_0490cf48edb5",
        "Volume": "emmo:EMMO_f1a51559_aa3d_43a0_9327_918039f0dfed",
        "CalendarLife": "electrochemistry:electrochemistry_743c71a3_b80c_42e3_92fa_13a67b8167df",
        "Mass": "emmo:EMMO_ed4af7ae_63a2_497e_bb88_2309619ea405",
        "CapacityFade": "electrochemistry:electrochemistry_e3d3d21c_cb9a_498c_bdb0_63c964f0d3c6",
        "NominalEnergy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "UpperVoltageLimit": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "MaximumChargingTemperature": "electrochemistry:electrochemistry_4a354510_4dc2_4803_8845_f4024a1a7260",
        "MinimumChargingTemperature": "electrochemistry:electrochemistry_b90b1ad7_b9a8_44df_ad45_bfd25aac2e49",
        "ChargingVoltage": "electrochemistry:electrochemistry_79a9e1be_35b0_4c3c_8087_b5f967ca0e87",
        "MaximumContinuousChargingCurrent": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "MaximumContinuousDischargingCurrent": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "CycleLife": "electrochemistry:electrochemistry_ae782b14_88ce_4cdd_9418_12aca00be937",
        "D50ParticleSize": "electrochemistry:electrochemistry_3cfdfc10_a5cb_4e3e_b1a1_281010d1465c",
        "DCInternalResistance": "electrochemistry:electrochemistry_7b3eb826_b968_493a_8396_cc3a5f09ecb3",
        "Diameter": "emmo:EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6",
        "LowerVoltageLimit": "electrochemistry:electrochemistry_534dd59c_904c_45d9_8550_ae9d2eb6bbc9",
        "MaximumDischargingTemperature": "electrochemistry:electrochemistry_de612af2_a029_4a02_8090_4a75ab13271d",
        "MinimumDischargingTemperature": "electrochemistry:electrochemistry_2a1de79f_e927_45a2_9619_3799a0d61e9b",
        "MassLoading": "electrochemistry:electrochemistry_c955c089_6ee1_41a2_95fc_d534c5cfd3d5",
        "EnergyDensity": "electrochemistry:electrochemistry_4aa1b96e_44a0_4b1a_a0ac_723d0223d80b",
        "Thickness": "emmo:EMMO_43003c86_9d15_433b_9789_ee2940920656",
        "Height": "emmo:EMMO_08bcf1d6_e719_46c8_bb21_24bc9bf34dba",
        "ElectricImpedance": "emmo:EMMO_79a02de5_b884_4eab_bc18_f67997d597a2",
        "InitialCoulombicEfficiency": "electrochemistry:electrochemistry_469b9516_a96d_4aa2_b8e5_05ae982e2084",
        "InternalResistance": "electrochemistry:electrochemistry_9bf40017_3f58_4030_ada7_cb37a3dfda2d",
        "Length": "emmo:EMMO_cd2cd0de_e0cc_4ef1_b27e_2e88db027bac",
        "MaximumStorageTemperature": "electrochemistry:electrochemistry_0ea4d188_9701_4699_a5ca_812a98a9afa7",
        "MinimumCapacity": "electrochemistry:electrochemistry_d3c0078e_c1d3_461e_873d_e5c3adf441c5",
        "MinimumStorageTemperature": "electrochemistry:electrochemistry_0ddfd57a_d338_4690_be45_b26884ed6302",
        "NPRatio": "electrochemistry:electrochemistry_05012606_b93d_4016_bbc7_8a927efdf723",
        "NominalCapacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "NominalVoltage": "electrochemistry:electrochemistry_639b844a_e801_436b_985d_28926129ead6",
        "PowerDensity": "electrochemistry:electrochemistry_a7eb870c_4ef7_4ccd_85e8_4b7b726d7a2a",
        "CalenderedDensity": "electrochemistry:electrochemistry_520995f8_ec9c_4b3c_bb64_2cd691947379",
        "MaximumPulseChargingCurrent": "electrochemistry:electrochemistry_1b2a7137_64d4_483a_8437_dcb3bedcb6da",
        "MaximumPulseDischargingCurrent": "electrochemistry:electrochemistry_3e54f9e3_a31d_4821_9bfb_ef953a42c35b",
        "AreicCapacity": "electrochemistry:electrochemistry_bcb33f7e_5573_4bc2_b636_4ea313a9dd3a",
        "RatedCapacity": "electrochemistry:electrochemistry_9b3b4668_0795_4a35_9965_2af383497a26",
        "DischargingSpecificCapacity": "electrochemistry:electrochemistry_884650fd_6cc6_4ec6_8264_c18fbe6b90ee",
        "SelfDischargeRate": "electrochemistry:electrochemistry_c3e97d58_1854_4c23_bb42_d2972172865e",
        "SpecificEnergy": "emmo:EMMO_e218c625_6a39_47a9_8d08_a2ef41c152a9",
        "SpecificPower": "electrochemistry:electrochemistry_c762a928_5a74_46fd_9929_4ac2d7a3a8d7",
        "StateOfHealth": "electrochemistry:electrochemistry_a7a4614f_2426_46f3_8475_cda4a9fabfce",
        "TheoreticalCapacity": "electrochemistry:electrochemistry_372c89d0_adab_4585_9662_33c912acef23",
        "Tortuosity": "emmo:EMMO_c413d96f_c57b_4c70_9ac1_312db6c009a8",
        "Width": "emmo:EMMO_e4de48b1_dabb_4490_ac2b_040f926c64f0",
        "AmpereHour": "emmo:AmpereHour",
        "MilliAmpereHour": "emmo:MilliAmpereHour",
        "Volt": "emmo:Volt",
        "MilliVolt": "emmo:MilliVolt",
        "Ampere": "emmo:Ampere",
        "MilliAmpere": "emmo:MilliAmpere",
        "Watt": "emmo:Watt",
        "WattHour": "emmo:WattHour",
        "KiloWattHour": "emmo:KiloWattHour",
        "MilliOhm": "emmo:MilliOhm",
        "DegreeCelsius": "emmo:DegreeCelsius",
        "Kelvin": "emmo:Kelvin",
        "Gram": "emmo:Gram",
        "Kilogram": "emmo:Kilogram",
        "MilliMetre": "emmo:MilliMetre",
        "CentiMetre": "emmo:CentiMetre",
        "Metre": "emmo:Metre",
        "Litre": "emmo:Litre",
        "MilliLitre": "emmo:MilliLitre",
        "UnitOne": "emmo:EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
        "Hour": "emmo:Hour",
        "Minute": "emmo:Minute",
        "Second": "emmo:Second",
        "WattHourPerKilogram": "emmo:WattHourPerKilogram",
        "WattHourPerLitre": "emmo:WattHourPerLitre",
        "WattPerKilogram": "emmo:WattPerKilogram",
        "WattPerLitre": "http://qudt.org/vocab/unit/W-PER-L",
        "WeightPercent": "electrochemistry:electrochemistry_2c0e66c8_d58d_44b2_b0ce_ba55194bd505",
        "VolumePercent": "electrochemistry:electrochemistry_db37b358_b2f0_4e06_b6ae_8c56c8fbb6ba",
        "MicroMetre": "emmo:MicroMetre",
        "MilliGramPerSquareCentiMetre": "emmo:MilliGramPerSquareCentiMetre",
        "GramPerCubicCentiMetre": "emmo:GramPerCubicCentiMetre",
        "MolePerLitre": "emmo:MolePerLitre",
        "LithiumManganeseDioxideBattery": "battery:battery_05adf5d2_0fbd_4c58_906e_4b875a7f2363",
        "LithiumIonIronPhosphateBattery": "battery:battery_04a4e5a4_e6fd_43af_b1ca_4a16d5f8886c",
        "LithiumIronPhosphateElectrode": "electrochemistry:electrochemistry_1d0f15cb_d6b5_4c27_89ca_fe78adc1ce5b",
        "hasPositiveElectrode": {
          "@id": "electrochemistry:electrochemistry_8e9cf965_9f92_46e8_b678_b50410ce3616",
          "@type": "@id"
        },
        "LithiumIonNickelManganeseCobaltOxideBattery": "battery:battery_834095fa_f684_4368_a7ce_853579a1362a",
        "LithiumNickelManganeseCobaltOxideElectrode": "electrochemistry:electrochemistry_b3eb8c65_5644_45e3_9e17_0be6277c7962",
        "LithiumIonNickelCobaltAluminiumOxideBattery": "battery:battery_217e44ed_efd9_4b9e_9cb4_1f7488d996b2",
        "LithiumIonCobaltOxideBattery": "battery:battery_4f0b1312_da2f_4039_a06d_d571ce51f835",
        "LithiumCobaltOxideElectrode": "electrochemistry:electrochemistry_fd7caf39_0a43_4fbf_958e_a62067aa9007",
        "ManganeseDioxideElectrode": "electrochemistry:electrochemistry_ca4d9efc_70be_441e_b358_d927aa4c36c4",
        "LithiumIonManganeseIronPhosphateBattery": "battery:battery_c429bb30_50d6_4cec_ae7e_279f59c36ccd",
        "LithiumManganeseIronPhosphateElectrode": "electrochemistry:electrochemistry_9109b3f6_112b_456d_ae45_b82c271c656b",
        "LithiumIonManganeseOxideBattery": "battery:battery_45804eeb_fba3_49dd_ae79_6b4e958d6e09",
        "LithiumManganeseOxideElectrode": "electrochemistry:electrochemistry_c231227b_f318_4e59_ad90_6e91072903ed",
        "LithiumIonGraphiteBattery": "battery:battery_2018e0da_4c25_46e9_83db_38431fc81ce0",
        "GraphiteElectrode": "electrochemistry:electrochemistry_c831d963_629a_41ab_850f_97fb6841b739",
        "hasNegativeElectrode": {
          "@id": "electrochemistry:electrochemistry_5d299271_3f68_494f_ab96_3db9acdd3138",
          "@type": "@id"
        },
        "SiliconGraphiteElectrode": "electrochemistry:electrochemistry_e8c39ecc_29d1_4172_996e_d5b05dc88015",
        "SiliconBasedElectrode": "electrochemistry:electrochemistry_79e12290_d1e5_4c41_916c_18f1e4d7fb51",
        "HardCarbonElectrode": "electrochemistry:electrochemistry_6235cc7c_2eee_432a_93af_47d7e05db007",
        "LithiumElectrode": "electrochemistry:electrochemistry_55775b50_b9d9_4d68_8cb5_38fcd7b9b54d",
        "LithiumIonTitanateBattery": "battery:battery_fd811dc3_8c37_4741_a099_78e26e4110ef",
        "LithiumTitanateElectrode": "electrochemistry:electrochemistry_6d0fe07e_a629_479c_ab24_2846f209bb0b",
        "RealData": "emmo:EMMO_18d180e4_5e3e_42f7_820c_e08951223486",
        "ConventionalProperty": "emmo:EMMO_d8aa8e1f_b650_416d_88a0_5118de945456",
        "MeasuredProperty": "emmo:EMMO_873b0ab3_88e6_4054_b901_5531e01f14a4",
        "NominalProperty": "emmo:EMMO_909415d1_7c43_4d5e_bbeb_7e1910159f66",
        "hasMeasurementParameter": {
          "@id": "https://w3id.org/emmo/domain/characterisation-methodology/chameo#hasMeasurementParameter",
          "@type": "@id"
        },
        "hasElectrolyte": {
          "@id": "electrochemistry:electrochemistry_3bd08946_4e81_455d_9fca_dc7a5ead9315",
          "@type": "@id"
        },
        "hasSeparator": {
          "@id": "electrochemistry:electrochemistry_9317be62_e602_4343_a72d_02c87201b9f6",
          "@type": "@id"
        },
        "hasCoating": {
          "@id": "electrochemistry:electrochemistry_4df9926d_d4f2_4955_93f3_a03c5edc5383",
          "@type": "@id"
        },
        "hasCurrentCollector": {
          "@id": "electrochemistry:electrochemistry_cc8c2c5d_cf3d_444d_a7e8_44ec4c06a88e",
          "@type": "@id"
        },
        "hasActiveMaterial": {
          "@id": "electrochemistry:electrochemistry_860aa941_5ff9_4452_8a16_7856fad07bee",
          "@type": "@id"
        },
        "hasBinder": {
          "@id": "electrochemistry:electrochemistry_056a5fab_3d99_46bd_8eb1_6e89a368e1a7",
          "@type": "@id"
        },
        "hasConductiveAdditive": {
          "@id": "electrochemistry:electrochemistry_c830c469_60c3_4380_8382_4df13a32a1e7",
          "@type": "@id"
        },
        "hasSolute": {
          "@id": "electrochemistry:electrochemistry_8784ef24_320b_4a3d_b200_654aec6c271c",
          "@type": "@id"
        },
        "hasSolvent": {
          "@id": "electrochemistry:electrochemistry_808e94df_e002_4e64_a6db_182ed75078c6",
          "@type": "@id"
        },
        "hasAdditive": {
          "@id": "electrochemistry:electrochemistry_7df82c48_b599_4b02_bef0_9facc9c39410",
          "@type": "@id"
        },
        "hasCase": {
          "@id": "electrochemistry:electrochemistry_3dcfe33d_6825_43c0_a798_68e871a68d39",
          "@type": "@id"
        },
        "hasConstituent": {
          "@id": "emmo:EMMO_dba27ca1_33c9_4443_a912_1519ce4c39ec",
          "@type": "@id"
        },
        "Electrode": "electrochemistry:electrochemistry_0f007072_a8dd_4798_b865_1bf9363be627",
        "ElectrodeCoating": "electrochemistry:electrochemistry_403c300e_09b9_400b_943b_04e82a3cfb56",
        "CurrentCollector": "electrochemistry:electrochemistry_212af058_3bbb_419f_a9c6_90ba9ebb3706",
        "CurrentCollectorTab": "electrochemistry:electrochemistry_6913368b_39cf_42da_ac51_c1b508930ac5",
        "Separator": "electrochemistry:electrochemistry_331e6cca_f260_4bf8_af55_35304fe1bbe0",
        "ElectrolyteSolution": "electrochemistry:electrochemistry_fa22874b_76a9_4043_8b8f_6086c88746de",
        "ActiveMaterial": "electrochemistry:electrochemistry_79d1b273_58cd_4be6_a250_434817f7c261",
        "Binder": "electrochemistry:electrochemistry_68eb5e35_5bd8_47b1_9b7f_f67224fa291e",
        "ConductiveAdditive": "electrochemistry:electrochemistry_82fef384_8eec_4765_b707_5397054df594",
        "Solute": "https://w3id.org/emmo/domain/chemical-substance#substance_3899a9c9_9b34_443e_8ce6_0257589bb38a",
        "Solvent": "https://w3id.org/emmo/domain/chemical-substance#substance_0f2f65a7_5cc4_4c86_a4d0_676771c646f1",
        "ElectrolyteAdditive": "electrochemistry:electrochemistry_554286d4_1f46_44c0_bebc_4ddae00dbce1",
        "Case": "electrochemistry:electrochemistry_1aec4cc0_82d5_4042_a657_ed7fe291c3d8",
        "Terminal": "electrochemistry:electrochemistry_3f70e5c5_67f0_483e_998b_b83b7739c4bc",
        "ElectrodeStack": "electrochemistry:electrochemistry_27662d03_1bcf_4393_a239_32e31b760839",
        "BatteryCycler": "battery:battery_23e6170d_a70b_4de9_a4db_458e24a327ac",
        "Potentiostat": "electrochemistry:electrochemistry_a9fc3f77_e48e_4bce_b118_044d608722f6",
        "Galvanostat": "electrochemistry:electrochemistry_22725105_c941_4b14_a4a2_fcb627958607",
        "MeasuringInstrument": "emmo:EMMO_f2d5d3ad_2e00_417f_8849_686f3988d929",
        "LithiumIronPhosphate": "https://w3id.org/emmo/domain/chemical-substance#substance_aa8e9cc4_5f66_4307_b1c8_26fac7653a90",
        "LithiumNickelManganeseCobaltOxide": "https://w3id.org/emmo/domain/chemical-substance#substance_3ac62305_acd6_4312_9e31_4f824bd2530d",
        "LithiumNickelCobaltAluminiumOxide": "https://w3id.org/emmo/domain/chemical-substance#substance_cd17ca33_ae3d_4738_8930_547673bf6c1f",
        "LithiumCobaltOxide": "https://w3id.org/emmo/domain/chemical-substance#substance_4c62d334_a124_40b3_9fd1_fe713d01a6af",
        "LithiumNickelManganeseOxide": "https://w3id.org/emmo/domain/chemical-substance#substance_f3e7979a_e3ef_450a_8762_7d8778afe478",
        "Graphite": "https://w3id.org/emmo/domain/chemical-substance#substance_d53259a7_0d9c_48b9_a6c1_4418169df303",
        "HardCarbon": "https://w3id.org/emmo/domain/chemical-substance#substance_5cee19d2_f916_4264_a8ed_efed13a808d2",
        "Silicon": "https://w3id.org/emmo/domain/chemical-substance#substance_68c0876b_cb62_41cd_846d_95cc9d9a8733",
        "SiliconOxide": "https://w3id.org/emmo/domain/chemical-substance#substance_0160f86c_e567_40d4_a457_25cf170e7ef2",
        "CarbonBlack": "https://w3id.org/emmo/domain/chemical-substance#substance_0a5cb747_60cf_4929_a54a_712c54b49f3b",
        "PolyvinylideneFluoride": "https://w3id.org/emmo/domain/chemical-substance#substance_f2e48e9e_f774_4f42_939f_1fe522efb7c8",
        "CarboxymethylCellulose": "https://w3id.org/emmo/domain/chemical-substance#substance_d36fbe2f_6b0a_4178_b6ca_7373bdefcb51",
        "StyreneButadiene": "https://w3id.org/emmo/domain/chemical-substance#substance_210edf30_ad63_438c_97db_f817942db49b",
        "LithiumHexafluorophosphate": "https://w3id.org/emmo/domain/chemical-substance#substance_0deb4fe8_b0c0_4e3f_8848_64435e5c0771",
        "EthyleneCarbonate": "https://w3id.org/emmo/domain/chemical-substance#substance_57339d90_0553_4a96_8da9_ff6c3684e226",
        "DimethylCarbonate": "https://w3id.org/emmo/domain/chemical-substance#substance_c4a7d7bd_497e_457e_b858_ff73254266d0",
        "PropyleneCarbonate": "https://w3id.org/emmo/domain/chemical-substance#substance_46e9f253_40cb_4b48_b8d0_0b976ea4e156",
        "FluoroethyleneCarbonate": "https://w3id.org/emmo/domain/chemical-substance#substance_20004d19_02cf_4667_a09f_b5c595b44b1f",
        "VinyleneCarbonate": "https://w3id.org/emmo/domain/chemical-substance#substance_31d0d139_7b45_4d1e_8603_92cc12da2fad",
        "VinylEthyleneCarbonate": "https://w3id.org/emmo/domain/chemical-substance#substance_edef7f16_a517_4577_91b1_a90099869f1b",
        "Polypropylene": "https://w3id.org/emmo/domain/chemical-substance#substance_c5cff8c2_581e_4341_a3e6_8ba8c8ce2d2b",
        "Polyethylene": "https://w3id.org/emmo/domain/chemical-substance#substance_79220ea3_3426_47a0_9b41_33012d565fc2",
        "Aluminium": "https://w3id.org/emmo/domain/chemical-substance#substance_8f7dd877_5ad0_48f1_bbec_84153d8215f4",
        "Copper": "https://w3id.org/emmo/domain/chemical-substance#substance_0993cbab_ff7f_4ec3_8a6c_cd67497d54d9",
        "EthylMethylCarbonate": "https://w3id.org/emmo/domain/chemical-substance#substance_bb20bdea_343c_4911_8c45_37fc1077d22f",
        "LithiumManganeseIronPhosphate": "https://w3id.org/emmo/domain/chemical-substance#substance_40c605fd_4e47_4e90_a055_185f749d834c",
        "Zinc": "https://w3id.org/emmo/domain/chemical-substance#substance_9bd78e1c_a4dc_41b6_8013_adb51df1ffdc",
        "PotassiumHydroxide": "https://w3id.org/emmo/domain/chemical-substance#substance_ccdce7d4_b695_4871_84c2_13679807d077",
        "OrganicElectrolyte": "electrochemistry:electrochemistry_564d31be_91cb_4a8f_8369_2a55f1180499",
        "AqueousElectrolyte": "electrochemistry:electrochemistry_b812e9d0_7c58_4455_b3e7_6847f10c8e8a",
        "IonicLiquidElectrolyte": "electrochemistry:electrochemistry_c3f4b34a_0e2c_46f3_baab_4ebd2682d26f",
        "PolymerElectrolyte": "electrochemistry:electrochemistry_c6d6c0a1_a06b_437a_978f_a469d3071ca9",
        "SolidElectrolyte": "electrochemistry:electrochemistry_0508a114_544a_4f54_a7de_9b947fb4b618",
        "Foil": "electrochemistry:electrochemistry_1d5377a7_9f2b_4fdf_958a_7eeadce158d6",
        "PerforatedFoil": "electrochemistry:electrochemistry_c84a1d8f_e405_42ba_8c80_bbe3b9c6c66a",
        "ExpandedMesh": "electrochemistry:electrochemistry_31b38a1b_5873_454c_ba99_00491497fb43",
        "WovenMesh": "electrochemistry:electrochemistry_3a69a00e_235a_4948_b369_8ac20116c85e",
        "ElectrospunMesh": "electrochemistry:electrochemistry_9e2f4509_e3f1_4bff_a5f4_8792c372e338",
        "Nickel": "https://w3id.org/emmo/domain/chemical-substance#substance_f92b3948_72a5_4662_acf7_5d8dd64e85de",
        "StainlessSteel": "https://w3id.org/emmo/domain/chemical-substance#substance_2cd874c8_f8f0_4794_bba9_d520603ab6bb",
        "Titanium": "https://w3id.org/emmo/domain/chemical-substance#substance_f8d50782_11fa_4188_ba55_d043d2eb597d",
        "Carbon": "https://w3id.org/emmo/domain/chemical-substance#substance_4e5582a6_caec_4917_acad_6f472cd7d831",
        "CoinCase": "electrochemistry:electrochemistry_3979cd56_6256_414d_966c_7f723bf71e37",
        "CylindricalCase": "electrochemistry:electrochemistry_b1cf9fee_2164_4f95_8204_90f717373a8a",
        "PouchCase": "electrochemistry:electrochemistry_74459386_875c_4303_b774_60125b599d06",
        "PrismaticCase": "electrochemistry:electrochemistry_43cd6e14_dd43_41b5_b5b4_344d53841603",
        "CellLid": "electrochemistry:electrochemistry_1e33e37e_d7c9_4701_ba6d_a09456a13aaf",
        "CellCan": "electrochemistry:electrochemistry_4a5660bd_1c1a_40e5_8a41_463c720d3903",
        "Spring": "electrochemistry:electrochemistry_872b11e1_8bb3_4a2a_af90_bbaa0055d01e",
        "Spacer": "electrochemistry:electrochemistry_49909cd1_44f4_41b4_877a_82a52845a5cb",
        "MassFraction": "emmo:EMMO_7c055d65_2929_40e1_af4f_4bf10995ad50",
        "VolumeFraction": "emmo:EMMO_a8eb87b5_4d10_4137_a75c_e04ee59ca095",
        "Porosity": "emmo:EMMO_3a6578ac_aee0_43b9_9bc6_1eb208c8c9a9",
        "AmountConcentration": "emmo:EMMO_d5be1faf_0c56_4f5a_9b78_581e6dee949f",
        "ElectrolyticConductivity": "emmo:EMMO_e6e7277a_1d40_4be5_a3a9_afd3da53d937",
        "DynamicViscosity": "emmo:EMMO_908da3d5_775e_425e_af96_33914618eb66",
        "Density": "emmo:EMMO_06448f64_8db6_4304_8b2c_e785dba82044",
        "CelsiusTemperature": "emmo:EMMO_66bc9029_f473_45ff_bab9_c3509ff37a22",
        "ActiveMassLoading": "electrochemistry:electrochemistry_1eeb0e2a_229a_43f1_b197_348d475067ff",
        "CalenderedCoatingThickness": "electrochemistry:electrochemistry_f9e1c862_c510_4b11_9141_bc91045df817"
      },
      "@type": [
        "BatteryCellSpecification",
        "schema:CreativeWork"
      ],
      "@id": "https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5",
      "schema:identifier": "7d9k-2m4p-8t3x-6nq5",
      "schema:name": "A123 ANR26650M1-B",
      "schema:model": "ANR26650M1-B",
      "schema:manufacturer": {
        "@type": "schema:Organization",
        "schema:name": "A123"
      },
      "schema:url": "https://www.battery-genome.org/registry/spec/7d9k-2m4p-8t3x-6nq5",
      "isDescriptionFor": {
        "@type": [
          "BatteryCell",
          "CylindricalBattery",
          "LithiumIonBattery",
          "LithiumIonIronPhosphateBattery"
        ],
        "skos:prefLabel": "A123 ANR26650M1-B"
      },
      "schema:size": "R26650",
      "schema:productID": "IFpR26650",
      "schema:brand": {
        "@type": "schema:Brand",
        "schema:name": "A123"
      },
      "schema:category": "battery cell",
      "schema:countryOfOrigin": {
        "@type": "schema:Country",
        "schema:name": "United States"
      },
      "schema:releaseDate": "2012-01-01",
      "schema:schemaVersion": "0.1.0",
      "hasProperty": [
        {
          "@type": [
            "NominalCapacity",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "NominalCapacity",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 2.5
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#AmpereHour"
        },
        {
          "@type": [
            "MinimumCapacity",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MinimumCapacity",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 2.4
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#AmpereHour"
        },
        {
          "@type": [
            "NominalVoltage",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "NominalVoltage",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 3.3
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Volt"
        },
        {
          "@type": [
            "InternalResistance",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "InternalResistance",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 6.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#MilliOhm"
        },
        {
          "@type": [
            "Mass",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "Mass",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 76.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Gram"
        },
        {
          "@type": [
            "Diameter",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "Diameter",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 26.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#MilliMetre"
        },
        {
          "@type": [
            "Height",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "Height",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 65.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#MilliMetre"
        },
        {
          "@type": [
            "MaximumPulseChargingCurrent",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MaximumPulseChargingCurrent",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 10.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Ampere"
        },
        {
          "@type": [
            "NominalContinuousChargingCurrent",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "NominalContinuousChargingCurrent",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 2.5
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Ampere"
        },
        {
          "@type": [
            "MaximumContinuousChargingCurrent",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MaximumContinuousChargingCurrent",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 2.5
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Ampere"
        },
        {
          "@type": [
            "MaximumContinuousDischargingCurrent",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MaximumContinuousDischargingCurrent",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 50.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Ampere"
        },
        {
          "@type": [
            "MinimumDischargingTemperature",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MinimumDischargingTemperature",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": -30
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc"
        },
        {
          "@type": [
            "MaximumDischargingTemperature",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MaximumDischargingTemperature",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 55
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc"
        },
        {
          "@type": [
            "MinimumStorageTemperature",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MinimumStorageTemperature",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": -40
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc"
        },
        {
          "@type": [
            "MaximumStorageTemperature",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "MaximumStorageTemperature",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 60
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc"
        },
        {
          "@type": [
            "CycleLife",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "CycleLife",
          "schema:value": ">1000",
          "hasMeasurementUnit": "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"
        }
      ],
      "hasPositiveElectrode": {
        "@type": "LithiumIronPhosphateElectrode"
      },
      "dcterms:source": {
        "@type": "prov:Entity",
        "dcterms:type": "datasheet",
        "prov:generatedAtTime": "2026-01-28T07:33:04+00:00"
      }
    }
  },
  {
    "slug": "test",
    "label": "Test — baseline cycling on a tracked cell",
    "recordType": "test",
    "sourceFile": "examples/test/test-5p7v-2n8k-4m3t-6q9r.json",
    "highlight": "The test points at the physical cell it ran on (prov:used), so every number stays attached to its subject.",
    "record": {
      "schema_version": "0.1.0",
      "test": {
        "id": "https://w3id.org/battinfo/test/5p7v-2n8k-4m3t-6q9r",
        "short_id": "5p7v2n",
        "identifier": "test:5p7v-2n8k-4m3t-6q9r",
        "cell_id": "https://w3id.org/battinfo/cell/3m6k-9t2p-7x4h-9nq8",
        "name": "A123 ANR26650M1-B baseline cycling",
        "description": "Galvanostatic cycling test for one physical cell instance.",
        "kind": "cycling",
        "status": "completed",
        "protocol_name": "0.5C charge/discharge baseline cycling",
        "started_at": 1771718400,
        "ended_at": 1771804800,
        "dataset_ids": [
          "https://w3id.org/battinfo/dataset/1f8r-6v2k-9p4m-3t7x"
        ]
      },
      "provenance": {
        "source_type": "measurement",
        "source_url": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x",
        "source_file": "test-5p7v-2n8k-4m3t-6q9r.json",
        "retrieved_at": 1771804800,
        "workflow_version": "0.2.0",
        "citation": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      },
      "notes": [
        "Explicit test record linking the physical cell instance to its cycling dataset."
      ]
    },
    "jsonld": {
      "@context": {
        "@version": 1.1,
        "battery": "https://w3id.org/emmo/domain/battery#",
        "electrochemistry": "https://w3id.org/emmo/domain/electrochemistry#",
        "emmo": "https://w3id.org/emmo#",
        "battinfo": "https://w3id.org/battinfo/",
        "schema": "https://schema.org/",
        "dcterms": "http://purl.org/dc/terms/",
        "prov": "http://www.w3.org/ns/prov#",
        "dcat": "http://www.w3.org/ns/dcat#",
        "bibo": "http://purl.org/ontology/bibo/",
        "pav": "http://purl.org/pav/",
        "dqv": "http://www.w3.org/ns/dqv#",
        "oa": "http://www.w3.org/ns/oa#",
        "earl": "http://www.w3.org/ns/earl#",
        "spdx": "http://spdx.org/rdf/terms#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "skos": "http://www.w3.org/2004/02/skos/core#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "BatteryCell": "battery:battery_68ed592a_7924_45d0_a108_94d6275d57f0",
        "BatteryCellSpecification": "battery:battery_1cfbba6c_8824_4932_a23e_2141483acef7",
        "CylindricalBattery": "battery:battery_ac604ecd_cc60_4b98_b57c_74cd5d3ccd40",
        "PrismaticBattery": "battery:battery_86c9ca80_de6f_417f_afdc_a7e52fa6322d",
        "PouchCell": "battery:battery_392b3f47_d62a_4bd4_a819_b58b09b8843a",
        "CoinCell": "battery:battery_b7fdab58_6e91_4c84_b097_b06eff86a124",
        "LithiumIonBattery": "battery:battery_96addc62_ea04_449a_8237_4cd541dd8e5f",
        "LithiumMetalBattery": "battery:battery_ada13509_4eed_4e40_a7b1_4cc488144154",
        "SodiumIonBattery": "battery:battery_42329a95_03fe_4ec1_83cb_b7e8ed52f68a",
        "AlkalineZincManganeseDioxideBattery": "battery:battery_b572826a_b4e4_4986_b57d_f7b945061f8b",
        "AlkalineCell": "battery:battery_50b911f7_c903_4700_9764_c308d8a95470",
        "PrimaryBattery": "battery:battery_3b0b0d6e_8b0e_4491_885e_8421d3eb3b69",
        "SecondaryBattery": "battery:battery_efc38420_ecbb_42e4_bb3f_208e7c417098",
        "BatteryTest": "battery:battery_dca7729a_421a_4921_90cf_9692bb9eb081",
        "name": "schema:name",
        "model": "schema:model",
        "manufacturer": "schema:manufacturer",
        "hasProperty": {
          "@id": "emmo:EMMO_e1097637_70d2_4895_973f_2396f04fa204",
          "@type": "@id"
        },
        "hasNumericalPart": {
          "@id": "emmo:EMMO_8ef3cd6d_ae58_4a8d_9fc0_ad8f49015cd0",
          "@type": "@id"
        },
        "hasNumberValue": "emmo:EMMO_faf79f53_749d_40b2_807c_d34244c192f4",
        "hasNumericalValue": "emmo:EMMO_faf79f53_749d_40b2_807c_d34244c192f4",
        "hasMeasurementUnit": {
          "@id": "emmo:EMMO_bed1d005_b04e_4a90_94cf_02bc678a8569",
          "@type": "@id"
        },
        "isDescriptionFor": {
          "@id": "emmo:EMMO_f702bad4_fc77_41f0_a26d_79f6444fd4f3",
          "@type": "@id"
        },
        "hasDescription": {
          "@id": "emmo:EMMO_c58c799e_cc6c_4310_a3f1_78da70705b2a",
          "@type": "@id"
        },
        "hasTestObject": {
          "@id": "battery:battery_da3b3f28_aaad_4d67_b674_df47e109fb8b",
          "@type": "@id"
        },
        "hasTestEquipment": {
          "@id": "battery:battery_df4ff8f1_2cf2_444a_9498_23f533bd295c",
          "@type": "@id"
        },
        "hasOutput": {
          "@id": "emmo:EMMO_c4bace1d_4db0_4cd3_87e9_18122bae2840",
          "@type": "@id"
        },
        "id": "schema:productID",
        "nominal_capacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "minimum_capacity": "electrochemistry:electrochemistry_d3c0078e_c1d3_461e_873d_e5c3adf441c5",
        "rated_capacity": "electrochemistry:electrochemistry_9b3b4668_0795_4a35_9965_2af383497a26",
        "typical_capacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "nominal_voltage": "electrochemistry:electrochemistry_639b844a_e801_436b_985d_28926129ead6",
        "charging_voltage": "electrochemistry:electrochemistry_79a9e1be_35b0_4c3c_8087_b5f967ca0e87",
        "discharging_cutoff_voltage": "electrochemistry:electrochemistry_534dd59c_904c_45d9_8550_ae9d2eb6bbc9",
        "charging_cutoff_voltage": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "upper_voltage_limit": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "maximum_continuous_charging_current": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "nominal_continuous_charging_current": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "maximum_pulse_charging_current": "electrochemistry:electrochemistry_1b2a7137_64d4_483a_8437_dcb3bedcb6da",
        "maximum_continuous_discharging_current": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "nominal_continuous_discharging_current": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "maximum_pulse_discharging_current": "electrochemistry:electrochemistry_3e54f9e3_a31d_4821_9bfb_ef953a42c35b",
        "nominal_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "typical_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "rated_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "certified_usable_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "power_capability": "battinfo:powerCapability",
        "maximum_power": "battinfo:maximumPower",
        "specific_energy": "emmo:EMMO_e218c625_6a39_47a9_8d08_a2ef41c152a9",
        "energy_density": "electrochemistry:electrochemistry_4aa1b96e_44a0_4b1a_a0ac_723d0223d80b",
        "specific_power": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_c762a928_5a74_46fd_9929_4ac2d7a3a8d7",
        "power_density": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_a7eb870c_4ef7_4ccd_85e8_4b7b726d7a2a",
        "power_energy_ratio": "battinfo:powerEnergyRatio",
        "internal_resistance": "electrochemistry:electrochemistry_9bf40017_3f58_4030_ada7_cb37a3dfda2d",
        "dc_internal_resistance": "electrochemistry:electrochemistry_7b3eb826_b968_493a_8396_cc3a5f09ecb3",
        "ac_internal_resistance": "electrochemistry:electrochemistry_964cd426_f3cf_4a52_8c5d_0490cf48edb5",
        "impedance": "emmo:EMMO_79a02de5_b884_4eab_bc18_f67997d597a2",
        "round_trip_energy_efficiency": "battinfo:roundTripEnergyEfficiency",
        "round_trip_energy_efficiency_50pct": "battinfo:roundTripEnergyEfficiency50Pct",
        "initial_coulombic_efficiency": "electrochemistry:electrochemistry_469b9516_a96d_4aa2_b8e5_05ae982e2084",
        "mass": "emmo:EMMO_ed4af7ae_63a2_497e_bb88_2309619ea405",
        "diameter": "emmo:EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6",
        "height": "emmo:EMMO_08bcf1d6_e719_46c8_bb21_24bc9bf34dba",
        "width": "emmo:EMMO_e4de48b1_dabb_4490_ac2b_040f926c64f0",
        "length": "emmo:EMMO_cd2cd0de_e0cc_4ef1_b27e_2e88db027bac",
        "thickness": "emmo:EMMO_43003c86_9d15_433b_9789_ee2940920656",
        "volume": "emmo:EMMO_f1a51559_aa3d_43a0_9327_918039f0dfed",
        "maximum_charging_temperature": "electrochemistry:electrochemistry_4a354510_4dc2_4803_8845_f4024a1a7260",
        "minimum_charging_temperature": "electrochemistry:electrochemistry_b90b1ad7_b9a8_44df_ad45_bfd25aac2e49",
        "maximum_discharging_temperature": "electrochemistry:electrochemistry_de612af2_a029_4a02_8090_4a75ab13271d",
        "minimum_discharging_temperature": "electrochemistry:electrochemistry_2a1de79f_e927_45a2_9619_3799a0d61e9b",
        "maximum_storage_temperature": "electrochemistry:electrochemistry_0ea4d188_9701_4699_a5ca_812a98a9afa7",
        "minimum_storage_temperature": "electrochemistry:electrochemistry_0ddfd57a_d338_4690_be45_b26884ed6302",
        "operating_temperature_min": "battinfo:operatingTemperatureMin",
        "operating_temperature_max": "battinfo:operatingTemperatureMax",
        "cycle_life": "electrochemistry:electrochemistry_ae782b14_88ce_4cdd_9418_12aca00be937",
        "cycle_life_c_rate": "battinfo:cycleLifeCRate",
        "calendar_life": "electrochemistry:electrochemistry_743c71a3_b80c_42e3_92fa_13a67b8167df",
        "capacity_fade": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_e3d3d21c_cb9a_498c_bdb0_63c964f0d3c6",
        "capacity_threshold_exhaustion": "battinfo:capacityThresholdExhaustion",
        "charging_time": "battinfo:chargingTime",
        "self_discharge_rate": "electrochemistry:electrochemistry_c3e97d58_1854_4c23_bb42_d2972172865e",
        "state_of_health": "electrochemistry:electrochemistry_a7a4614f_2426_46f3_8475_cda4a9fabfce",
        "source_type": "dcterms:type",
        "source_url": {
          "@id": "prov:hadPrimarySource",
          "@type": "@id"
        },
        "citation": "dcterms:bibliographicCitation",
        "citation_doi": "bibo:doi",
        "retrieved_at": "prov:generatedAtTime",
        "workflow_version": "pav:version",
        "curated_by": "dcterms:contributor",
        "protocol_name": "schema:name",
        "protocol_url": "schema:url",
        "V": "emmo:Volt",
        "mV": "emmo:MilliVolt",
        "kV": "emmo:KiloVolt",
        "Ah": "emmo:AmpereHour",
        "mAh": "emmo:MilliAmpereHour",
        "A": "emmo:Ampere",
        "mA": "emmo:MilliAmpere",
        "W": "emmo:Watt",
        "kW": "emmo:KiloWatt",
        "Wh": "emmo:WattHour",
        "kWh": "emmo:KiloWattHour",
        "MWh": "emmo:MegaWattHour",
        "Ohm": "emmo:Ohm",
        "mOhm": "emmo:MilliOhm",
        "mohm": "emmo:MilliOhm",
        "degC": "emmo:EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc",
        "K": "emmo:Kelvin",
        "g": "emmo:Gram",
        "kg": "emmo:Kilogram",
        "mg": "emmo:MilliGram",
        "mm": "emmo:MilliMetre",
        "cm": "emmo:CentiMetre",
        "m": "emmo:Metre",
        "L": "emmo:Litre",
        "mL": "emmo:MilliLitre",
        "cm3": "emmo:CubicCentiMetre",
        "h": "emmo:Hour",
        "min": "emmo:Minute",
        "s": "emmo:Second",
        "1": "emmo:EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
        "%": "emmo:Percent",
        "license": {
          "@id": "dcterms:license",
          "@type": "@id"
        },
        "created_at": {
          "@id": "dcterms:created",
          "@type": "xsd:dateTime"
        },
        "modified_at": {
          "@id": "dcterms:modified",
          "@type": "xsd:dateTime"
        }
      },
      "@type": [
        "BatteryTest",
        "schema:Action",
        "prov:Activity"
      ],
      "@id": "https://w3id.org/battinfo/test/5p7v-2n8k-4m3t-6q9r",
      "schema:name": "A123 ANR26650M1-B baseline cycling",
      "schema:additionalType": "cycling",
      "schema:measurementTechnique": "0.5C charge/discharge baseline cycling",
      "schema:actionStatus": "completed",
      "hasTestObject": {
        "@id": "https://w3id.org/battinfo/cell/3m6k-9t2p-7x4h-9nq8"
      },
      "schema:result": [
        {
          "@id": "https://w3id.org/battinfo/dataset/1f8r-6v2k-9p4m-3t7x"
        }
      ],
      "dcterms:source": {
        "@type": "prov:Entity",
        "dcterms:type": "measurement",
        "prov:hadPrimarySource": {
          "@id": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
        },
        "prov:generatedAtTime": "2026-02-23T00:00:00+00:00",
        "dcterms:bibliographicCitation": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      }
    }
  },
  {
    "slug": "dataset",
    "label": "Dataset — the files a test produced",
    "recordType": "dataset",
    "sourceFile": "examples/dataset/dataset-1f8r-6v2k-9p4m-3t7x.json",
    "highlight": "Datasets are DCAT: catalogable, with distributions and checksums — the shape data portals already understand.",
    "record": {
      "schema_version": "0.2.0",
      "dataset": {
        "id": "https://w3id.org/battinfo/dataset/1f8r-6v2k-9p4m-3t7x",
        "short_id": "1f8r6v",
        "identifier": "doi:10.5281/zenodo.1234567",
        "name": "Cell cycling run for BattINFO cell 3m6k9t",
        "description": "Raw cycling and metadata export for one physical cell.",
        "access_url": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x",
        "same_as": [
          "https://doi.org/10.5281/zenodo.1234567"
        ],
        "license": "https://creativecommons.org/licenses/by/4.0/",
        "version": "1.0.0",
        "keywords": [
          "battery cycling",
          "time series",
          "lithium-ion"
        ],
        "creators": [
          {
            "type": "Organization",
            "name": "BattINFO Maintainers"
          }
        ],
        "publisher": {
          "type": "Organization",
          "name": "BattINFO"
        },
        "citations": [
          {
            "kind": "dataset",
            "url": "https://doi.org/10.5281/zenodo.1234567",
            "doi": "10.5281/zenodo.1234567",
            "citation_key": "example_dataset_2026"
          }
        ],
        "about": [
          "https://w3id.org/battinfo/cell/3m6k-9t2p-7x4h-9nq8",
          "https://w3id.org/battinfo/test/5p7v-2n8k-4m3t-6q9r"
        ],
        "measurement_techniques": [
          "cycling"
        ],
        "measurement_methods": [
          "galvanostatic cycling"
        ],
        "variable_measured": [
          {
            "name": "voltage",
            "unit_text": "V"
          },
          {
            "name": "current",
            "unit_text": "A"
          },
          {
            "name": "capacity",
            "unit_text": "Ah"
          }
        ],
        "is_accessible_for_free": true,
        "in_language": "en",
        "created_at": 1771718400,
        "modified_at": 1771718400,
        "published_at": 1771718400,
        "distributions": [
          {
            "type": "DataDownload",
            "name": "Raw cycling HDF5 archive",
            "content_url": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x/raw.h5",
            "encoding_format": "application/x-hdf5",
            "checksum": {
              "algorithm": "sha256",
              "value": "8fbf34bd0f8a0caef6f5ce6cc1f8e6a2d8f0123982fc624d6f7f3f7e27b95a89"
            },
            "access_level": "open"
          }
        ]
      },
      "provenance": {
        "source_type": "measurement",
        "source_name": "Example Lab Data Portal",
        "source_url": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x",
        "source_file": "dataset-1f8r-6v2k-9p4m-3t7x.json",
        "source_dataset_key": "example-0001",
        "ingest_status": "ready",
        "quality_flags": [],
        "retrieved_at": 1771718400,
        "curated_by": "BattINFO Maintainers",
        "workflow_version": "0.2.0",
        "citation": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      },
      "notes": [
        "Schema.org-first dataset record with BattINFO battery extensions.",
        "Used as a canonical example for dataset ingestion and linking workflows."
      ]
    },
    "jsonld": {
      "@context": {
        "@version": 1.1,
        "battery": "https://w3id.org/emmo/domain/battery#",
        "electrochemistry": "https://w3id.org/emmo/domain/electrochemistry#",
        "emmo": "https://w3id.org/emmo#",
        "battinfo": "https://w3id.org/battinfo/",
        "schema": "https://schema.org/",
        "dcterms": "http://purl.org/dc/terms/",
        "prov": "http://www.w3.org/ns/prov#",
        "dcat": "http://www.w3.org/ns/dcat#",
        "bibo": "http://purl.org/ontology/bibo/",
        "pav": "http://purl.org/pav/",
        "dqv": "http://www.w3.org/ns/dqv#",
        "oa": "http://www.w3.org/ns/oa#",
        "earl": "http://www.w3.org/ns/earl#",
        "spdx": "http://spdx.org/rdf/terms#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "skos": "http://www.w3.org/2004/02/skos/core#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "BatteryCell": "battery:battery_68ed592a_7924_45d0_a108_94d6275d57f0",
        "BatteryCellSpecification": "battery:battery_1cfbba6c_8824_4932_a23e_2141483acef7",
        "CylindricalBattery": "battery:battery_ac604ecd_cc60_4b98_b57c_74cd5d3ccd40",
        "PrismaticBattery": "battery:battery_86c9ca80_de6f_417f_afdc_a7e52fa6322d",
        "PouchCell": "battery:battery_392b3f47_d62a_4bd4_a819_b58b09b8843a",
        "CoinCell": "battery:battery_b7fdab58_6e91_4c84_b097_b06eff86a124",
        "LithiumIonBattery": "battery:battery_96addc62_ea04_449a_8237_4cd541dd8e5f",
        "LithiumMetalBattery": "battery:battery_ada13509_4eed_4e40_a7b1_4cc488144154",
        "SodiumIonBattery": "battery:battery_42329a95_03fe_4ec1_83cb_b7e8ed52f68a",
        "AlkalineZincManganeseDioxideBattery": "battery:battery_b572826a_b4e4_4986_b57d_f7b945061f8b",
        "AlkalineCell": "battery:battery_50b911f7_c903_4700_9764_c308d8a95470",
        "PrimaryBattery": "battery:battery_3b0b0d6e_8b0e_4491_885e_8421d3eb3b69",
        "SecondaryBattery": "battery:battery_efc38420_ecbb_42e4_bb3f_208e7c417098",
        "BatteryTest": "battery:battery_dca7729a_421a_4921_90cf_9692bb9eb081",
        "name": "schema:name",
        "model": "schema:model",
        "manufacturer": "schema:manufacturer",
        "hasProperty": {
          "@id": "emmo:EMMO_e1097637_70d2_4895_973f_2396f04fa204",
          "@type": "@id"
        },
        "hasNumericalPart": {
          "@id": "emmo:EMMO_8ef3cd6d_ae58_4a8d_9fc0_ad8f49015cd0",
          "@type": "@id"
        },
        "hasNumberValue": "emmo:EMMO_faf79f53_749d_40b2_807c_d34244c192f4",
        "hasNumericalValue": "emmo:EMMO_faf79f53_749d_40b2_807c_d34244c192f4",
        "hasMeasurementUnit": {
          "@id": "emmo:EMMO_bed1d005_b04e_4a90_94cf_02bc678a8569",
          "@type": "@id"
        },
        "isDescriptionFor": {
          "@id": "emmo:EMMO_f702bad4_fc77_41f0_a26d_79f6444fd4f3",
          "@type": "@id"
        },
        "hasDescription": {
          "@id": "emmo:EMMO_c58c799e_cc6c_4310_a3f1_78da70705b2a",
          "@type": "@id"
        },
        "hasTestObject": {
          "@id": "battery:battery_da3b3f28_aaad_4d67_b674_df47e109fb8b",
          "@type": "@id"
        },
        "hasTestEquipment": {
          "@id": "battery:battery_df4ff8f1_2cf2_444a_9498_23f533bd295c",
          "@type": "@id"
        },
        "hasOutput": {
          "@id": "emmo:EMMO_c4bace1d_4db0_4cd3_87e9_18122bae2840",
          "@type": "@id"
        },
        "id": "schema:productID",
        "nominal_capacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "minimum_capacity": "electrochemistry:electrochemistry_d3c0078e_c1d3_461e_873d_e5c3adf441c5",
        "rated_capacity": "electrochemistry:electrochemistry_9b3b4668_0795_4a35_9965_2af383497a26",
        "typical_capacity": "electrochemistry:electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
        "nominal_voltage": "electrochemistry:electrochemistry_639b844a_e801_436b_985d_28926129ead6",
        "charging_voltage": "electrochemistry:electrochemistry_79a9e1be_35b0_4c3c_8087_b5f967ca0e87",
        "discharging_cutoff_voltage": "electrochemistry:electrochemistry_534dd59c_904c_45d9_8550_ae9d2eb6bbc9",
        "charging_cutoff_voltage": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "upper_voltage_limit": "electrochemistry:electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
        "maximum_continuous_charging_current": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "nominal_continuous_charging_current": "electrochemistry:electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78",
        "maximum_pulse_charging_current": "electrochemistry:electrochemistry_1b2a7137_64d4_483a_8437_dcb3bedcb6da",
        "maximum_continuous_discharging_current": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "nominal_continuous_discharging_current": "electrochemistry:electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5",
        "maximum_pulse_discharging_current": "electrochemistry:electrochemistry_3e54f9e3_a31d_4821_9bfb_ef953a42c35b",
        "nominal_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "typical_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "rated_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "certified_usable_energy": "electrochemistry:electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d",
        "power_capability": "battinfo:powerCapability",
        "maximum_power": "battinfo:maximumPower",
        "specific_energy": "emmo:EMMO_e218c625_6a39_47a9_8d08_a2ef41c152a9",
        "energy_density": "electrochemistry:electrochemistry_4aa1b96e_44a0_4b1a_a0ac_723d0223d80b",
        "specific_power": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_c762a928_5a74_46fd_9929_4ac2d7a3a8d7",
        "power_density": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_a7eb870c_4ef7_4ccd_85e8_4b7b726d7a2a",
        "power_energy_ratio": "battinfo:powerEnergyRatio",
        "internal_resistance": "electrochemistry:electrochemistry_9bf40017_3f58_4030_ada7_cb37a3dfda2d",
        "dc_internal_resistance": "electrochemistry:electrochemistry_7b3eb826_b968_493a_8396_cc3a5f09ecb3",
        "ac_internal_resistance": "electrochemistry:electrochemistry_964cd426_f3cf_4a52_8c5d_0490cf48edb5",
        "impedance": "emmo:EMMO_79a02de5_b884_4eab_bc18_f67997d597a2",
        "round_trip_energy_efficiency": "battinfo:roundTripEnergyEfficiency",
        "round_trip_energy_efficiency_50pct": "battinfo:roundTripEnergyEfficiency50Pct",
        "initial_coulombic_efficiency": "electrochemistry:electrochemistry_469b9516_a96d_4aa2_b8e5_05ae982e2084",
        "mass": "emmo:EMMO_ed4af7ae_63a2_497e_bb88_2309619ea405",
        "diameter": "emmo:EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6",
        "height": "emmo:EMMO_08bcf1d6_e719_46c8_bb21_24bc9bf34dba",
        "width": "emmo:EMMO_e4de48b1_dabb_4490_ac2b_040f926c64f0",
        "length": "emmo:EMMO_cd2cd0de_e0cc_4ef1_b27e_2e88db027bac",
        "thickness": "emmo:EMMO_43003c86_9d15_433b_9789_ee2940920656",
        "volume": "emmo:EMMO_f1a51559_aa3d_43a0_9327_918039f0dfed",
        "maximum_charging_temperature": "electrochemistry:electrochemistry_4a354510_4dc2_4803_8845_f4024a1a7260",
        "minimum_charging_temperature": "electrochemistry:electrochemistry_b90b1ad7_b9a8_44df_ad45_bfd25aac2e49",
        "maximum_discharging_temperature": "electrochemistry:electrochemistry_de612af2_a029_4a02_8090_4a75ab13271d",
        "minimum_discharging_temperature": "electrochemistry:electrochemistry_2a1de79f_e927_45a2_9619_3799a0d61e9b",
        "maximum_storage_temperature": "electrochemistry:electrochemistry_0ea4d188_9701_4699_a5ca_812a98a9afa7",
        "minimum_storage_temperature": "electrochemistry:electrochemistry_0ddfd57a_d338_4690_be45_b26884ed6302",
        "operating_temperature_min": "battinfo:operatingTemperatureMin",
        "operating_temperature_max": "battinfo:operatingTemperatureMax",
        "cycle_life": "electrochemistry:electrochemistry_ae782b14_88ce_4cdd_9418_12aca00be937",
        "cycle_life_c_rate": "battinfo:cycleLifeCRate",
        "calendar_life": "electrochemistry:electrochemistry_743c71a3_b80c_42e3_92fa_13a67b8167df",
        "capacity_fade": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_e3d3d21c_cb9a_498c_bdb0_63c964f0d3c6",
        "capacity_threshold_exhaustion": "battinfo:capacityThresholdExhaustion",
        "charging_time": "battinfo:chargingTime",
        "self_discharge_rate": "electrochemistry:electrochemistry_c3e97d58_1854_4c23_bb42_d2972172865e",
        "state_of_health": "electrochemistry:electrochemistry_a7a4614f_2426_46f3_8475_cda4a9fabfce",
        "source_type": "dcterms:type",
        "source_url": {
          "@id": "prov:hadPrimarySource",
          "@type": "@id"
        },
        "citation": "dcterms:bibliographicCitation",
        "citation_doi": "bibo:doi",
        "retrieved_at": "prov:generatedAtTime",
        "workflow_version": "pav:version",
        "curated_by": "dcterms:contributor",
        "protocol_name": "schema:name",
        "protocol_url": "schema:url",
        "V": "emmo:Volt",
        "mV": "emmo:MilliVolt",
        "kV": "emmo:KiloVolt",
        "Ah": "emmo:AmpereHour",
        "mAh": "emmo:MilliAmpereHour",
        "A": "emmo:Ampere",
        "mA": "emmo:MilliAmpere",
        "W": "emmo:Watt",
        "kW": "emmo:KiloWatt",
        "Wh": "emmo:WattHour",
        "kWh": "emmo:KiloWattHour",
        "MWh": "emmo:MegaWattHour",
        "Ohm": "emmo:Ohm",
        "mOhm": "emmo:MilliOhm",
        "mohm": "emmo:MilliOhm",
        "degC": "emmo:EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc",
        "K": "emmo:Kelvin",
        "g": "emmo:Gram",
        "kg": "emmo:Kilogram",
        "mg": "emmo:MilliGram",
        "mm": "emmo:MilliMetre",
        "cm": "emmo:CentiMetre",
        "m": "emmo:Metre",
        "L": "emmo:Litre",
        "mL": "emmo:MilliLitre",
        "cm3": "emmo:CubicCentiMetre",
        "h": "emmo:Hour",
        "min": "emmo:Minute",
        "s": "emmo:Second",
        "1": "emmo:EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
        "%": "emmo:Percent",
        "license": {
          "@id": "dcterms:license",
          "@type": "@id"
        },
        "created_at": {
          "@id": "dcterms:created",
          "@type": "xsd:dateTime"
        },
        "modified_at": {
          "@id": "dcterms:modified",
          "@type": "xsd:dateTime"
        }
      },
      "@type": "http://www.w3.org/ns/dcat#Dataset",
      "@id": "https://w3id.org/battinfo/dataset/1f8r-6v2k-9p4m-3t7x",
      "dcterms:title": "Cell cycling run for BattINFO cell 3m6k9t",
      "dcterms:license": {
        "@id": "https://creativecommons.org/licenses/by/4.0/"
      },
      "dcat:accessURL": {
        "@id": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      },
      "dcterms:created": "2026-02-22T00:00:00Z",
      "dcterms:modified": "2026-02-22T00:00:00Z",
      "dcterms:subject": [
        {
          "@id": "https://w3id.org/battinfo/cell/3m6k-9t2p-7x4h-9nq8"
        },
        {
          "@id": "https://w3id.org/battinfo/test/5p7v-2n8k-4m3t-6q9r"
        }
      ],
      "dcat:distribution": [
        {
          "@type": "dcat:Distribution",
          "dcat:downloadURL": {
            "@id": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x/raw.h5"
          },
          "dcat:mediaType": "application/x-hdf5",
          "spdx:checksum": {
            "@type": "spdx:Checksum",
            "spdx:checksumAlgorithm": "spdx:checksumAlgorithm_sha256",
            "spdx:checksumValue": "8fbf34bd0f8a0caef6f5ce6cc1f8e6a2d8f0123982fc624d6f7f3f7e27b95a89"
          }
        }
      ],
      "dcterms:source": {
        "@type": "prov:Entity",
        "dcterms:type": "measurement",
        "prov:hadPrimarySource": {
          "@id": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
        },
        "prov:generatedAtTime": "2026-02-22T00:00:00+00:00",
        "dcterms:bibliographicCitation": "https://example.org/lab-data/dataset-1f8r-6v2k-9p4m-3t7x"
      }
    }
  }
];
