// GENERATED by scripts/sync-properties.mjs — do not edit.
// Source of truth: assets/mappings/domain-battery/{property_map,unit_map}.curated.json
// (63 properties, 35 units). CI fails if this file drifts.

export const curatedProperties: { key: string; label: string; qname: string; iri: string }[] = [
  {
    "key": "ac_internal_resistance",
    "label": "ACInternalResistance",
    "qname": "emmo:ACInternalResistance",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_964cd426_f3cf_4a52_8c5d_0490cf48edb5"
  },
  {
    "key": "available_volume",
    "label": "Volume",
    "qname": "emmo:Volume",
    "iri": "https://w3id.org/emmo#EMMO_f1a51559_aa3d_43a0_9327_918039f0dfed"
  },
  {
    "key": "calendar_life",
    "label": "CalendarLife",
    "qname": "emmo:CalendarLife",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_743c71a3_b80c_42e3_92fa_13a67b8167df"
  },
  {
    "key": "cap_assembly_weight",
    "label": "Mass",
    "qname": "emmo:Mass",
    "iri": "https://w3id.org/emmo#EMMO_ed4af7ae_63a2_497e_bb88_2309619ea405"
  },
  {
    "key": "certified_usable_energy",
    "label": "NominalEnergy",
    "qname": "emmo:NominalEnergy",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d"
  },
  {
    "key": "charging_cutoff_voltage",
    "label": "UpperVoltageLimit",
    "qname": "emmo:UpperVoltageLimit",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88"
  },
  {
    "key": "charging_temperature_max",
    "label": "MaximumChargingTemperature",
    "qname": "emmo:MaximumChargingTemperature",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_4a354510_4dc2_4803_8845_f4024a1a7260"
  },
  {
    "key": "charging_temperature_min",
    "label": "MinimumChargingTemperature",
    "qname": "emmo:MinimumChargingTemperature",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_b90b1ad7_b9a8_44df_ad45_bfd25aac2e49"
  },
  {
    "key": "charging_voltage",
    "label": "ChargingVoltage",
    "qname": "emmo:ChargingVoltage",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_79a9e1be_35b0_4c3c_8087_b5f967ca0e87"
  },
  {
    "key": "continuous_charging_current",
    "label": "MaximumContinuousChargingCurrent",
    "qname": "emmo:MaximumContinuousChargingCurrent",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78"
  },
  {
    "key": "continuous_discharging_current",
    "label": "MaximumContinuousDischargingCurrent",
    "qname": "emmo:MaximumContinuousDischargingCurrent",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5"
  },
  {
    "key": "cycle_life",
    "label": "CycleLife",
    "qname": "emmo:CycleLife",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_ae782b14_88ce_4cdd_9418_12aca00be937"
  },
  {
    "key": "d50_particle_size",
    "label": "D50ParticleSize",
    "qname": "emmo:D50ParticleSize",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_3cfdfc10_a5cb_4e3e_b1a1_281010d1465c"
  },
  {
    "key": "dc_internal_resistance",
    "label": "DCInternalResistance",
    "qname": "emmo:DCInternalResistance",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_7b3eb826_b968_493a_8396_cc3a5f09ecb3"
  },
  {
    "key": "diameter",
    "label": "Diameter",
    "qname": "emmo:Diameter",
    "iri": "https://w3id.org/emmo#EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6"
  },
  {
    "key": "discharging_cutoff_voltage",
    "label": "LowerVoltageLimit",
    "qname": "emmo:LowerVoltageLimit",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_534dd59c_904c_45d9_8550_ae9d2eb6bbc9"
  },
  {
    "key": "discharging_temperature_max",
    "label": "MaximumDischargingTemperature",
    "qname": "emmo:MaximumDischargingTemperature",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_de612af2_a029_4a02_8090_4a75ab13271d"
  },
  {
    "key": "discharging_temperature_min",
    "label": "MinimumDischargingTemperature",
    "qname": "emmo:MinimumDischargingTemperature",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_2a1de79f_e927_45a2_9619_3799a0d61e9b"
  },
  {
    "key": "double_side_loading",
    "label": "MassLoading",
    "qname": "emmo:MassLoading",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_c955c089_6ee1_41a2_95fc_d534c5cfd3d5"
  },
  {
    "key": "energy_density",
    "label": "EnergyDensity",
    "qname": "emmo:EnergyDensity",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_4aa1b96e_44a0_4b1a_a0ac_723d0223d80b"
  },
  {
    "key": "foil_thickness",
    "label": "Thickness",
    "qname": "emmo:Thickness",
    "iri": "https://w3id.org/emmo#EMMO_43003c86_9d15_433b_9789_ee2940920656"
  },
  {
    "key": "height",
    "label": "Height",
    "qname": "emmo:Height",
    "iri": "https://w3id.org/emmo#EMMO_08bcf1d6_e719_46c8_bb21_24bc9bf34dba"
  },
  {
    "key": "impedance",
    "label": "ElectricImpedance",
    "qname": "emmo:ElectricImpedance",
    "iri": "https://w3id.org/emmo#EMMO_79a02de5_b884_4eab_bc18_f67997d597a2"
  },
  {
    "key": "initial_coulombic_efficiency",
    "label": "InitialCoulombicEfficiency",
    "qname": "emmo:InitialCoulombicEfficiency",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_469b9516_a96d_4aa2_b8e5_05ae982e2084"
  },
  {
    "key": "internal_resistance",
    "label": "InternalResistance",
    "qname": "emmo:InternalResistance",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_9bf40017_3f58_4030_ada7_cb37a3dfda2d"
  },
  {
    "key": "length",
    "label": "Length",
    "qname": "emmo:Length",
    "iri": "https://w3id.org/emmo#EMMO_cd2cd0de_e0cc_4ef1_b27e_2e88db027bac"
  },
  {
    "key": "mass",
    "label": "Mass",
    "qname": "emmo:Mass",
    "iri": "https://w3id.org/emmo#EMMO_ed4af7ae_63a2_497e_bb88_2309619ea405"
  },
  {
    "key": "maximum_charging_temperature",
    "label": "MaximumChargingTemperature",
    "qname": "emmo:MaximumChargingTemperature",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_4a354510_4dc2_4803_8845_f4024a1a7260"
  },
  {
    "key": "maximum_continuous_charging_current",
    "label": "MaximumContinuousChargingCurrent",
    "qname": "emmo:MaximumContinuousChargingCurrent",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_39d8a6ee_cd55_4855_8b5b_d42bef95ac78"
  },
  {
    "key": "maximum_continuous_discharging_current",
    "label": "MaximumContinuousDischargingCurrent",
    "qname": "emmo:MaximumContinuousDischargingCurrent",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_ba7ac581_0e13_4815_b888_013c378932f5"
  },
  {
    "key": "maximum_discharging_temperature",
    "label": "MaximumDischargingTemperature",
    "qname": "emmo:MaximumDischargingTemperature",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_de612af2_a029_4a02_8090_4a75ab13271d"
  },
  {
    "key": "maximum_storage_temperature",
    "label": "MaximumStorageTemperature",
    "qname": "emmo:MaximumStorageTemperature",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_0ea4d188_9701_4699_a5ca_812a98a9afa7"
  },
  {
    "key": "min_capacity",
    "label": "MinimumCapacity",
    "qname": "emmo:MinimumCapacity",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_d3c0078e_c1d3_461e_873d_e5c3adf441c5"
  },
  {
    "key": "minimum_capacity",
    "label": "MinimumCapacity",
    "qname": "emmo:MinimumCapacity",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_d3c0078e_c1d3_461e_873d_e5c3adf441c5"
  },
  {
    "key": "minimum_charging_temperature",
    "label": "MinimumChargingTemperature",
    "qname": "emmo:MinimumChargingTemperature",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_b90b1ad7_b9a8_44df_ad45_bfd25aac2e49"
  },
  {
    "key": "minimum_discharging_temperature",
    "label": "MinimumDischargingTemperature",
    "qname": "emmo:MinimumDischargingTemperature",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_2a1de79f_e927_45a2_9619_3799a0d61e9b"
  },
  {
    "key": "minimum_storage_temperature",
    "label": "MinimumStorageTemperature",
    "qname": "emmo:MinimumStorageTemperature",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_0ddfd57a_d338_4690_be45_b26884ed6302"
  },
  {
    "key": "n_p_ratio",
    "label": "NPRatio",
    "qname": "emmo:NPRatio",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_05012606_b93d_4016_bbc7_8a927efdf723"
  },
  {
    "key": "nominal_capacity",
    "label": "NominalCapacity",
    "qname": "emmo:NominalCapacity",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100"
  },
  {
    "key": "nominal_energy",
    "label": "NominalEnergy",
    "qname": "emmo:NominalEnergy",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d"
  },
  {
    "key": "nominal_voltage",
    "label": "NominalVoltage",
    "qname": "emmo:NominalVoltage",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_639b844a_e801_436b_985d_28926129ead6"
  },
  {
    "key": "press_density",
    "label": "CalenderedDensity",
    "qname": "emmo:CalenderedDensity",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_520995f8_ec9c_4b3c_bb64_2cd691947379"
  },
  {
    "key": "pulse_charging_current",
    "label": "MaximumPulseChargingCurrent",
    "qname": "emmo:MaximumPulseChargingCurrent",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_1b2a7137_64d4_483a_8437_dcb3bedcb6da"
  },
  {
    "key": "pulse_discharging_current",
    "label": "MaximumPulseDischargingCurrent",
    "qname": "emmo:MaximumPulseDischargingCurrent",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_3e54f9e3_a31d_4821_9bfb_ef953a42c35b"
  },
  {
    "key": "rated_areal_discharge_capacity",
    "label": "AreicCapacity",
    "qname": "emmo:AreicCapacity",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_bcb33f7e_5573_4bc2_b636_4ea313a9dd3a"
  },
  {
    "key": "rated_capacity",
    "label": "RatedCapacity",
    "qname": "emmo:RatedCapacity",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_9b3b4668_0795_4a35_9965_2af383497a26"
  },
  {
    "key": "rated_energy",
    "label": "NominalEnergy",
    "qname": "emmo:NominalEnergy",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d"
  },
  {
    "key": "rated_specific_discharge_capacity",
    "label": "DischargingSpecificCapacity",
    "qname": "emmo:DischargingSpecificCapacity",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_884650fd_6cc6_4ec6_8264_c18fbe6b90ee"
  },
  {
    "key": "self_discharge_rate",
    "label": "SelfDischargeRate",
    "qname": "emmo:SelfDischargeRate",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_c3e97d58_1854_4c23_bb42_d2972172865e"
  },
  {
    "key": "single_side_loading",
    "label": "MassLoading",
    "qname": "emmo:MassLoading",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_c955c089_6ee1_41a2_95fc_d534c5cfd3d5"
  },
  {
    "key": "specific_energy",
    "label": "SpecificEnergy",
    "qname": "emmo:SpecificEnergy",
    "iri": "https://w3id.org/emmo#EMMO_e218c625_6a39_47a9_8d08_a2ef41c152a9"
  },
  {
    "key": "state_of_health",
    "label": "StateOfHealth",
    "qname": "emmo:StateOfHealth",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_a7a4614f_2426_46f3_8475_cda4a9fabfce"
  },
  {
    "key": "storage_temperature_max",
    "label": "MaximumStorageTemperature",
    "qname": "emmo:MaximumStorageTemperature",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_0ea4d188_9701_4699_a5ca_812a98a9afa7"
  },
  {
    "key": "storage_temperature_min",
    "label": "MinimumStorageTemperature",
    "qname": "emmo:MinimumStorageTemperature",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_0ddfd57a_d338_4690_be45_b26884ed6302"
  },
  {
    "key": "theoretical_capacity",
    "label": "TheoreticalCapacity",
    "qname": "emmo:TheoreticalCapacity",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_372c89d0_adab_4585_9662_33c912acef23"
  },
  {
    "key": "thickness",
    "label": "Thickness",
    "qname": "emmo:Thickness",
    "iri": "https://w3id.org/emmo#EMMO_43003c86_9d15_433b_9789_ee2940920656"
  },
  {
    "key": "tortuosity",
    "label": "Tortuosity",
    "qname": "emmo:Tortuosity",
    "iri": "https://w3id.org/emmo#EMMO_c413d96f_c57b_4c70_9ac1_312db6c009a8"
  },
  {
    "key": "typical_energy",
    "label": "NominalEnergy",
    "qname": "emmo:NominalEnergy",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_19e27aa3_0970_43a6_86d3_e3cdd956134d"
  },
  {
    "key": "upper_voltage_limit",
    "label": "UpperVoltageLimit",
    "qname": "emmo:UpperVoltageLimit",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88"
  },
  {
    "key": "volume",
    "label": "Volume",
    "qname": "emmo:Volume",
    "iri": "https://w3id.org/emmo#EMMO_f1a51559_aa3d_43a0_9327_918039f0dfed"
  },
  {
    "key": "wall_thickness",
    "label": "Thickness",
    "qname": "emmo:Thickness",
    "iri": "https://w3id.org/emmo#EMMO_43003c86_9d15_433b_9789_ee2940920656"
  },
  {
    "key": "weight",
    "label": "Mass",
    "qname": "emmo:Mass",
    "iri": "https://w3id.org/emmo#EMMO_ed4af7ae_63a2_497e_bb88_2309619ea405"
  },
  {
    "key": "width",
    "label": "Width",
    "qname": "emmo:Width",
    "iri": "https://w3id.org/emmo#EMMO_e4de48b1_dabb_4490_ac2b_040f926c64f0"
  }
];

export const curatedUnits: { symbol: string; label: string; qname: string; iri: string }[] = [
  {
    "symbol": "%",
    "label": "WeightPercent",
    "qname": "electrochemistry:WeightPercent",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_2c0e66c8_d58d_44b2_b0ce_ba55194bd505"
  },
  {
    "symbol": "°C",
    "label": "CelsiusTemperature",
    "qname": "emmo:CelsiusTemperature",
    "iri": "https://w3id.org/emmo#EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc"
  },
  {
    "symbol": "A",
    "label": "Ampere",
    "qname": "emmo:Ampere",
    "iri": "https://w3id.org/emmo#Ampere"
  },
  {
    "symbol": "Ah",
    "label": "AmpereHour",
    "qname": "emmo:AmpereHour",
    "iri": "https://w3id.org/emmo#AmpereHour"
  },
  {
    "symbol": "cm",
    "label": "CentiMetre",
    "qname": "emmo:CentiMetre",
    "iri": "https://w3id.org/emmo#CentiMetre"
  },
  {
    "symbol": "count",
    "label": "UnitOne",
    "qname": "emmo:UnitOne",
    "iri": "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"
  },
  {
    "symbol": "degC",
    "label": "CelsiusTemperature",
    "qname": "emmo:CelsiusTemperature",
    "iri": "https://w3id.org/emmo#EMMO_36a9bf69_483b_42fd_8a0c_7ac9206320bc"
  },
  {
    "symbol": "g",
    "label": "Gram",
    "qname": "emmo:Gram",
    "iri": "https://w3id.org/emmo#Gram"
  },
  {
    "symbol": "g/cm3",
    "label": "GramPerCubicCentiMetre",
    "qname": "emmo:GramPerCubicCentiMetre",
    "iri": "https://w3id.org/emmo#GramPerCubicCentiMetre"
  },
  {
    "symbol": "h",
    "label": "Hour",
    "qname": "emmo:Hour",
    "iri": "https://w3id.org/emmo#Hour"
  },
  {
    "symbol": "K",
    "label": "Kelvin",
    "qname": "emmo:Kelvin",
    "iri": "https://w3id.org/emmo#Kelvin"
  },
  {
    "symbol": "kg",
    "label": "Kilogram",
    "qname": "emmo:Kilogram",
    "iri": "https://w3id.org/emmo#Kilogram"
  },
  {
    "symbol": "kWh",
    "label": "KiloWattHour",
    "qname": "emmo:KiloWattHour",
    "iri": "https://w3id.org/emmo#KiloWattHour"
  },
  {
    "symbol": "L",
    "label": "Litre",
    "qname": "emmo:Litre",
    "iri": "https://w3id.org/emmo#Litre"
  },
  {
    "symbol": "m",
    "label": "Metre",
    "qname": "emmo:Metre",
    "iri": "https://w3id.org/emmo#Metre"
  },
  {
    "symbol": "mA",
    "label": "MilliAmpere",
    "qname": "emmo:MilliAmpere",
    "iri": "https://w3id.org/emmo#MilliAmpere"
  },
  {
    "symbol": "mAh",
    "label": "MilliAmpereHour",
    "qname": "emmo:MilliAmpereHour",
    "iri": "https://w3id.org/emmo#MilliAmpereHour"
  },
  {
    "symbol": "mg/cm2",
    "label": "MilliGramPerSquareCentiMetre",
    "qname": "emmo:MilliGramPerSquareCentiMetre",
    "iri": "https://w3id.org/emmo#MilliGramPerSquareCentiMetre"
  },
  {
    "symbol": "min",
    "label": "Minute",
    "qname": "emmo:Minute",
    "iri": "https://w3id.org/emmo#Minute"
  },
  {
    "symbol": "mL",
    "label": "MilliLitre",
    "qname": "emmo:MilliLitre",
    "iri": "https://w3id.org/emmo#MilliLitre"
  },
  {
    "symbol": "mm",
    "label": "MilliMetre",
    "qname": "emmo:MilliMetre",
    "iri": "https://w3id.org/emmo#MilliMetre"
  },
  {
    "symbol": "mol/L",
    "label": "MolePerLitre",
    "qname": "emmo:MolePerLitre",
    "iri": "https://w3id.org/emmo#MolePerLitre"
  },
  {
    "symbol": "mV",
    "label": "MilliVolt",
    "qname": "emmo:MilliVolt",
    "iri": "https://w3id.org/emmo#MilliVolt"
  },
  {
    "symbol": "mΩ",
    "label": "MilliOhm",
    "qname": "emmo:MilliOhm",
    "iri": "https://w3id.org/emmo#MilliOhm"
  },
  {
    "symbol": "s",
    "label": "Second",
    "qname": "emmo:Second",
    "iri": "https://w3id.org/emmo#Second"
  },
  {
    "symbol": "V",
    "label": "Volt",
    "qname": "emmo:Volt",
    "iri": "https://w3id.org/emmo#Volt"
  },
  {
    "symbol": "vol%",
    "label": "VolumePercent",
    "qname": "electrochemistry:VolumePercent",
    "iri": "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_db37b358_b2f0_4e06_b6ae_8c56c8fbb6ba"
  },
  {
    "symbol": "W",
    "label": "Watt",
    "qname": "emmo:Watt",
    "iri": "https://w3id.org/emmo#Watt"
  },
  {
    "symbol": "W/kg",
    "label": "WattPerKilogram",
    "qname": "qudt:W-PER-KiloGM",
    "iri": "http://qudt.org/vocab/unit/W-PER-KiloGM"
  },
  {
    "symbol": "W/L",
    "label": "WattPerLitre",
    "qname": "qudt:W-PER-L",
    "iri": "http://qudt.org/vocab/unit/W-PER-L"
  },
  {
    "symbol": "Wh",
    "label": "WattHour",
    "qname": "emmo:WattHour",
    "iri": "https://w3id.org/emmo#WattHour"
  },
  {
    "symbol": "Wh/kg",
    "label": "WattHourPerKilogram",
    "qname": "emmo:WattHourPerKilogram",
    "iri": "https://w3id.org/emmo#WattHourPerKilogram"
  },
  {
    "symbol": "Wh/L",
    "label": "WattHourPerLitre",
    "qname": "emmo:WattHourPerLitre",
    "iri": "https://w3id.org/emmo#WattHourPerLitre"
  },
  {
    "symbol": "µm",
    "label": "MicroMetre",
    "qname": "emmo:MicroMetre",
    "iri": "https://w3id.org/emmo#MicroMetre"
  },
  {
    "symbol": "Ω",
    "label": "Ohm",
    "qname": "emmo:Ohm",
    "iri": "https://w3id.org/emmo#Ohm"
  }
];
