// GENERATED by scripts/gen_web_examples.py — do not edit.
// Each entry's `code` is the literal source of a snippet function in that
// script, and `record` is what executing it produced (IRIs/timestamps
// normalized). tests/test_web_generated.py fails when this file drifts.

export const showcase: {
  slug: string;
  title: string;
  tagline: string;
  recordType: string | null;
  code: string;
  record: Record<string, unknown>;
  jsonld: Record<string, unknown> | null;
}[] = [
  {
    "slug": "material",
    "title": "A material",
    "tagline": "Any substance in the cell — actives, binders, salts, solvents — with its properties, reusable across every cell that contains it.",
    "recordType": null,
    "code": "from battinfo.authoring import material\nfrom battinfo.materials import material_spec_from_component\n\nnmc = material(\n    \"NMC811\",\n    molecular_formula=\"LiNi0.8Mn0.1Co0.1O2\",\n    mass_fraction={\"value\": 96, \"unit\": \"%\"},\n)\n\n# Lift it to a standalone, reusable material-spec record with its own IRI\nrecord = material_spec_from_component(nmc, material_class=\"active_material\")",
    "record": {
      "schema_version": "0.2.0",
      "material_spec": {
        "id": "https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5",
        "short_id": "7d9k2m",
        "name": "NMC811",
        "material_class": "active_material",
        "formula": "LiNi0.8Mn0.1Co0.1O2"
      },
      "provenance": {
        "source_type": "datasheet",
        "retrieved_at": 1750000000,
        "battinfo_version": "0.7.0"
      }
    },
    "jsonld": null
  },
  {
    "slug": "electrode",
    "title": "An electrode",
    "tagline": "A bill of materials plus the numbers that define the coating: loading, calendered density, current collector.",
    "recordType": null,
    "code": "from battinfo.authoring import bom, electrode, material\n\ncathode = electrode(\n    bom=bom(\n        active_material=material(\"NMC811\", mass_fraction={\"value\": 96, \"unit\": \"%\"}),\n        binder=material(\"PVDF\", mass_fraction={\"value\": 2, \"unit\": \"%\"}),\n        additive=material(\"Carbon black\", mass_fraction={\"value\": 2, \"unit\": \"%\"}),\n    ),\n    loading={\"value\": 18.5, \"unit\": \"mg/cm2\"},\n    calendered_density={\"value\": 3.4, \"unit\": \"g/cm3\"},\n    current_collector=\"Aluminium foil\",\n)\nrecord = cathode.model_dump(exclude_none=True)",
    "record": {
      "coating": {
        "component": {
          "active_material": [
            {
              "name": "NMC811",
              "property": {
                "mass_fraction": {
                  "value": 96,
                  "unit": "%"
                }
              }
            }
          ],
          "binder": [
            {
              "name": "PVDF",
              "property": {
                "mass_fraction": {
                  "value": 2,
                  "unit": "%"
                }
              }
            }
          ],
          "additive": [
            {
              "name": "Carbon black",
              "property": {
                "mass_fraction": {
                  "value": 2,
                  "unit": "%"
                }
              }
            }
          ]
        },
        "property": {
          "loading": {
            "value": 18.5,
            "unit": "mg/cm2"
          },
          "calendered_density": {
            "value": 3.4,
            "unit": "g/cm3"
          }
        }
      },
      "current_collector": {
        "name": "Aluminium foil",
        "property": {}
      },
      "property": {}
    },
    "jsonld": null
  },
  {
    "slug": "electrolyte",
    "title": "An electrolyte",
    "tagline": "Salt, solvents, and additives — all the same material(...) form, fractions and concentrations inline.",
    "recordType": null,
    "code": "from battinfo.authoring import electrolyte_recipe, material\n\nlp30 = electrolyte_recipe(\n    family=\"organic\",\n    salt=material(\"LiPF6\", concentration={\"value\": 1.0, \"unit\": \"mol/L\"}),\n    solvents=[\n        material(\"EC\", volume_fraction={\"value\": 50, \"unit\": \"%\"}),\n        material(\"DMC\", volume_fraction={\"value\": 50, \"unit\": \"%\"}),\n    ],\n    additives=[material(\"VC\", mass_fraction={\"value\": 2.0, \"unit\": \"%\"})],\n    comment=\"LP30 + 2% VC\",\n)\nrecord = lp30.model_dump(exclude_none=True)",
    "record": {
      "family": "organic",
      "solvent_mixture": {
        "component": [
          {
            "name": "EC",
            "property": {
              "volume_fraction": {
                "value": 50,
                "unit": "%"
              }
            }
          },
          {
            "name": "DMC",
            "property": {
              "volume_fraction": {
                "value": 50,
                "unit": "%"
              }
            }
          }
        ],
        "property": {}
      },
      "salt": {
        "name": "LiPF6",
        "property": {
          "concentration": {
            "value": 1.0,
            "unit": "mol/L"
          }
        }
      },
      "additive": [
        {
          "name": "VC",
          "property": {
            "mass_fraction": {
              "value": 2.0,
              "unit": "%"
            }
          }
        }
      ],
      "property": {},
      "comment": "LP30 + 2% VC"
    },
    "jsonld": null
  },
  {
    "slug": "separator",
    "title": "A separator",
    "tagline": "Base material, thickness, porosity — and free text for what the numbers can't hold.",
    "recordType": null,
    "code": "from battinfo.authoring import properties, separator_spec\n\nsep = separator_spec(\n    material=\"Polypropylene\",\n    thickness={\"value\": 25.0, \"unit\": \"µm\"},\n    properties=properties(porosity={\"value\": 41, \"unit\": \"%\"}),\n    comment=\"Celgard 2500, single-layer PP\",\n)\nrecord = sep.model_dump(exclude_none=True)",
    "record": {
      "material": "Polypropylene",
      "property": {
        "porosity": {
          "value": 41,
          "unit": "%"
        },
        "thickness": {
          "value": 25.0,
          "unit": "µm"
        }
      },
      "comment": "Celgard 2500, single-layer PP"
    },
    "jsonld": null
  },
  {
    "slug": "cell-spec",
    "title": "A cell spec",
    "tagline": "The product datasheet, as data: identity, format, chemistry, and rated properties with units that resolve to EMMO.",
    "recordType": "cell-spec",
    "code": "from battinfo import CellSpec\n\nspec = CellSpec(\n    # The published flagship IRI: dereference it (Accept: application/ld+json)\n    # to get this exact record. In the workspace flow the IRI is minted for\n    # you at ws.save(); standalone, you set it (or let publish() mint it).\n    id=\"https://w3id.org/battinfo/spec/pge5-wer6-2q82-v9k0\",\n    manufacturer=\"A123\",\n    model=\"ANR26650M1-B\",\n    format=\"cylindrical\",\n    chemistry=\"Li-ion\",\n    positive_electrode_basis=\"LFP\",\n    properties={\n        \"nominal_capacity\": {\"value\": 2.5, \"unit\": \"Ah\"},\n        \"nominal_voltage\": {\"value\": 3.3, \"unit\": \"V\"},\n        \"mass\": {\"value\": 76.0, \"unit\": \"g\"},\n    },\n    source={\"type\": \"datasheet\", \"retrieved_at\": 1750000000},\n)\nrecord = spec.to_record()",
    "record": {
      "schema_version": "0.2.0",
      "cell_spec": {
        "id": "https://w3id.org/battinfo/spec/pge5-wer6-2q82-v9k0",
        "short_id": "pge5we",
        "identifier": "cell-spec:pge5-wer6-2q82-v9k0",
        "name": "A123 ANR26650M1-B",
        "model": "ANR26650M1-B",
        "manufacturer": {
          "type": "Organization",
          "name": "A123"
        },
        "cell_format": "cylindrical",
        "chemistry": "Li-ion",
        "positive_electrode_basis": "LFP"
      },
      "properties": {
        "nominal_capacity": {
          "value": 2.5,
          "unit": "Ah"
        },
        "nominal_voltage": {
          "value": 3.3,
          "unit": "V"
        },
        "mass": {
          "value": 76.0,
          "unit": "g"
        }
      },
      "provenance": {
        "source_type": "datasheet",
        "retrieved_at": 1750000000,
        "battinfo_version": "0.7.0"
      }
    },
    "jsonld": {
      "@context": "https://w3id.org/battinfo/context/records/v1.json",
      "@type": [
        "BatteryCellSpecification",
        "schema:CreativeWork"
      ],
      "@id": "https://w3id.org/battinfo/spec/pge5-wer6-2q82-v9k0",
      "schema:identifier": "pge5-wer6-2q82-v9k0",
      "schema:name": "A123 ANR26650M1-B",
      "schema:model": "ANR26650M1-B",
      "schema:manufacturer": {
        "@type": "schema:Organization",
        "schema:name": "A123"
      },
      "schema:url": "https://www.battery-genome.org/registry/spec/pge5-wer6-2q82-v9k0",
      "isDescriptionFor": {
        "@type": [
          "BatteryCell",
          "CylindricalBattery",
          "LithiumIonBattery",
          "LithiumIonIronPhosphateBattery"
        ],
        "skos:prefLabel": "A123 ANR26650M1-B"
      },
      "schema:schemaVersion": "0.2.0",
      "hasProperty": [
        {
          "@type": [
            "NominalCapacity",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "NominalCapacity",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 2.5
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#AmpereHour"
        },
        {
          "@type": [
            "NominalVoltage",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "NominalVoltage",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 3.3
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Volt"
        },
        {
          "@type": [
            "Mass",
            "ConventionalProperty"
          ],
          "skos:prefLabel": "Mass",
          "hasNumericalPart": {
            "@type": "RealData",
            "hasNumberValue": 76.0
          },
          "hasMeasurementUnit": "https://w3id.org/emmo#Gram"
        }
      ],
      "hasPositiveElectrode": {
        "@type": "LithiumIronPhosphateElectrode"
      },
      "dcterms:source": {
        "@type": "prov:Entity",
        "dcterms:type": "datasheet",
        "prov:generatedAtTime": "2025-06-15T15:06:40+00:00"
      }
    }
  },
  {
    "slug": "cell",
    "title": "A cell",
    "tagline": "One specific physical item with a serial number, permanently linked to the spec that describes it.",
    "recordType": null,
    "code": "from battinfo import Cell, CellSpec\n\nspec = CellSpec(\n    id=\"https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5\",\n    manufacturer=\"Samsung SDI\",\n    model=\"INR21700-50E\",\n    format=\"cylindrical\",\n    chemistry=\"Li-ion\",\n)\ncell = Cell(\n    id=\"https://w3id.org/battinfo/cell/y9xy-kr0v-y5tn-dfj7\",\n    cell_spec=spec,                    # every cell links to its spec\n    serial_number=\"LAB-2026-0001\",\n    manufactured_at=\"2026-01-15\",\n)\nrecord = cell.to_record()",
    "record": {
      "schema_version": "0.2.0",
      "cell_instance": {
        "id": "https://w3id.org/battinfo/cell/y9xy-kr0v-y5tn-dfj7",
        "short_id": "y9xykr",
        "cell_spec_id": "https://w3id.org/battinfo/spec/y9xy-kr0v-y5tn-dfj7",
        "name": "LAB-2026-0001",
        "serial_number": "LAB-2026-0001",
        "manufactured_at": "2026-01-15"
      },
      "provenance": {
        "battinfo_version": "0.7.0"
      }
    },
    "jsonld": null
  },
  {
    "slug": "test-spec",
    "title": "A test spec",
    "tagline": "The reusable procedure — steps in PyBaMM syntax a machine can re-run, conditions a human can check.",
    "recordType": null,
    "code": "from battinfo import TestSpec\n\nprotocol = TestSpec(\n    id=\"https://w3id.org/battinfo/spec/kxwy-5f5f-f682-hhch\",\n    name=\"1C cycle life at 25 °C\",\n    kind=\"cycling\",\n    experiment=[                       # PyBaMM syntax — runnable as-is\n        \"Charge at 1C until 4.2 V\",\n        \"Hold at 4.2 V until C/20\",\n        \"Discharge at 1C until 2.5 V\",\n        \"Rest for 10 minutes\",\n    ],\n    conditions={\"ambient_temperature\": {\"value\": 25.0, \"unit\": \"degC\"}},\n)\nrecord = protocol.to_record()",
    "record": {
      "schema_version": "0.2.0",
      "test_spec": {
        "id": "https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5",
        "short_id": "7d9k2m",
        "identifier": "test-protocol:7d9k-2m4p-8t3x-6nq5",
        "name": "1C cycle life at 25 °C",
        "kind": "cycling"
      },
      "provenance": {
        "battinfo_version": "0.7.0"
      },
      "method": [
        {
          "mode": "cc",
          "direction": "charge",
          "setpoints": {
            "c_rate": {
              "value": 1.0,
              "unit": "A/Ah"
            }
          },
          "termination": [
            {
              "quantity": "voltage",
              "value": 4.2,
              "unit": "V",
              "direction": "above"
            }
          ],
          "description": "Charge at 1C until 4.2 V"
        },
        {
          "mode": "cv",
          "direction": "hold",
          "setpoints": {
            "voltage": {
              "value": 4.2,
              "unit": "V"
            }
          },
          "termination": [
            {
              "quantity": "c_rate",
              "value": 0.05,
              "unit": "A/Ah",
              "direction": "below"
            }
          ],
          "description": "Hold at 4.2 V until C/20"
        },
        {
          "mode": "cc",
          "direction": "discharge",
          "setpoints": {
            "c_rate": {
              "value": 1.0,
              "unit": "A/Ah"
            }
          },
          "termination": [
            {
              "quantity": "voltage",
              "value": 2.5,
              "unit": "V",
              "direction": "below"
            }
          ],
          "description": "Discharge at 1C until 2.5 V"
        },
        {
          "mode": "rest",
          "direction": "rest",
          "duration": {
            "value": 600.0,
            "unit": "s"
          },
          "description": "Rest for 10 minutes"
        }
      ],
      "facets": {
        "modes": [
          "cc",
          "cv",
          "rest"
        ],
        "directions": [
          "charge",
          "discharge"
        ],
        "control_modes": [
          "current",
          "voltage"
        ],
        "has_cv_hold": true,
        "has_rest": true,
        "has_eis": false,
        "c_rates": [
          0.05,
          1.0
        ],
        "voltage_window_V": [
          2.5,
          4.2
        ],
        "temperatures": [
          25.0
        ]
      },
      "conditions": {
        "ambient_temperature": {
          "value": 25.0,
          "unit": "degC"
        }
      }
    },
    "jsonld": null
  },
  {
    "slug": "equipment",
    "title": "Equipment + channels",
    "tagline": "The cycler on the bench: the model as a spec, the physical unit, and one channel per slot — so every test can say exactly where it ran.",
    "recordType": null,
    "code": "from battinfo.api import create_channel, create_equipment, create_equipment_spec\n\nspec = create_equipment_spec(\n    # Explicit IRIs here; ws.add(\"equipment\", ...) mints them for you.\n    id=\"https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5\",\n    name=\"SkyRC MC3000\",\n    manufacturer=\"SkyRC\",\n    model=\"MC3000\",\n    equipment_class=\"cycler\",          # category is data, never a namespace\n    channel_count=4,\n    supported_chemistries=[\"NiMH\", \"Li-ion\", \"LiFePO4\", \"Na-ion\"],\n)\nunit = create_equipment(\n    id=\"https://w3id.org/battinfo/equipment/y9xy-kr0v-y5tn-dfj7\",\n    equipment_spec_id=spec[\"equipment_spec\"][\"id\"],\n    serial_number=\"MC3K-2026-0001\",\n    name=\"Cycler 1\",\n    location=\"Lab B\",\n    status=\"active\",\n)\nchannels = [                           # uid deterministic from (unit, index)\n    create_channel(equipment_id=unit[\"equipment\"][\"id\"], index=i,\n                   label=f\"MC3000-A/CH{i}\")\n    for i in (1, 2, 3, 4)\n]\nrecord = {\n    \"equipment_spec\": spec[\"equipment_spec\"],\n    \"equipment\": unit[\"equipment\"],\n    \"channels\": [c[\"channel\"] for c in channels],\n}",
    "record": {
      "equipment_spec": {
        "id": "https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5",
        "short_id": "7d9k2m",
        "name": "SkyRC MC3000",
        "equipment_class": "cycler",
        "model": "MC3000",
        "channel_count": 4,
        "supported_chemistries": [
          "NiMH",
          "Li-ion",
          "LiFePO4",
          "Na-ion"
        ],
        "manufacturer": {
          "type": "Organization",
          "name": "SkyRC"
        }
      },
      "equipment": {
        "id": "https://w3id.org/battinfo/equipment/y9xy-kr0v-y5tn-dfj7",
        "equipment_spec_id": "https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5",
        "short_id": "y9xykr",
        "serial_number": "MC3K-2026-0001",
        "name": "Cycler 1",
        "location": "Lab B",
        "status": "active"
      },
      "channels": [
        {
          "id": "https://w3id.org/battinfo/channel/3w87-0ddf-ryjg-evxe",
          "equipment_id": "https://w3id.org/battinfo/equipment/y9xy-kr0v-y5tn-dfj7",
          "index": 1,
          "short_id": "3w870d",
          "label": "MC3000-A/CH1"
        },
        {
          "id": "https://w3id.org/battinfo/channel/kxwy-5f5f-f682-hhch",
          "equipment_id": "https://w3id.org/battinfo/equipment/y9xy-kr0v-y5tn-dfj7",
          "index": 2,
          "short_id": "kxwy5f",
          "label": "MC3000-A/CH2"
        },
        {
          "id": "https://w3id.org/battinfo/channel/6nec-h262-tthy-4rnt",
          "equipment_id": "https://w3id.org/battinfo/equipment/y9xy-kr0v-y5tn-dfj7",
          "index": 3,
          "short_id": "6nech2",
          "label": "MC3000-A/CH3"
        },
        {
          "id": "https://w3id.org/battinfo/channel/0rp6-kncv-cyem-qwcd",
          "equipment_id": "https://w3id.org/battinfo/equipment/y9xy-kr0v-y5tn-dfj7",
          "index": 4,
          "short_id": "0rp6kn",
          "label": "MC3000-A/CH4"
        }
      ]
    },
    "jsonld": null
  },
  {
    "slug": "test",
    "title": "A test",
    "tagline": "One execution of a procedure on one cell: instrument, status, and the link every dataset hangs off.",
    "recordType": "test",
    "code": "from battinfo import Cell, CellSpec, Test\n\ncell = Cell(\n    id=\"https://w3id.org/battinfo/cell/y9xy-kr0v-y5tn-dfj7\",\n    cell_spec=CellSpec(\n        id=\"https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5\",\n        manufacturer=\"Samsung SDI\", model=\"INR21700-50E\",\n        format=\"cylindrical\", chemistry=\"Li-ion\",\n    ),\n    serial_number=\"LAB-2026-0001\",\n)\ntest = Test(\n    # A live IRI: dereference it (Accept: application/ld+json) and it\n    # resolves. Its archived payload predates this emission dialect; the\n    # showcase body below is the current gold-standard form.\n    id=\"https://w3id.org/battinfo/test/ygnc-b2j3-bc55-rbn1\",\n    cell=cell,                         # what you did, to which cell\n    kind=\"capacity_check\",\n    protocol=\"C/10 constant-current discharge\",\n    instrument=\"Biologic VMP-300\",\n    status=\"completed\",\n)\nrecord = test.to_record()",
    "record": {
      "schema_version": "0.2.0",
      "test": {
        "id": "https://w3id.org/battinfo/test/ygnc-b2j3-bc55-rbn1",
        "short_id": "ygncb2",
        "identifier": "test:ygnc-b2j3-bc55-rbn1",
        "name": "LAB-2026-0001 C/10 constant-current discharge",
        "kind": "capacity_check",
        "cell_id": "https://w3id.org/battinfo/cell/7d9k-2m4p-8t3x-6nq5",
        "status": "completed",
        "protocol_name": "C/10 constant-current discharge",
        "instrument_name": "Biologic VMP-300"
      },
      "provenance": {
        "battinfo_version": "0.7.0"
      }
    },
    "jsonld": {
      "@context": "https://w3id.org/battinfo/context/records/v1.json",
      "@type": [
        "BatteryTest",
        "schema:Action",
        "prov:Activity"
      ],
      "@id": "https://w3id.org/battinfo/test/ygnc-b2j3-bc55-rbn1",
      "schema:name": "LAB-2026-0001 C/10 constant-current discharge",
      "schema:additionalType": "capacity_check",
      "schema:instrument": "Biologic VMP-300",
      "schema:measurementTechnique": "C/10 constant-current discharge",
      "schema:actionStatus": "completed",
      "hasTestObject": {
        "@id": "https://w3id.org/battinfo/cell/7d9k-2m4p-8t3x-6nq5"
      }
    }
  },
  {
    "slug": "dataset",
    "title": "A dataset",
    "tagline": "The measured files, linked to the cell and test that produced them — the shape data portals understand (DCAT).",
    "recordType": "dataset",
    "code": "from battinfo import Cell, CellSpec, Dataset, Test\n\ncell = Cell(\n    id=\"https://w3id.org/battinfo/cell/y9xy-kr0v-y5tn-dfj7\",\n    cell_spec=CellSpec(\n        id=\"https://w3id.org/battinfo/spec/7d9k-2m4p-8t3x-6nq5\",\n        manufacturer=\"Samsung SDI\", model=\"INR21700-50E\",\n        format=\"cylindrical\", chemistry=\"Li-ion\",\n    ),\n    serial_number=\"LAB-2026-0001\",\n)\ntest = Test(\n    id=\"https://w3id.org/battinfo/test/6nec-h262-tthy-4rnt\",\n    cell=cell, kind=\"cycling\", status=\"completed\",\n)\ndataset = Dataset(\n    # A live IRI: dereference it (Accept: application/ld+json) and it\n    # resolves. Its archived payload predates this emission dialect; the\n    # showcase body below is the current gold-standard form.\n    id=\"https://w3id.org/battinfo/dataset/yssz-kccw-16g6-s21q\",\n    path=\"data/cycle-life-run\",        # the folder with your measured files\n    cell=cell,\n    test=test,\n    name=\"INR21700-50E cycle-life dataset\",\n    license=\"CC-BY-4.0\",\n    access_url=\"https://doi.org/10.5281/zenodo.1234567\",  # where the data lives\n)\nrecord = dataset.to_record()",
    "record": {
      "schema_version": "0.2.0",
      "dataset": {
        "id": "https://w3id.org/battinfo/dataset/yssz-kccw-16g6-s21q",
        "short_id": "ysszkc",
        "identifier": "dataset:yssz-kccw-16g6-s21q",
        "name": "INR21700-50E cycle-life dataset",
        "license": "CC-BY-4.0",
        "access_url": "https://doi.org/10.5281/zenodo.1234567",
        "about": [
          "https://w3id.org/battinfo/cell/7d9k-2m4p-8t3x-6nq5",
          "https://w3id.org/battinfo/test/y9xy-kr0v-y5tn-dfj7"
        ]
      },
      "provenance": {
        "battinfo_version": "0.7.0"
      }
    },
    "jsonld": {
      "@context": "https://w3id.org/battinfo/context/records/v1.json",
      "@type": "http://www.w3.org/ns/dcat#Dataset",
      "@id": "https://w3id.org/battinfo/dataset/yssz-kccw-16g6-s21q",
      "dcterms:title": "INR21700-50E cycle-life dataset",
      "dcterms:license": {
        "@id": "CC-BY-4.0"
      },
      "dcat:accessURL": {
        "@id": "https://doi.org/10.5281/zenodo.1234567"
      },
      "dcterms:subject": [
        {
          "@id": "https://w3id.org/battinfo/cell/7d9k-2m4p-8t3x-6nq5"
        },
        {
          "@id": "https://w3id.org/battinfo/test/y9xy-kr0v-y5tn-dfj7"
        }
      ]
    }
  }
];
