# Configurations used when running emmocheck from the ci_emmocheck workflow
skip:
  - test_namespace

test_quantity_dimension:
  exceptions:
    - BattINFO.ElectroChemicalQuantity
    - BattINFO.BatteryQuantity
