"""The committed reference-records chapter must match what the library does today.

docs/records/ is generated by scripts/gen_reference_records.py: each
page's authoring snippet is executed against the current library, the record it
produces is validated under the strict policy, and the emitted JSON-LD is
committed beside it. This test regenerates the chapter in memory and fails on
drift — a schema, API, or emitter change that alters any reference record must
regenerate the chapter in the same PR:

    uv run python scripts/gen_reference_records.py
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

_spec = importlib.util.spec_from_file_location(
    "gen_reference_records", ROOT / "scripts" / "gen_reference_records.py"
)
assert _spec is not None and _spec.loader is not None
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)


def test_reference_records_match_the_current_library() -> None:
    expected = gen.render_all()
    for name, text in expected.items():
        path = gen.OUT_DIR / name
        assert path.exists(), (
            f"docs/records/{name} is missing — "
            "run `uv run python scripts/gen_reference_records.py` and commit the result"
        )
        actual = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        assert actual == text.replace("\r\n", "\n"), (
            f"docs/records/{name} drifts from what the current library "
            "produces — run `uv run python scripts/gen_reference_records.py` and "
            "review the diff: it is the propagation record of your change"
        )


def test_generation_is_deterministic() -> None:
    # Two builds in one process must agree byte-for-byte; a snippet that lets a
    # randomly minted uid or a wall-clock timestamp leak through would make the
    # drift gate flaky instead of honest.
    assert gen.render_all() == gen.render_all()
