"""Committed web-generated artifacts must match what the library emits today.

The JSON-LD gallery on /examples is generated by scripts/gen_web_jsonld.py
using the real Python transform and committed (the Vercel build cannot run
Python). This test regenerates in memory and fails on drift — change the
transform and the gallery must be regenerated in the same PR.
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

_spec = importlib.util.spec_from_file_location("gen_web_jsonld", ROOT / "scripts" / "gen_web_jsonld.py")
assert _spec is not None and _spec.loader is not None
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)


def test_jsonld_gallery_matches_the_current_transform() -> None:
    expected = gen.render(gen.build_entries())
    actual = gen.OUT.read_text(encoding="utf-8").replace("\r\n", "\n")
    assert actual == expected.replace("\r\n", "\n"), (
        "web/lib/jsonld.generated.ts drifts from battinfo.record_to_jsonld output — "
        "run `uv run python scripts/gen_web_jsonld.py` and commit the result"
    )


def test_gallery_shows_type_stacking() -> None:
    entries = gen.build_entries()
    cell_spec = next(e for e in entries if e["slug"] == "cell-spec")
    types = cell_spec["jsonld"].get("@type")
    assert isinstance(types, list) and len(types) >= 3, (
        "the flagship cell-spec JSON-LD should stack multiple EMMO types — "
        f"got {types!r}"
    )


def test_public_jsonld_files_match_the_transform() -> None:
    entries = gen.build_entries()
    for name, expected in gen.render_public(entries).items():
        raw = (gen.PUBLIC_DIR / name).read_text(encoding="utf-8")
        actual = raw.replace(chr(13) + chr(10), chr(10))
        assert actual == expected, (
            f"web/public/jsonld/{name} drifts — run scripts/gen_web_jsonld.py"
        )


_spec2 = importlib.util.spec_from_file_location("gen_web_examples", ROOT / "scripts" / "gen_web_examples.py")
assert _spec2 is not None and _spec2.loader is not None
gen_showcase = importlib.util.module_from_spec(_spec2)
_spec2.loader.exec_module(gen_showcase)


def test_showcase_matches_the_current_library() -> None:
    """Every /examples snippet still runs and still produces the committed record."""
    expected = gen_showcase.render(gen_showcase.build_entries())
    actual = (ROOT / "web" / "lib" / "showcase.generated.ts").read_text(encoding="utf-8")
    assert actual == expected, (
        "web/lib/showcase.generated.ts is stale - regenerate with "
        "`uv run python scripts/gen_web_examples.py`"
    )
