import type { Metadata } from "next";
import Link from "next/link";
import { CodeBlock } from "@/components/code-block";
import { jsonldGallery } from "@/lib/jsonld.generated";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Examples — record → JSON-LD",
  description:
    "Real canonical battery records and the EMMO-aligned JSON-LD the BattINFO transform emits for them — generated by the actual library, not mocked.",
};

/**
 * The JSON-LD gallery: before/after pairs generated by the REAL Python
 * transform (scripts/gen_web_jsonld.py) and drift-checked by the test suite.
 * Nothing on this page is illustrative or abbreviated — it is exactly what
 * the current library emits for the canonical example records.
 */
export default function ExamplesPage() {
  return (
    <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6">
      <header className="max-w-prose">
        <h1 className="text-4xl font-bold tracking-tight text-ink">Examples</h1>
        <p className="mt-4 text-lg text-ink-muted">
          Real records, real output. Each pair below is a canonical example
          record and the EMMO-aligned JSON-LD the BattINFO transform emits for
          it — generated by the actual library and kept in sync by the test
          suite, not hand-written for the website.
        </p>
      </header>

      {jsonldGallery.map((entry) => {
        const types = entry.jsonld["@type"];
        const typeList = Array.isArray(types) ? (types as string[]) : types ? [String(types)] : [];
        return (
          <section key={entry.slug} className="mt-14" id={entry.slug}>
            <div className="flex flex-wrap items-baseline justify-between gap-2">
              <h2 className="text-2xl font-semibold tracking-tight text-ink">{entry.label}</h2>
              <a
                href={`${site.github}/blob/main/${entry.sourceFile}`}
                target="_blank"
                rel="noreferrer"
                className="font-mono text-xs text-brand-600 hover:text-brand-700"
              >
                {entry.sourceFile}
              </a>
            </div>

            {typeList.length > 1 && (
              <div className="mt-3 flex flex-wrap gap-2">
                {typeList.map((t) => (
                  <span
                    key={t}
                    className="rounded-full border border-brand-200 bg-brand-50 px-2.5 py-1 font-mono text-xs text-brand-700"
                  >
                    {t}
                  </span>
                ))}
              </div>
            )}

            <p className="mt-3 max-w-prose text-sm text-ink-muted">{entry.highlight}</p>

            <div className="mt-6 grid gap-6 lg:grid-cols-2">
              <div>
                <h3 className="mb-2 text-sm font-semibold uppercase tracking-wider text-ink-faint">
                  Input — canonical record
                </h3>
                <CodeBlock
                  label={`${entry.recordType}.json`}
                  code={JSON.stringify(entry.record, null, 2)}
                />
              </div>
              <div>
                <h3 className="mb-2 text-sm font-semibold uppercase tracking-wider text-brand-600">
                  Output — EMMO JSON-LD (real transform output)
                </h3>
                <CodeBlock
                  label={`${entry.recordType}.jsonld`}
                  code={JSON.stringify(entry.jsonld, null, 2)}
                />
              </div>
            </div>
          </section>
        );
      })}

      <div className="mt-12 flex flex-wrap gap-4 text-sm">
        <Link href="/validate" className="font-semibold text-brand-600 hover:text-brand-700">
          Validate your own record →
        </Link>
        <Link href="/properties" className="font-semibold text-brand-600 hover:text-brand-700">
          Browse every property &amp; unit →
        </Link>
        <Link href="/publish" className="font-semibold text-brand-600 hover:text-brand-700">
          Publish your data →
        </Link>
      </div>
    </div>
  );
}
