import type { Metadata } from "next";
import Link from "next/link";
import { CodeBlock } from "@/components/code-block";
import { jsonldGallery } from "@/lib/jsonld.generated";
import { showcase } from "@/lib/showcase.generated";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Examples — describe your thing",
  description:
    "Materials, electrodes, electrolytes, cells, tests, datasets — real BattINFO authoring code for each, with the record it produces. Every snippet is executed against the current library.",
};

/**
 * The showcase: for each thing you can describe, the literal source of a
 * snippet in scripts/gen_web_examples.py and the record executing it
 * produced. Drift-checked by the test suite — nothing here is illustrative.
 */
export default function ExamplesPage() {
  return (
    <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6">
      <header className="max-w-prose">
        <h1 className="text-4xl font-bold tracking-tight text-ink">
          Describe your thing
        </h1>
        <p className="mt-4 text-lg text-ink-muted">
          Whatever is on your bench — a material, an electrode, a cell, a test,
          the data it produced — there is a record for it. Each example below
          is real authoring code and the record it produces, executed against
          the current library and kept in sync by the test suite.
        </p>
      </header>

      <nav className="mt-8 flex flex-wrap gap-2">
        {showcase.map((entry) => (
          <a
            key={entry.slug}
            href={`#${entry.slug}`}
            className="rounded-full border border-brand-200 bg-brand-50 px-3 py-1.5 text-sm font-semibold text-brand-700 hover:bg-brand-100"
          >
            {entry.title}
          </a>
        ))}
      </nav>

      {showcase.map((entry) => (
        <section key={entry.slug} className="mt-14 scroll-mt-24" id={entry.slug}>
          <h2 className="text-2xl font-semibold tracking-tight text-ink">
            {entry.title}
          </h2>
          <p className="mt-2 max-w-prose text-sm text-ink-muted">{entry.tagline}</p>

          <div className="mt-5 grid gap-6 lg:grid-cols-2">
            <div>
              <h3 className="mb-2 text-sm font-semibold uppercase tracking-wider text-ink-faint">
                You write
              </h3>
              <CodeBlock label="Python" code={entry.code} />
            </div>
            <div>
              <h3 className="mb-2 text-sm font-semibold uppercase tracking-wider text-brand-600">
                You get — a validated, linkable record
              </h3>
              <CodeBlock
                label={`${entry.slug}.json`}
                code={JSON.stringify(entry.record, null, 2)}
              />
            </div>
          </div>
        </section>
      ))}

      <section className="mt-20 border-t border-line pt-12" id="jsonld">
        <h2 className="text-3xl font-bold tracking-tight text-ink">
          Under the hood: record → JSON-LD
        </h2>
        <p className="mt-3 max-w-prose text-ink-muted">
          Every record above has a Linked Data form: the same content, typed
          against the EMMO battery ontology so machines can reason over it.
          Three flagship pairs, generated by the actual transform:
        </p>

        {jsonldGallery.map((entry) => {
          const types = entry.jsonld["@type"];
          const typeList = Array.isArray(types) ? (types as string[]) : types ? [String(types)] : [];
          return (
            <section key={entry.slug} className="mt-12" id={`jsonld-${entry.slug}`}>
              <div className="flex flex-wrap items-baseline justify-between gap-2">
                <h3 className="text-xl font-semibold tracking-tight text-ink">{entry.label}</h3>
                <a
                  href={`${site.github}/blob/main/${entry.sourceFile}`}
                  target="_blank"
                  rel="noreferrer"
                  className="font-mono text-xs text-brand-600 hover:text-brand-700"
                >
                  {entry.sourceFile}
                </a>
              </div>

              {typeList.length > 1 && (
                <div className="mt-3 flex flex-wrap gap-2">
                  {typeList.map((t) => (
                    <span
                      key={t}
                      className="rounded-full border border-brand-200 bg-brand-50 px-2.5 py-1 font-mono text-xs text-brand-700"
                    >
                      {t}
                    </span>
                  ))}
                </div>
              )}

              <p className="mt-3 max-w-prose text-sm text-ink-muted">{entry.highlight}</p>

              <div className="mt-3 flex flex-wrap gap-4 text-xs font-semibold">
                <a
                  href={`https://json-ld.org/playground/#startTab=tab-expanded&json-ld=${encodeURIComponent(`${site.url}/jsonld/${entry.slug}.jsonld`)}`}
                  target="_blank"
                  rel="noreferrer"
                  className="text-brand-600 hover:text-brand-700"
                >
                  Open in the JSON-LD Playground →
                </a>
                <a
                  href={`/jsonld/${entry.slug}.jsonld`}
                  target="_blank"
                  rel="noreferrer"
                  className="text-ink-faint hover:text-ink"
                >
                  Raw JSON-LD
                </a>
              </div>

              <div className="mt-6 grid gap-6 lg:grid-cols-2">
                <div>
                  <h4 className="mb-2 text-sm font-semibold uppercase tracking-wider text-ink-faint">
                    Input — canonical record
                  </h4>
                  <CodeBlock
                    label={`${entry.recordType}.json`}
                    code={JSON.stringify(entry.record, null, 2)}
                  />
                </div>
                <div>
                  <h4 className="mb-2 text-sm font-semibold uppercase tracking-wider text-brand-600">
                    Output — EMMO JSON-LD (real transform output)
                  </h4>
                  <CodeBlock
                    label={`${entry.recordType}.jsonld`}
                    code={JSON.stringify(entry.jsonld, null, 2)}
                  />
                </div>
              </div>
            </section>
          );
        })}
      </section>

      <div className="mt-12 flex flex-wrap gap-4 text-sm">
        <Link href="/validate" className="font-semibold text-brand-600 hover:text-brand-700">
          Validate your own record →
        </Link>
        <Link href="/publish" className="font-semibold text-brand-600 hover:text-brand-700">
          Publish your data →
        </Link>
      </div>
    </div>
  );
}
