// Build-time context sync — same discipline as sync-schemas.mjs.
//
// The JSON-LD workbench must resolve our hosted records @context offline (the
// site makes no network calls at runtime). The canonical context lives in
// src/battinfo/data/context/records.context.json; this script embeds it into a
// GENERATED, COMMITTED module so the Vercel build stays self-contained. When a
// pasted document references the hosted context URL, the workbench feeds this
// vendored copy to the expander instead of fetching anything.
//
//   Run:   npm run sync:context
//   CI:    npm run sync:context -- --check   (fails on drift)
//
// No dependencies; Node ESM only.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const SOURCE = resolve(repoRoot, "src", "battinfo", "data", "context", "records.context.json");
// The hosted URL the Python transform stamps into documents (jsonld.py).
const CONTEXT_URL = "https://w3id.org/battinfo/context/records/v1.json";
const OUT = resolve(here, "..", "lib", "records-context.generated.ts");

const context = JSON.parse(readFileSync(SOURCE, "utf-8"));

const banner = `// GENERATED by scripts/sync-context.mjs — do not edit.
// Source of truth: src/battinfo/data/context/records.context.json.
// Regenerate with \`npm run sync:context\`; CI fails if this file drifts.

`;

const body =
  banner +
  `export const RECORDS_CONTEXT_URL = ${JSON.stringify(CONTEXT_URL)};\n\n` +
  "export const recordsContext: Record<string, unknown> = " +
  JSON.stringify(context, null, 2) +
  ";\n";

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf-8") : "";
  if (current.replace(/\r\n/g, "\n") !== body.replace(/\r\n/g, "\n")) {
    console.error(
      "lib/records-context.generated.ts drifts from src/battinfo/data/context/records.context.json.\n" +
        "Run `npm run sync:context` in web/ and commit the result.",
    );
    process.exit(1);
  }
  console.log("records context in sync.");
} else {
  writeFileSync(OUT, body);
  console.log(`Wrote ${OUT}.`);
}
