// Build-time schema sync — vendored-with-sync (see docs/CONTENT-MODEL.md §4).
//
// The in-browser validator must run the REAL canonical JSON Schemas, not a
// hand-rolled approximation — the whole point of the tool is that the browser
// and `battinfo validate` give the same verdict. The canonical schemas live in
// src/battinfo/data/schemas/**; this script embeds them into a GENERATED,
// COMMITTED module so the Vercel build stays self-contained. The registry
// vendors the same tree with the same discipline (its sync_battinfo_schemas.py
// --check); the web is simply the third consumer of one contract.
//
//   Run:   npm run sync:schemas
//   CI:    npm run sync:schemas -- --check   (fails on drift)
//
// No dependencies; Node ESM only.

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const SCHEMA_ROOT = resolve(repoRoot, "src", "battinfo", "data", "schemas");
const OUT = resolve(here, "..", "lib", "schemas.generated.ts");

function* walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else if (entry.name.endsWith(".json")) yield full;
  }
}

const files = [...walk(SCHEMA_ROOT)].sort();
const schemas = files.map((file) => {
  const parsed = JSON.parse(readFileSync(file, "utf-8"));
  return {
    path: relative(SCHEMA_ROOT, file).split(sep).join("/"),
    schema: parsed,
  };
});

const banner = `// GENERATED by scripts/sync-schemas.mjs — do not edit.
// Source of truth: src/battinfo/data/schemas/** (${schemas.length} files).
// Regenerate with \`npm run sync:schemas\`; CI fails if this file drifts.

`;

const body =
  banner +
  "export const schemaFiles: { path: string; schema: Record<string, unknown> }[] = " +
  JSON.stringify(schemas, null, 2) +
  ";\n";

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf-8") : "";
  if (current.replace(/\r\n/g, "\n") !== body.replace(/\r\n/g, "\n")) {
    console.error(
      "lib/schemas.generated.ts drifts from src/battinfo/data/schemas/**.\n" +
        "Run `npm run sync:schemas` in web/ and commit the result.",
    );
    process.exit(1);
  }
  console.log(`schemas in sync (${schemas.length} files).`);
} else {
  writeFileSync(OUT, body);
  console.log(`Wrote ${OUT} (${schemas.length} schemas).`);
}
