"""Chemical-substance resolution against the shipped substances vocabulary.

The vocabulary (``data/vocab/substances.json``, generated by
``tools/substances/build_vocab.py``) maps the symbols battery people actually
write ("EC", "LiPF6", "TTE") to pinned chemical identity: InChIKey as the
canonical key, with PubChem CID, CAS, SMILES, and the domain-chemical-substance
(chemsub) EMMO class as crosswalk. Resolution is exact-match only and happens
once, at authoring time — the resolved identity is stamped into the record and
never recomputed. Fuzzy matching is used solely for "did you mean" suggestions.

A symbol may appear more than once only when two different substances share it
(EC: ethylene carbonate vs ethyl cellulose). Such collisions are broken by the
record slot the component occupies (solvent_mixture / salt / additive / binder /
plasticizer / host), which callers pass as ``slot``; the vocabulary's ``roles``
are collision discriminators, never usage constraints.
"""

from __future__ import annotations

import difflib
import json
from dataclasses import dataclass, field
from functools import lru_cache
from importlib import resources
from pathlib import Path
from typing import Any


class AmbiguousSubstanceError(ValueError):
    """A name matched more than one substance and the slot did not discriminate."""

    def __init__(self, name: str, candidates: list["Substance"]):
        self.name = name
        self.candidates = candidates
        options = "; ".join(
            f"{c.label or c.symbol} (roles: {', '.join(c.roles) or 'any'})" for c in candidates
        )
        super().__init__(
            f"substance name {name!r} is ambiguous: {options}. "
            "Pass the record slot (e.g. slot='solvent' or slot='binder') to disambiguate."
        )


@dataclass(frozen=True)
class Substance:
    """One resolved substance: pinned identity plus crosswalk."""

    symbol: str
    identity_basis: str  # "structure" | "label"
    label: str = ""
    roles: tuple[str, ...] = ()
    inchikey: str | None = None
    pubchem_cid: int | None = None
    cas_number: str | None = None
    smiles: str | None = None
    formula: str | None = None
    molar_mass: float | None = None
    chemsub_iri: str | None = None
    ions: dict[str, str] = field(default_factory=dict)

    def identity_fields(self) -> dict[str, Any]:
        """The fields a builder stamps into a record component (only what is known)."""
        out: dict[str, Any] = {}
        if self.inchikey:
            out["inchikey"] = self.inchikey
        if self.pubchem_cid:
            out["pubchem_cid"] = self.pubchem_cid
        if self.cas_number:
            out["cas_number"] = self.cas_number
        if self.smiles:
            out["smiles"] = self.smiles
        if self.label:
            out["label"] = self.label
        return out


def _load_vocab_file() -> dict[str, Any]:
    packaged_path = resources.files("battinfo").joinpath("data", "vocab", "substances.json")
    if packaged_path.is_file():
        with packaged_path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    repo_root = Path(__file__).resolve().parents[2]
    asset_path = repo_root.joinpath("src", "battinfo", "data", "vocab", "substances.json")
    if asset_path.is_file():
        with asset_path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    return {"version": "0", "substances": []}


@lru_cache(maxsize=1)
def _vocab_with_aliases() -> list[tuple[Substance, frozenset[str]]]:
    """Each substance with its normalized lookup keys (symbol, label, chemsub label)."""
    entries: list[tuple[Substance, frozenset[str]]] = []
    for raw in _load_vocab_file().get("substances", []):
        sub = Substance(
            symbol=raw["symbol"],
            identity_basis=raw.get("identity_basis", "label"),
            label=raw.get("label", ""),
            roles=tuple(raw.get("roles", [])),
            inchikey=raw.get("inchikey"),
            pubchem_cid=raw.get("pubchem_cid"),
            cas_number=raw.get("cas_number"),
            smiles=raw.get("smiles"),
            formula=raw.get("formula"),
            molar_mass=raw.get("molar_mass"),
            chemsub_iri=raw.get("chemsub_iri"),
            ions=dict(raw.get("ions", {})),
        )
        keys = {_normalize(sub.symbol)}
        if sub.label:
            keys.add(_normalize(sub.label))
        # chemsub CamelCase labels double as long-name aliases (EthyleneCarbonate)
        if raw.get("chemsub_label"):
            keys.add(_normalize(raw["chemsub_label"]))
        entries.append((sub, frozenset(keys)))
    return entries


def _vocab() -> list[Substance]:
    return [sub for sub, _ in _vocab_with_aliases()]


def _normalize(name: str) -> str:
    return "".join(name.lower().split()).replace("-", "").replace("_", "")


@lru_cache(maxsize=1)
def _index() -> dict[str, list[Substance]]:
    index: dict[str, list[Substance]] = {}
    for sub, keys in _vocab_with_aliases():
        for key in keys:
            index.setdefault(key, []).append(sub)
    return index


def resolve(name: str, slot: str | None = None) -> Substance | None:
    """Resolve a human-written substance name to its pinned identity.

    Exact match after normalization (case, whitespace, hyphens). A name unique
    in the vocabulary resolves regardless of slot; a colliding name uses the
    slot to pick the candidate whose roles include it. Returns None for an
    unknown name (use :func:`suggest` for a "did you mean" hint); raises
    :class:`AmbiguousSubstanceError` when the slot cannot discriminate.
    """
    if not name or not name.strip():
        return None
    candidates = _index().get(_normalize(name), [])
    if not candidates:
        return None
    if len(candidates) == 1:
        return candidates[0]
    if slot:
        slotted = [c for c in candidates if slot in c.roles or not c.roles]
        if len(slotted) == 1:
            return slotted[0]
        if slotted:
            candidates = slotted
    raise AmbiguousSubstanceError(name, candidates)


def suggest(name: str, limit: int = 3) -> list[str]:
    """Nearby known symbols/labels for an unresolved name. Never auto-applied."""
    if not name or not name.strip():
        return []
    keys = sorted({s.symbol for s in _vocab()} | {s.label for s in _vocab() if s.label})
    return difflib.get_close_matches(name.strip(), keys, n=limit, cutoff=0.6)


def substance_symbols() -> list[str]:
    """All symbols in the vocabulary, sorted, duplicates collapsed."""
    return sorted({s.symbol for s in _vocab()})


def vocabulary_version() -> str:
    return str(_load_vocab_file().get("version", "0"))
