"""Generate the website's JSON-LD gallery from canonical examples.

The /examples page shows record → JSON-LD before/after pairs. Porting the
semantic transform to TypeScript would be a permanent drift risk, so the REAL
Python transform (`battinfo.record_to_jsonld`) runs here at author time and
the output is committed (web/lib/jsonld.generated.ts). A pytest
(tests/test_web_generated.py) regenerates in-memory and fails on drift, so the
gallery always shows exactly what the current library emits.

Usage:
    uv run python scripts/gen_web_jsonld.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from battinfo import record_to_jsonld  # noqa: E402

NL = chr(10)
OUT = ROOT / "web" / "lib" / "jsonld.generated.ts"

# Curated flagship pairs: one product spec, one measurement activity, one data
# asset — enough to show @type stacking, the provenance chain, and DCAT.
GALLERY = [
    {
        "slug": "cell-spec",
        "label": "Cell spec — A123 ANR26650M1-B",
        "recordType": "cell-spec",
        "file": "examples/cell-spec/A123__ANR26650M1-B.json",
        "highlight": "EMMO @type stacking: one cylindrical LFP cell is simultaneously a BatteryCell, a CylindricalBattery, and a LithiumIronPhosphateBattery — no manual annotation.",
    },
    {
        "slug": "test",
        "label": "Test — baseline cycling on a tracked cell",
        "recordType": "test",
        "file": "examples/test/test-5p7v-2n8k-4m3t-6q9r.json",
        "highlight": "The test points at the physical cell it ran on (prov:used), so every number stays attached to its subject.",
    },
    {
        "slug": "dataset",
        "label": "Dataset — the files a test produced",
        "recordType": "dataset",
        "file": "examples/dataset/dataset-1f8r-6v2k-9p4m-3t7x.json",
        "highlight": "Datasets are DCAT: catalogable, with distributions and checksums — the shape data portals already understand.",
    },
]


def build_entries() -> list[dict]:
    entries = []
    for item in GALLERY:
        record = json.loads((ROOT / item["file"]).read_text(encoding="utf-8"))
        jsonld = record_to_jsonld(record, item["recordType"])
        entries.append(
            {
                "slug": item["slug"],
                "label": item["label"],
                "recordType": item["recordType"],
                "sourceFile": item["file"],
                "highlight": item["highlight"],
                "record": record,
                "jsonld": jsonld,
            }
        )
    return entries


def render(entries: list[dict]) -> str:
    banner = (
        "// GENERATED by scripts/gen_web_jsonld.py — do not edit.\n"
        "// Each pair is the canonical example record and the JSON-LD the REAL\n"
        "// Python transform emits for it (battinfo.record_to_jsonld).\n"
        "// tests/test_web_generated.py fails when this file drifts from the library.\n\n"
    )
    body = (
        "export const jsonldGallery: {\n"
        "  slug: string;\n"
        "  label: string;\n"
        "  recordType: string;\n"
        "  sourceFile: string;\n"
        "  highlight: string;\n"
        "  record: Record<string, unknown>;\n"
        "  jsonld: Record<string, unknown>;\n"
        "}[] = " + json.dumps(entries, indent=2, ensure_ascii=False) + ";\n"
    )
    return banner + body


PUBLIC_DIR = ROOT / "web" / "public" / "jsonld"


def render_public(entries: list) -> dict:
    """Raw JSON-LD documents served at /jsonld/<slug>.jsonld — permalinks the
    W3C JSON-LD Playground can fetch (CORS headers set in web/vercel.json)."""
    return {
        entry["slug"] + ".jsonld": json.dumps(entry["jsonld"], indent=2, ensure_ascii=False) + NL
        for entry in entries
    }


def main() -> int:
    entries = build_entries()
    OUT.write_text(render(entries), encoding="utf-8", newline=NL)
    PUBLIC_DIR.mkdir(parents=True, exist_ok=True)
    for name, text in render_public(entries).items():
        (PUBLIC_DIR / name).write_text(text, encoding="utf-8", newline=NL)
    print(f"Wrote {OUT} + {len(entries)} public jsonld files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
