"""Generate the schema reference page from the canonical JSON Schemas.

One row of truth per record type: discriminator key, required fields, and a
link to the schema file. Committed output; tests/test_generated_reference.py
regenerates in memory and fails on drift.

Usage:
    uv run python scripts/gen_schema_reference.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from battinfo.entities import ENTITY_KINDS  # noqa: E402

SCHEMAS = ROOT / "src" / "battinfo" / "data" / "schemas"
OUT = ROOT / "docs" / "pages" / "schema-reference.md"
GITHUB = "https://github.com/BIG-MAP/BattINFO/blob/main/src/battinfo/data/schemas"


def build() -> str:
    lines = [
        "# JSON Schema reference",
        "",
        "<!-- GENERATED by scripts/gen_schema_reference.py — do not edit.",
        "     Regenerate with `uv run python scripts/gen_schema_reference.py`. -->",
        "",
        "Every canonical record validates against one of these JSON Schemas",
        "(draft 2020-12) — the same files enforced by `battinfo validate`, the",
        "registry's publish gate, and the [browser validator](https://battinfo.org/validate).",
        "",
    ]
    kinds = list(ENTITY_KINDS)
    for kind in kinds:
        schema_path = SCHEMAS / kind.schema_file
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        required = schema.get("required", [])
        body = (schema.get("properties", {}) or {}).get(kind.record_key, {})
        body_required = body.get("required", []) if isinstance(body, dict) else []
        lines += [
            f"## {kind.entity_type}",
            "",
            f"- **Record key (discriminator):** `{kind.record_key}`",
            f"- **Required top-level:** {', '.join(f'`{r}`' for r in required) or '—'}",
            f"- **Required in `{kind.record_key}`:** {', '.join(f'`{r}`' for r in body_required) or '—'}",
            f"- **Schema:** [`{kind.schema_file}`]({GITHUB}/{kind.schema_file})",
            "",
        ]
    lines += [
        "## organization",
        "",
        "- **Record key (discriminator):** `organization`",
        f"- **Schema:** [`organization.schema.json`]({GITHUB}/organization.schema.json)",
        "",
        "Shared building blocks (quantities, provenance, component modules) live in",
        f"[`modules/`]({GITHUB}/modules).",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    OUT.write_text(build(), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
