"""Generate assets/vocab/emmo-labels.ttl - skos:prefLabel for every EMMO term used.

Companion to the records vocabulary (IDENTIFIER_POLICY.md section 14: the human
layer is labels, not identifiers). One triple per EMMO-family term the emitters
use:

    <full-iri> skos:prefLabel "Label"@en .

The term set is the same table the publication emitters use to build inline
contexts (battinfo.transform.cell_spec_node.label_to_compact): the static core
classes, the curated property-map class IRIs, the curated unit-map unit IRIs,
the entity_type_map battery classes, and the quantity-node structure terms.
When two labels resolve to one IRI, the first (sorted) label is the prefLabel
and the rest become skos:altLabel.

tests/test_generated_reference.py regenerates in memory and fails on drift.

Usage:
    uv run python scripts/gen_emmo_labels.py
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Mapping

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from battinfo.transform.cell_spec_node import _COMPACT_PREFIXES, label_to_compact  # noqa: E402

OUT = ROOT / "assets" / "vocab" / "emmo-labels.ttl"


def _expand(compact: str) -> str:
    for prefix, base in _COMPACT_PREFIXES:
        if compact.startswith(prefix):
            return base + compact[len(prefix):]
    return compact


def _iri_of(value: object) -> str | None:
    if isinstance(value, str):
        return _expand(value)
    if isinstance(value, Mapping) and isinstance(value.get("@id"), str):
        return _expand(value["@id"])
    return None


def build() -> str:
    labels_by_iri: dict[str, list[str]] = {}
    for label, value in label_to_compact().items():
        iri = _iri_of(value)
        if iri is None or "://" not in iri:
            continue
        bucket = labels_by_iri.setdefault(iri, [])
        if label not in bucket:
            bucket.append(label)
    lines = [
        "# GENERATED by scripts/gen_emmo_labels.py - do not edit.",
        "# skos:prefLabel companion for every EMMO-family term the BattINFO",
        "# emitters use (property classes, units, battery classes, structure",
        "# terms), so exported RDF is human-readable without loading EMMO.",
        "@prefix skos: <http://www.w3.org/2004/02/skos/core#> .",
        "",
    ]
    for iri in sorted(labels_by_iri):
        pref, *alts = sorted(labels_by_iri[iri])
        entry = f'<{iri}> skos:prefLabel "{pref}"@en'
        for alt in alts:
            entry += f' ;\n    skos:altLabel "{alt}"@en'
        lines.append(entry + " .")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    text = build()
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT} ({text.count(chr(62) + ' skos:prefLabel')} label entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
