"""Generate the property & unit reference page from the curated mapping tables.

These tables are the single source of truth for how `properties={...}` keys
and unit symbols become EMMO IRIs in the emitted JSON-LD. Committed output;
tests/test_generated_reference.py regenerates in memory and fails on drift.

Usage:
    uv run python scripts/gen_property_reference.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAPPINGS = ROOT / "assets" / "mappings" / "domain-battery"
OUT = ROOT / "docs" / "pages" / "property-reference.md"


def build() -> str:
    props = json.loads(
        (MAPPINGS / "property_map.curated.json").read_text(encoding="utf-8")
    )["mappings"]
    units = json.loads(
        (MAPPINGS / "unit_map.curated.json").read_text(encoding="utf-8")
    )["mappings"]

    lines = [
        "# Property & unit reference",
        "",
        "<!-- GENERATED by scripts/gen_property_reference.py — do not edit.",
        "     Regenerate with `uv run python scripts/gen_property_reference.py`. -->",
        "",
        "Every quantity you author — `{\"value\": 5.0, \"unit\": \"Ah\"}` under a",
        "`properties` key — is mapped to an EMMO class, and every unit symbol to a",
        "unit IRI, by the curated mapping tables under",
        "`assets/mappings/domain-battery/` — the single source of truth for the",
        "semantics of emitted JSON-LD. This page is generated from those tables.",
        "",
        f"## Properties ({len(props)})",
        "",
        "The keys accepted in `properties={...}` on a cell spec, and the EMMO",
        "class each becomes in JSON-LD:",
        "",
        "| Key | EMMO class |",
        "|---|---|",
    ]
    for p in sorted(props, key=lambda p: p["key"]):
        lines.append(f"| `{p['key']}` | [{p['class_pref_label']}]({p['class_iri']}) |")

    lines += [
        "",
        f"## Units ({len(units)})",
        "",
        "The unit symbols accepted in quantity dicts, and the unit IRI each maps",
        "to (EMMO where a term exists, QUDT as the documented fallback):",
        "",
        "| Symbol | Unit |",
        "|---|---|",
    ]
    for u in sorted(units, key=lambda u: u["symbol"].lower()):
        lines.append(f"| `{u['symbol']}` | [{u['unit_pref_label']}]({u['unit_iri']}) |")

    lines += [
        "",
        "Unknown keys and symbols are refused, not guessed — see the",
        "[validation contract](../validation-contract.md) for how mapping gaps",
        "surface as machine-readable issues.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    OUT.write_text(build(), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
