"""Generate the battinfo: record-layer vocabulary (Turtle) from the code.

The exports mint ~49 `battinfo:` terms (https://w3id.org/battinfo/<term>) that
were defined nowhere — no SPARQL join or ontology lookup could say what any of
them meant (red-team W3.6). This script scans the source for every emitted
`battinfo:` CURIE and writes assets/vocab/battinfo-records.ttl declaring each
one (owl:Class when Capitalized, rdf:Property otherwise) with a label derived
from the term name. tests/test_generated_reference.py regenerates in memory
and fails on drift, so a new emitted term cannot ship undefined.

Serving: w3id.org/battinfo/<term> should resolve to this document (W2 routing
work); the namespace is the SLASH form by decision — the hash form belongs to
the ontology.

Usage:
    uv run python scripts/gen_battinfo_vocab.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "vocab" / "battinfo-records.ttl"

TERM_RE = re.compile(r'"battinfo:([A-Za-z_][A-Za-z0-9_]*)"')
SCAN = ["src/battinfo"]
SUFFIXES = {".py", ".json"}


def collect_terms() -> list[str]:
    terms: set[str] = set()
    for base in SCAN:
        for path in (ROOT / base).rglob("*"):
            if path.suffix in SUFFIXES and path.is_file():
                terms.update(TERM_RE.findall(path.read_text(encoding="utf-8", errors="ignore")))
    return sorted(terms)


def label_of(term: str) -> str:
    words = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", term.replace("_", " "))
    return words[0].upper() + words[1:]


def build() -> str:
    terms = collect_terms()
    lines = [
        "# GENERATED by scripts/gen_battinfo_vocab.py - do not edit.",
        "# Every battinfo: term the library emits, so the record-layer",
        "# vocabulary at https://w3id.org/battinfo/ resolves for consumers.",
        "@prefix battinfo: <https://w3id.org/battinfo/> .",
        "@prefix owl: <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix dcterms: <http://purl.org/dc/terms/> .",
        "",
        "<https://w3id.org/battinfo/> a owl:Ontology ;",
        '    rdfs:label "BattINFO record-layer vocabulary"@en ;',
        '    rdfs:comment "Terms used by canonical BattINFO record exports '
        "(JSON-LD). This is the record/data layer under the slash namespace; "
        'the EMMO-based battery ontology lives in its own hash namespace."@en ;',
        "    dcterms:source <https://github.com/BIG-MAP/BattINFO> .",
        "",
    ]
    for term in terms:
        kind = "owl:Class" if term[0].isupper() else "rdf:Property"
        lines += [
            f"battinfo:{term} a {kind} ;",
            f'    rdfs:label "{label_of(term)}"@en ;',
            "    rdfs:isDefinedBy <https://w3id.org/battinfo/> .",
            "",
        ]
    return "\n".join(lines)


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT} ({len(collect_terms())} terms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
