import type { Metadata } from "next";
import Link from "next/link";
import { CodeBlock } from "@/components/code-block";
import { SectionHeading } from "@/components/section-heading";
import { converterMatrix } from "@/lib/content";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Convert your cycler data, BattINFO",
  description:
    "Which instrument formats ws.convert() handles, auto-detected, with an explicit pattern, or after a CSV export, and what you get back.",
};

const CONVERT_SNIPPET = `import battinfo
ws = battinfo.workspace(".")

ws.convert()          # NEWARE / Biologic / Excel / MATLAB auto-detected
ws.convert("*.csv")   # Digatron / Landt / Novonix / generic CSV exports
# -> bdf/*.bdf.csv    one tidy, documented table format for all of them`;

function FormatTable({
  rows,
  caption,
}: {
  rows: readonly { ext: string; source: string }[];
  caption: string;
}) {
  return (
    <div className="overflow-x-auto rounded-xl border border-border">
      <table className="w-full text-left text-sm">
        <thead className="bg-paper text-xs uppercase tracking-wider text-ink-faint">
          <tr>
            <th className="px-4 py-3 w-28">Extension</th>
            <th className="px-4 py-3">{caption}</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-border">
          {rows.map((row) => (
            <tr key={row.ext + row.source} className="bg-surface">
              <td className="px-4 py-2.5 font-mono text-xs text-ink">{row.ext}</td>
              <td className="px-4 py-2.5 text-ink-muted">{row.source}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

/**
 * The honest capability page for data conversion. No in-browser conversion
 * demo: instrument parsing needs the real Python stack, and pretending
 * otherwise in TypeScript would be a drift machine. Instead: exactly what
 * converts, how, and what you get, with the JSON-LD story handed off to the
 * gallery, where the output shown is generated by the real transform.
 */
export default function ConvertPage() {
  return (
    <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6">
      <header className="max-w-prose">
        <h1 className="text-4xl font-bold tracking-tight text-ink">Convert your cycler data</h1>
        <p className="mt-4 text-lg text-ink-muted">
          Every instrument speaks its own format, the first wall between your
          data and anyone else&rsquo;s tools. <code className="text-sm">ws.convert()</code>{" "}
          turns what your cycler wrote into BDF: one tidy, documented table
          format that every later step (and every colleague) can read.
        </p>
      </header>

      <div className="mt-8 max-w-3xl">
        <CodeBlock label="in your terminal" code={CONVERT_SNIPPET} />
      </div>

      <section className="mt-12">
        <SectionHeading kicker="What converts" title="What the converter can do today." />
        <p className="mt-3 max-w-prose text-sm text-ink-muted">
          This table is checked against the library&rsquo;s own guidance in CI, so it
          cannot overpromise.
        </p>
        <div className="mt-6 grid gap-8 lg:grid-cols-3">
          <div>
            <h3 className="mb-3 text-sm font-semibold text-ink">
              Auto-detected, just run <code className="text-xs">ws.convert()</code>
            </h3>
            <FormatTable rows={converterMatrix.autoDetected} caption="Instrument" />
          </div>
          <div>
            <h3 className="mb-3 text-sm font-semibold text-ink">
              With a pattern, <code className="text-xs">ws.convert(&quot;*.csv&quot;)</code>
            </h3>
            <FormatTable rows={converterMatrix.explicitPattern} caption="Instrument" />
          </div>
          <div>
            <h3 className="mb-3 text-sm font-semibold text-ink">Export a CSV first</h3>
            <FormatTable rows={converterMatrix.exportCsvFirst} caption="Instrument" />
            <p className="mt-2 text-xs text-ink-faint">
              Proprietary binaries: export CSV from the vendor software, then{" "}
              <code>ws.convert(&quot;*.csv&quot;)</code>.
            </p>
          </div>
        </div>
      </section>

      <section className="mt-14 rounded-2xl border border-border bg-surface p-6">
        <h2 className="text-lg font-semibold text-ink">What you get back</h2>
        <p className="mt-2 max-w-prose text-sm leading-relaxed text-ink-muted">
          <span className="font-mono text-xs">bdf/*.bdf.csv</span>, cycle, step,
          time, voltage, current, and capacity columns under one documented
          schema (run <code className="text-xs">ws.bdf_columns()</code> for the
          full list). From there,{" "}
          <Link href="/publish" className="font-semibold text-brand-600 hover:text-brand-700">
            the publishing journey
          </Link>{" "}
          attaches the converted file to a linked test record with provenance
          intact.
        </p>
      </section>

      <section className="mt-12">
        <SectionHeading
          kicker="The semantic layer"
          title="Want JSON-LD? See what the real transform emits."
        />
        <p className="mt-3 max-w-prose text-sm text-ink-muted">
          Records become EMMO-aligned JSON-LD at publish time. The examples
          gallery shows genuine before/after pairs, generated by the actual
          Python transform, drift-checked in CI, never mocked in the browser.
        </p>
        <div className="mt-5 flex flex-wrap gap-4 text-sm">
          <Link href="/examples" className="font-semibold text-brand-600 hover:text-brand-700">
            Open the JSON-LD gallery →
          </Link>
          <Link href="/properties" className="font-semibold text-brand-600 hover:text-brand-700">
            Browse properties &amp; units →
          </Link>
          <a
            href={site.reference}
            target="_blank"
            rel="noreferrer"
            className="font-semibold text-brand-600 hover:text-brand-700"
          >
            Developer reference →
          </a>
        </div>
      </section>
    </div>
  );
}
