name: CI tests
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install EMMO-python
      run: |
        pip install EMMO

    - name: Check EMMO
      run: |
        emmocheck --verbose --url-from-catalog battinfo.ttl -s test_namespace
