name: CI tests
on: [push]

jobs:

  emmocheck:
    name: EMMO Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"

    - name: Install EMMOntoPy
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt

    - name: Run EMMO Check
      run: |
        emmocheck --verbose --url-from-catalog \
          --skip test_namespace \
          --skip test_quantity_dimension \
          --configfile=.github/utils/emmocheck_config.yml \
          battinfo.ttl

  documentation-build:
    name: Documentation
    runs-on: ubuntu-latest

    env:
      PAGES_DIR: site

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements_docs.txt -r requirements.txt

    - name: Build documentation
      run: python ${GITHUB_WORKSPACE}/docs/scripts/build.py ${PAGES_DIR} && ls -lahR ${PAGES_DIR}

    - name: Publish ontologies
      run: python ${GITHUB_WORKSPACE}/.github/utils/publish_ontologies.py && ls -lahR ${PAGES_DIR}
      env:
        ONTODOC_DIR: '.'
        TMP_DIR: '.'
        PUBLISH_ONTOLOGIES_DIR: ontology
