name: CI tests
on: [push]

jobs:

  emmocheck:
    name: EMMO Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Install EMMOntoPy
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt

    - name: Run EMMO Check
      run: |
        emmocheck --verbose --url-from-catalog \
          --skip test_namespace \
          --skip test_quantity_dimension \
          --configfile=.github/utils/emmocheck_config.yml \
          battinfo.ttl

  documentation-build:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install Markdown==3.4.3 rdflib==6.3.2

    - name: Render documentation from md
      run: python docs/scripts/md_to_html.py

    - name: Publish ontologies
      run: python ${GITHUB_WORKSPACE}/.github/utils/publish_ontologies.py

    - name: Update GitHub Pages
      run: ${GITHUB_WORKSPACE}/${ONTODOC_DIR}/update-pages.sh TEST
