name: CI tests
on: [push]

jobs:

  emmocheck:
    name: EMMO Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.7

    - name: Install EMMOntoPy
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt

    - name: Run EMMO Check
      run: |
        emmocheck --verbose --url-from-catalog \
          --skip test_namespace \
          --skip test_quantity_dimension \
          --configfile=.github/utils/emmocheck_config.yml \
          battinfo.ttl


