name: "Sphinx: Render docs"

on: 
  push:
    branches:
      - 'master'
  pull_request:

env:
  GIT_USER_NAME: BattINFO Developers
  GIT_USER_EMAIL: "BattINFO@big-map.org"

jobs:

  updatepages:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements_docs.txt -r sphinx/requirements.txt

    - name: Render documentation from ttl
      run: python sphinx/ttl_to_rst.py

    - name: Build HTML
      run: |
        sudo apt-get update && sudo apt-get install -y pandoc
        make html
      working-directory: sphinx

    # Still upload built documentation as an artifact if not deploying
    # This is to provide the opportunity to download the built documentation
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentationHTML
        path: sphinx/_build/html/

    # Only deploy if pushing to 'master'
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: sphinx/_build/html
