name: "Sphinx: Render docs"

on: 
  push:
    branches:
      - 'master'
    
env:
  GIT_USER_NAME: BattINFO Developers
  GIT_USER_EMAIL: "BattINFO@big-map.org"
    
jobs:

  updatepages:
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5 #Uses python install action from here: https://github.com/marketplace?type=actions
      with:
        python-version: '3.10'  # Replace with the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Markdown==3.4.3 rdflib==6.3.2  # Add any other dependencies if needed
        
    - name: Render documentation from ttl
      run: python sphinx/ttl_to_rst.py

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "sphinx/"
        pre-build-command: "apt-get update -y; apt-get install -y pandoc"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentationHTML
        path: sphinx/_build/html/
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: sphinx/_build/html
      
