name: Update GitHub Pages

on:
  push:
    branches:
      - master  # Replace with the branch name you want to trigger the workflow on

env:
  GIT_USER_NAME: BattINFO Developers
  GIT_USER_EMAIL: "BattINFO@big-map.org"

jobs:
  updatepages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4 #Uses python install action from here: https://github.com/marketplace?type=actions
      with:
        python-version: '3.10'  # Replace with the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements_docs.txt

    - name: Build documentation
      run: python docs/scripts/build.py site

    - name: Commit updated documentation
      run: |
        cd ${GITHUB_WORKSPACE}
        git config --global user.email "${GIT_USER_EMAIL}"
        git config --global user.name "${GIT_USER_NAME}"
        git config pull.rebase false
        git add .
        git commit -m "Automatic update of github pages"
        git push origin master
